// Source éditable — quiz histoire-6. Régénéré automatiquement dans index.html via build.sh.
window.ALL_QUIZZES['histoire-6'] = {
  SEARCH_SITES: 'site:lumni.fr OR site:francetveducation.fr OR site:curiosphere.tv OR site:fr.khanacademy.org',
  YT_SUFFIX: 'histoire 6eme college antiquite',
  SUMMER_TOPIC: 'Histoire',
  SUBJECT: { id:'histoire-6', name:'Histoire', short:'Histoire', level:'Fin de 6ème', mark:'📜', tagline:'Évaluation diagnostique' },
  DOMAINS: {
    prehistoire: { id:'prehistoire', name:'Préhistoire et Néolithique',                    short:'Préhist.',  coef:2, color:'#78350f', icon:'⛰',    search:'prehistoire neolithique 6eme' },
    orient:      { id:'orient',      name:'Premières civilisations — Égypte & Mésopotamie', short:'Orient',    coef:2, color:'#b45309', icon:'𓂀',   search:'egypte mesopotamie 6eme' },
    grece:       { id:'grece',       name:'La Grèce antique — Athènes, démocratie',         short:'Grèce',     coef:3, color:'#1e40af', icon:'Ω',    search:'grece antique democratie 6eme' },
    rome:        { id:'rome',        name:'Rome — fondation, République, Empire',            short:'Rome',      coef:3, color:'#991b1b', icon:'SPQR', search:'rome antique republique empire 6eme' },
    religions:   { id:'religions',   name:'Judaïsme et naissance du christianisme',          short:'Religions', coef:2, color:'#7c3aed', icon:'✡',    search:'judaisme christianisme 6eme' },
    asie:        { id:'asie',        name:'Chine des Han et Inde des Gupta',                 short:'Asie',      coef:2, color:'#ca8a04', icon:'龍',   search:'chine han inde gupta 6eme' },
    reperes:     { id:'reperes',     name:'Repères chronologiques et vocabulaire',           short:'Repères',   coef:2, color:'#475569', icon:'⧗',    search:'chronologie antiquite reperes 6eme' },
  },
  RESOURCES: [
    { label:'Lumni — Histoire 6ème',         author:'France TV éducation',  url:'https://www.lumni.fr/college/sixieme/histoire-geographie' },
    { label:'France TV Éducation — Antiquité',author:'France Télévisions',  url:'https://www.francetveducation.fr/thematique/histoire/' },
    { label:'Curiosphère — Histoire antique', author:'France 5',            url:'https://www.curiosphere.tv/categories/histoire' },
    { label:'Khan Academy — Histoire mondiale',author:'Cours + exercices',  url:'https://fr.khanacademy.org/humanities/world-history' },
  ],
  POOL: {
    prehistoire: [
      { key:'pre-1', q:'Lucy est un célèbre fossile découvert en Éthiopie. À quelle espèce appartient-elle ?', options:['Homo sapiens','Homo erectus','Australopithecus','Homo habilis'], correct:2, hint:'Lucy a vécu il y a environ 3,2 millions d\'années — bien avant Homo sapiens.' },
      { key:'pre-2', q:'Homo sapiens est apparu il y a environ :', options:['500 000 ans','300 000 ans','10 000 ans','1 million d\'années'], correct:1, hint:'Les premiers Homo sapiens sont attestés en Afrique vers -300 000 ans.' },
      { key:'pre-3', q:'Les peintures rupestres de Lascaux se trouvent dans quel département français ?', options:['Ariège','Dordogne','Lot','Ardèche'], correct:1, hint:'Lascaux est en Dordogne (Périgord). Elles datent d\'environ 17 000 ans av. J.-C.' },
      { key:'pre-4', q:'Le Néolithique commence avec :', options:['L\'invention de l\'écriture','L\'agriculture, l\'élevage et la sédentarisation','La naissance de Rome','La construction des pyramides'], correct:1, hint:'Néolithique = «Pierre polie» : les humains deviennent agriculteurs et sédentaires vers -10 000.' },
      { key:'pre-5', q:'Au Paléolithique, les hommes vivaient surtout :', options:['Dans des maisons en pierre','De manière nomade, de chasse et de cueillette','En cultivant le blé','Dans des cités'], correct:1, hint:'Paléolithique = «Pierre taillée» : vie nomade, pas d\'agriculture.' },
      { key:'pre-6', q:'La sédentarisation signifie :', options:['Se déplacer selon les saisons','S\'installer de façon permanente dans un lieu fixe','Chasser de grands animaux','Sculpter des statues'], correct:1, hint:'Les premiers villages permanents apparaissent avec l\'agriculture au Néolithique.' },
      { key:'pre-7', q:'L\'outil caractéristique du Paléolithique est :', options:['La poterie','La hache en bronze','Le silex taillé','La charrue'], correct:2, hint:'Paléolithique = «vieille pierre taillée». Le silex est frappé pour obtenir un tranchant.' },
    ],
    orient: [
      { key:'ori-1', q:'En Égypte antique, le chef de l\'État s\'appelle :', options:['Consul','Pharaon','Roi','Sultan'], correct:1, hint:'Le pharaon est à la fois roi, chef militaire et dieu vivant en Égypte.' },
      { key:'ori-2', q:'L\'écriture inventée en Mésopotamie vers -3300 s\'appelle :', options:['L\'alphabet','Les hiéroglyphes','L\'écriture cunéiforme','Les runes'], correct:2, hint:'Cunéiforme vient de «cuneus» = coin. On gravait des signes en forme de clous dans l\'argile.' },
      { key:'ori-3', q:'Le fleuve essentiel à la civilisation égyptienne est :', options:['Le Tigre','L\'Euphrate','Le Nil','Le Jourdain'], correct:2, hint:'Le Nil fertilise ses rives lors des crues annuelles. Sans lui, l\'Égypte serait un désert.' },
      { key:'ori-4', q:'Les hiéroglyphes sont :', options:['Des lettres comme l\'alphabet','Des signes d\'écriture égyptiens (dessins)','Des chiffres arabes','Une langue parlée'], correct:1, hint:'Hiéroglyphe = «écriture sacrée gravée» en grec. Déchiffrés grâce à la pierre de Rosette.' },
      { key:'ori-5', q:'Le code d\'Hammourabi (vers -1750) est :', options:['Un temple babylonien','Un des premiers codes de lois écrits','Un récit mythologique','Une carte géographique'], correct:1, hint:'Hammourabi, roi de Babylone, a fait graver ses lois sur une stèle. Principe : œil pour œil.' },
      { key:'ori-6', q:'Les pyramides de Gizeh ont été construites pour :', options:['Stocker des céréales','Servir de tombeaux aux pharaons','Abriter les soldats','Observer les étoiles'], correct:1, hint:'Les pyramides sont les tombes monumentales des pharaons. Kheops, Khephren, Mykérinos à Gizeh.' },
      { key:'ori-7', q:'La Mésopotamie se trouve entre deux fleuves. Lesquels ?', options:['Nil et Congo','Tigre et Euphrate','Jourdain et Nil','Indus et Gange'], correct:1, hint:'«Mésopotamie» = «entre les fleuves» en grec : Tigre + Euphrate (actuel Irak).' },
      { key:'ori-8', q:'Toutankhamon est célèbre parce que :', options:['Il a conquis la Grèce','Sa tombe découverte en 1922 était intacte, remplie de trésors','Il a construit la grande pyramide','Il a inventé les hiéroglyphes'], correct:1, hint:'La découverte de sa tombe par Howard Carter en 1922 est l\'une des plus grandes trouvailles archéologiques.' },
    ],
    grece: [
      { key:'gre-1', q:'La cité-État grecque s\'appelle :', options:['L\'agora','La polis','L\'acropole','L\'amphithéâtre'], correct:1, hint:'Polis = cité-État. Chaque polis (Athènes, Sparte, Corinthe…) est indépendante.' },
      { key:'gre-2', q:'La démocratie athénienne au Ve siècle av. J.-C. signifie que :', options:['Le roi décide seul','Tous les habitants votent','Les citoyens (hommes libres nés à Athènes) participent aux décisions','Toutes les cités grecques sont réunies'], correct:2, hint:'«Démocratie» = «pouvoir du peuple» en grec. Mais femmes, esclaves, étrangers exclus.' },
      { key:'gre-3', q:'Périclès est un grand homme politique athénien du :', options:['VIIIe siècle av. J.-C.','Ve siècle av. J.-C.','IIIe siècle av. J.-C.','Ier siècle apr. J.-C.'], correct:1, hint:'Périclès dirige Athènes vers 461-429 av. J.-C. Il fait construire le Parthénon.' },
      { key:'gre-4', q:'L\'Iliade et l\'Odyssée sont des poèmes épiques attribués à :', options:['Platon','Homère','Aristote','Hérodote'], correct:1, hint:'Homère : deux épopées fondatrices (guerre de Troie et voyage d\'Ulysse). VIIIe s. av. J.-C.' },
      { key:'gre-5', q:'Les Jeux olympiques antiques se déroulaient à :', options:['Athènes','Sparte','Olympie','Corinthe'], correct:2, hint:'Olympie, dans le Péloponnèse. Jeux tous les 4 ans en l\'honneur de Zeus depuis -776.' },
      { key:'gre-6', q:'Alexandre le Grand est :', options:['Un pharaon égyptien','Un roi macédonien qui conquiert un vaste empire jusqu\'en Inde','Un consul romain','Un philosophe athénien'], correct:1, hint:'Alexandre III de Macédoine (356-323 av. J.-C.) conquiert la Perse, l\'Égypte et atteint l\'Inde.' },
      { key:'gre-7', q:'Le dieu suprême du panthéon grec est :', options:['Poséidon','Apollon','Zeus','Arès'], correct:2, hint:'Zeus règne sur l\'Olympe et sur tous les autres dieux. Maître du tonnerre.' },
      { key:'gre-8', q:'Sparte est connue pour être une cité :', options:['Marchande et artistique','Militaire et guerrière, où les garçons s\'entraînent dès 7 ans','Démocratique','Pacifiste'], correct:1, hint:'À Sparte, les garçons entrent à l\'agogé à 7 ans pour devenir des guerriers. Cité rivale d\'Athènes.' },
    ],
    rome: [
      { key:'rom-1', q:'Selon la légende, Rome a été fondée en -753 par :', options:['Jules César','Romulus et Rémus','Auguste','Virgile'], correct:1, hint:'Les jumeaux Romulus et Rémus, nourris par une louve. Romulus aurait fondé Rome et tué son frère.' },
      { key:'rom-2', q:'La République romaine (509-27 av. J.-C.) est dirigée par :', options:['Un pharaon','Deux consuls élus chaque année','Un seul roi à vie','Un sultan'], correct:1, hint:'Res publica = «chose publique». Deux consuls élus pour 1 an avec le Sénat.' },
      { key:'rom-3', q:'Jules César est assassiné en :', options:['-44 av. J.-C.','-27 av. J.-C.','476 apr. J.-C.','-753 av. J.-C.'], correct:0, hint:'Assassiné aux Ides de mars (-44). Son neveu Octave lui succède et devient Auguste.' },
      { key:'rom-4', q:'Auguste devient le premier empereur romain en :', options:['-509 av. J.-C.','-44 av. J.-C.','-27 av. J.-C.','476 apr. J.-C.'], correct:2, hint:'-27 marque la fin de la République et le début de l\'Empire romain. Octave prend le titre d\'Augustus.' },
      { key:'rom-5', q:'La Pax Romana désigne :', options:['Une guerre contre Carthage','Une longue période de paix et de prospérité dans l\'Empire romain','La chute de Rome','La fondation de Constantinople'], correct:1, hint:'Pax Romana = paix romaine. Environ 200 ans de stabilité (du règne d\'Auguste à la crise du IIIe s.).' },
      { key:'rom-6', q:'L\'Empire romain d\'Occident prend fin en :', options:['-27 av. J.-C.','313 apr. J.-C.','476 apr. J.-C.','380 apr. J.-C.'], correct:2, hint:'476 : déposition du dernier empereur Romulus Augustule par Odoacre. Date symbolique de la fin de l\'Antiquité.' },
      { key:'rom-7', q:'Le Colisée est un monument de Rome qui servait à :', options:['Stocker les archives de l\'État','Organiser des spectacles (combats de gladiateurs, combats d\'animaux)','Abriter le Sénat','Observer les astres'], correct:1, hint:'Le Colisée (Flavius) peut accueillir 50 000 spectateurs pour les jeux (munera, venationes).' },
      { key:'rom-8', q:'L\'armée romaine est organisée en :', options:['Cavalerie uniquement','Légions','Phalanges','Croisades'], correct:1, hint:'La légion romaine (~5 000 soldats) est l\'unité de base. Discipline, génie civil, routes.' },
    ],
    religions: [
      { key:'rel-1', q:'Le judaïsme est une religion :', options:['Polythéiste (plusieurs dieux)','Monothéiste (un seul Dieu)','Animiste','Sans dieu'], correct:1, hint:'Judaïsme = l\'une des premières religions monothéistes. Un seul Dieu (Yahvé), révélé à Moïse.' },
      { key:'rel-2', q:'Le livre sacré du judaïsme est :', options:['La Bible chrétienne','La Torah','Le Coran','Les Vedas'], correct:1, hint:'La Torah = les 5 premiers livres de la Bible. Elle contient la Loi donnée à Moïse sur le Sinaï.' },
      { key:'rel-3', q:'Jésus de Nazareth naît :', options:['Vers -753','Vers l\'an 0 (début de notre ère)','En 313','En 476'], correct:1, hint:'L\'ère chrétienne commence à la naissance supposée de Jésus (vers -4 à +6 selon les historiens).' },
      { key:'rel-4', q:'L\'édit de Milan (313) est signé par l\'empereur Constantin pour :', options:['Interdire le christianisme','Autoriser la pratique du christianisme dans l\'Empire','Détruire Jérusalem','Expulser les juifs'], correct:1, hint:'En 313, Constantin accorde la liberté de culte aux chrétiens, qui étaient persécutés.' },
      { key:'rel-5', q:'En 380, le christianisme devient :', options:['Interdit dans l\'Empire','La religion officielle de l\'Empire romain','Une religion mineure','Remplacé par le judaïsme'], correct:1, hint:'Édit de Thessalonique (380) : l\'empereur Théodose fait du christianisme la religion d\'État.' },
      { key:'rel-6', q:'Moïse est surtout connu pour :', options:['Avoir fondé Rome','Avoir reçu les dix commandements et conduit les Hébreux hors d\'Égypte','Avoir construit Jérusalem','Avoir écrit la Torah seul'], correct:1, hint:'Moïse est le prophète fondateur du judaïsme. Il reçoit les Tables de la Loi sur le mont Sinaï.' },
    ],
    asie: [
      { key:'asi-1', q:'La Grande Muraille de Chine a été construite à l\'origine pour :', options:['Délimiter les provinces','Protéger la Chine des invasions nomades du nord','Faciliter le commerce','Symboliser la puissance des empereurs'], correct:1, hint:'La muraille est renforcée sous les Han et surtout sous les Ming, pour stopper les raids des nomades.' },
      { key:'asi-2', q:'La route de la Soie reliait :', options:['Rome et Carthage','La Chine à l\'Europe et au Moyen-Orient','L\'Inde à l\'Afrique','Athènes à Babylone'], correct:1, hint:'La route de la Soie (à partir des Han, IIe s. av. J.-C.) permettait l\'échange de soie, épices, or.' },
      { key:'asi-3', q:'Confucius est un penseur chinois qui prône :', options:['La guerre permanente','Le respect des parents, des anciens et de l\'ordre social','La conquête militaire','L\'isolement de la Chine'], correct:1, hint:'Confucius (551-479 av. J.-C.) insiste sur la piété filiale, la vertu et l\'harmonie sociale.' },
      { key:'asi-4', q:'La dynastie Han gouverne la Chine de :', options:['-221 à -206','-206 à 220 apr. J.-C.','IVe au VIe siècle','VIIe au Xe siècle'], correct:1, hint:'Les Han (-206 à 220 apr. J.-C.) : grand empire unifié, route de la Soie, confucianisme comme doctrine officielle.' },
      { key:'asi-5', q:'Les chiffres que nous utilisons aujourd\'hui (1, 2, 3…) viennent de :', options:['La Grèce antique','Rome','L\'Inde (période Gupta)','La Chine Han'], correct:2, hint:'Les chiffres «arabes» ont été inventés en Inde, transmis par les Arabes à l\'Europe. Période Gupta (IVe-VIe s.).' },
      { key:'asi-6', q:'L\'hindouisme et le bouddhisme sont des religions nées :', options:['En Chine','En Inde','Au Moyen-Orient','En Grèce'], correct:1, hint:'L\'hindouisme est l\'une des plus anciennes religions du monde. Le bouddhisme naît en Inde avec Bouddha (~Ve s. av. J.-C.).' },
    ],
    reperes: [
      { key:'rep-1', q:'L\'abréviation «av. J.-C.» signifie :', options:['Avant les journées chrétiennes','Avant Jésus-Christ','Après Jésus-Christ','Avant le jugement chrétien'], correct:1, hint:'Av. J.-C. = avant Jésus-Christ. Les dates av. J.-C. se comptent à rebours (plus on recule, plus le chiffre est grand).' },
      { key:'rep-2', q:'Le Ve siècle av. J.-C. correspond aux années :', options:['-600 à -501','-500 à -401','-400 à -301','-300 à -201'], correct:1, hint:'Le Ve siècle = les années 400 à 500 (comptées av. J.-C.) soit -500 à -401. Siècle = 100 ans.' },
      { key:'rep-3', q:'L\'écriture apparaît en Mésopotamie vers :', options:['-10 000','-5000','-3300','-753'], correct:2, hint:'L\'écriture cunéiforme, inventée par les Sumériens, date d\'environ -3300 av. J.-C.' },
      { key:'rep-4', q:'La date -27 marque :', options:['La fondation de Rome','La naissance de Jésus','Le début de l\'Empire romain avec Auguste','La chute de l\'Empire romain d\'Occident'], correct:2, hint:'-27 : Octave reçoit le titre d\'Augustus. Fin de la République, début de l\'Empire.' },
      { key:'rep-5', q:'La date 476 marque :', options:['La naissance de Jésus','Le début de la Pax Romana','La chute de l\'Empire romain d\'Occident','L\'édit de Milan'], correct:2, hint:'476 apr. J.-C. : fin de l\'Antiquité. L\'Empire romain d\'Occident s\'effondre.' },
      { key:'rep-6', q:'Le mot «chronologie» désigne :', options:['L\'étude des roches','L\'ordre des événements dans le temps','La géographie des civilisations','Le nom d\'un dieu grec'], correct:1, hint:'Chrono = temps (grec). La chronologie classe les événements du plus ancien au plus récent.' },
      { key:'rep-7', q:'La République romaine dure de -509 à -27. Combien d\'années cela fait-il ?', options:['100 ans','300 ans','482 ans','753 ans'], correct:2, hint:'509 − 27 = 482 ans. La République romaine a duré presque 5 siècles.' },
    ],
  },
  PICK: {
    prehistoire: 3,
    orient:      4,
    grece:       6,
    rome:        6,
    religions:   3,
    asie:        3,
    reperes:     5,
  },
  PLANS: {
    prehistoire: {
      'non-acquis': ['Retenir Lucy (Australopithecus) et Homo sapiens (-300 000 ans)', 'Distinguer Paléolithique (chasse/cueillette nomade) et Néolithique (agriculture/sédentarisation)', 'Situer Lascaux dans le temps (environ -17 000)'],
      'fragile':    ['Mémoriser -10 000 comme date approximative du début du Néolithique'],
    },
    orient: {
      'non-acquis': ['Connaître les deux grandes civilisations : Égypte (Nil, pharaons, hiéroglyphes) et Mésopotamie (Tigre/Euphrate, cunéiforme)', 'Retenir -3300 pour l\'écriture cunéiforme et les pyramides de Gizeh', 'Distinguer hiéroglyphes (Égypte) et cunéiforme (Mésopotamie)'],
      'fragile':    ['Noms clés : Hammourabi (lois), Toutankhamon (tombe), Ramsès (grand pharaon)'],
    },
    grece: {
      'non-acquis': ['Comprendre ce qu\'est une polis (cité-État indépendante)', 'Définir la démocratie athénienne et ses limites (citoyens uniquement)', 'Connaître Périclès (Ve s.), les Jeux olympiques (Olympie), Homère (Iliade/Odyssée)'],
      'fragile':    ['Situer Alexandre le Grand et ses conquêtes (-336 à -323)'],
    },
    rome: {
      'non-acquis': ['Retenir -753 (fondation), -509 (République), -27 (Empire), 476 (fin Empire Occident)', 'Distinguer République (consuls, Sénat) et Empire (un seul chef)', 'Connaître Jules César et Auguste'],
      'fragile':    ['Le rôle des légions et la Pax Romana'],
    },
    religions: {
      'non-acquis': ['Définir le monothéisme (un seul Dieu)', 'Connaître Moïse et la Torah (judaïsme)', 'Retenir 313 (édit de Milan) et 380 (christianisme religion d\'État)'],
      'fragile':    ['Lien entre judaïsme et christianisme (Jésus est juif, ses disciples fondent une nouvelle religion)'],
    },
    asie: {
      'non-acquis': ['Connaître la route de la Soie (Chine → Europe) et son rôle commercial', 'Associer Confucius à la Chine Han et ses valeurs', 'Savoir que les chiffres arabes viennent d\'Inde (Gupta)'],
      'fragile':    ['Période Gupta (IVe-VIe s.) : hindouisme, bouddhisme, sciences'],
    },
    reperes: {
      'non-acquis': ['Maîtriser av. J.-C. / apr. J.-C. et le sens du comptage', 'Savoir calculer un siècle (Ve s. av. J.-C. = -500 à -401)', 'Mémoriser les 4 dates clés : -3300, -753, -27, 476'],
      'fragile':    ['Calculer une durée entre deux dates (avec ou sans changement d\'ère)'],
    },
  },
};
