// Source éditable — quiz histoire-3. Régénéré automatiquement dans index.html via build.sh.
window.ALL_QUIZZES['histoire-3'] = {
  SEARCH_SITES: 'site:lumni.fr OR site:ina.fr OR site:herodote.net OR site:francetveducation.fr',
  YT_SUFFIX: 'histoire 3eme brevet college',
  SUMMER_TOPIC: 'Histoire',
  SUBJECT: { id:'histoire-3', name:'Histoire', short:'Histoire', level:'Fin de 3ème (brevet)', mark:'📜', tagline:'Évaluation brevet' },
  DOMAINS: {
    gm1:          { id:'gm1',          name:'La Première Guerre mondiale (1914-1918)',         short:'PGM',        coef:3, color:'#78350f', icon:'⚔',  search:'premiere guerre mondiale 1914 1918 brevet' },
    entredeux:    { id:'entredeux',    name:'Entre-deux-guerres et totalitarismes',             short:'Entre-deux', coef:3, color:'#991b1b', icon:'☭',  search:'entre deux guerres totalitarisme staline hitler brevet' },
    gm2:          { id:'gm2',          name:'La Seconde Guerre mondiale (1939-1945)',           short:'SGM',        coef:4, color:'#1e3a8a', icon:'☠',  search:'seconde guerre mondiale 1939 1945 shoah brevet' },
    guerrefroide: { id:'guerrefroide', name:'La Guerre froide (1947-1991)',                    short:'Gfroide',    coef:3, color:'#4b5563', icon:'⚑⚐', search:'guerre froide bloc est ouest brevet' },
    decolonisation:{ id:'decolonisation',name:'Décolonisation et Tiers-Monde',                short:'Décolon.',   coef:2, color:'#a16207', icon:'🌍', search:'decolonisation indochine algerie brevet' },
    france45:     { id:'france45',     name:'La France depuis 1945 — IVe et Ve République',   short:'France 45',  coef:3, color:'#0f5e6b', icon:'🇫🇷', search:'france depuis 1945 IVe Ve republique brevet' },
    europe:       { id:'europe',       name:'La construction européenne',                      short:'Europe',     coef:2, color:'#1e40af', icon:'⭐', search:'construction europeenne traite rome maastricht brevet' },
    reperes:      { id:'reperes',      name:'Repères chronologiques',                         short:'Repères',    coef:2, color:'#475569', icon:'⧗',  search:'reperes chronologiques histoire 3eme brevet' },
  },
  RESOURCES: [
    { label:'Lumni — Histoire 3ème',         author:'France TV éducation',    url:'https://www.lumni.fr/college/troisieme/histoire-geographie' },
    { label:'INA — Archives audiovisuelles', author:'Institut National Audiovisuel', url:'https://www.ina.fr/enseignant' },
    { label:'Hérodote — dossiers thématiques',author:'herodote.net',          url:'https://www.herodote.net' },
    { label:'France TV Éducation — 3ème',    author:'francetveducation.fr',   url:'https://www.lumni.fr/parcours/preparer-le-brevet' },
  ],
  POOL: {
    gm1: [
      { key:'gm1-1', q:'Quel événement déclenche directement la Première Guerre mondiale le 28 juin 1914 ?', options:['Le krach boursier de New York','L\'assassinat de l\'archiduc François-Ferdinand à Sarajevo','L\'invasion de la Belgique par l\'Allemagne','La mobilisation générale de la France'], correct:1, hint:'L\'archiduc héritier d\'Autriche-Hongrie est assassiné par Gavrilo Princip, nationaliste serbe, à Sarajevo.' },
      { key:'gm1-2', q:'Quel terme désigne la guerre menée dans des tranchées creusées face à face, caractéristique du front Ouest ?', options:['La guerre de mouvement','La guerre sous-marine','La guerre de position (ou de tranchées)','La guerre éclair'], correct:2, hint:'Après l\'échec de la guerre de mouvement fin 1914, le front se stabilise en tranchées de la Mer du Nord à la Suisse.' },
      { key:'gm1-3', q:'La bataille de Verdun (1916) est surtout connue pour :', options:['La victoire rapide de l\'Allemagne','Ses pertes humaines colossales et le symbole de résistance française','L\'entrée en guerre des États-Unis','Le premier emploi du gaz moutarde'], correct:1, hint:'Verdun (fév-déc 1916) : environ 300 000 morts, symbole de l\'horreur des tranchées et du sacrifice français.' },
      { key:'gm1-4', q:'En quelle année les États-Unis entrent-ils en guerre aux côtés des Alliés ?', options:['1914','1915','1916','1917'], correct:3, hint:'En avril 1917, après la guerre sous-marine à outrance et le télégramme Zimmermann, les États-Unis rejoignent les Alliés.' },
      { key:'gm1-5', q:'L\'armistice mettant fin aux combats de la Première Guerre mondiale est signé le :', options:['11 novembre 1918','8 mai 1945','28 juin 1919','4 août 1914'], correct:0, hint:'Le 11 novembre 1918 à 11h, l\'armistice est signé dans un wagon à Rethondes (forêt de Compiègne).' },
      { key:'gm1-6', q:'Le traité de Versailles (1919) impose à l\'Allemagne :', options:['Des réparations, la perte de territoires et la responsabilité de la guerre (article 231)','Une alliance avec la France','L\'entrée dans la SDN immédiatement','Une réduction de son armée à 500 000 hommes'], correct:0, hint:'Article 231 = clause de culpabilité. L\'Allemagne perd l\'Alsace-Lorraine, ses colonies et doit verser des réparations.' },
      { key:'gm1-7', q:'La Société des Nations (SDN) est créée après la guerre pour :', options:['Préparer la prochaine guerre','Maintenir la paix et régler les conflits diplomatiquement','Organiser le commerce international','Rembourser les dettes de guerre'], correct:1, hint:'SDN créée en 1919 (siège à Genève) — ancêtre de l\'ONU, mais sans les États-Unis (Sénat refuse) et sans l\'URSS au départ.' },
      { key:'gm1-8', q:'En 1917, la révolution bolchevique conduit la Russie à :', options:['Renforcer son armée sur le front','Signer la paix avec l\'Allemagne (traité de Brest-Litovsk 1918)','Envahir la France','Rejoindre les Alliés plus activement'], correct:1, hint:'Lénine prend le pouvoir en octobre 1917 et signe une paix séparée avec l\'Allemagne en mars 1918 — libérant des troupes allemandes vers l\'Ouest.' },
    ],
    entredeux: [
      { key:'ed-1', q:'Le krach boursier qui déclenche la Grande Dépression se produit à Wall Street le :', options:['24 octobre 1929','11 novembre 1918','28 juin 1919','14 juillet 1936'], correct:0, hint:'Le « jeudi noir » du 24 octobre 1929 : effondrement des cours à la Bourse de New York, début de la crise mondiale.' },
      { key:'ed-2', q:'Benito Mussolini prend le pouvoir en Italie en 1922 grâce à :', options:['Des élections libres','La marche sur Rome et la nomination comme chef du gouvernement','Un coup d\'État militaire','L\'appui des communistes'], correct:1, hint:'Mussolini organise la marche sur Rome (oct. 1922) ; le roi Victor-Emmanuel III le nomme Président du Conseil.' },
      { key:'ed-3', q:'Adolf Hitler devient chancelier d\'Allemagne en :', options:['1929','1931','1933','1938'], correct:2, hint:'Le 30 janvier 1933, le président Hindenburg nomme Hitler chancelier (chef du gouvernement) de la République de Weimar.' },
      { key:'ed-4', q:'Les lois de Nuremberg (1935) en Allemagne nazie :', options:['Accordent le droit de vote aux femmes','Privent les Juifs de la nationalité allemande et interdisent les mariages mixtes','Créent la Gestapo','Instituent le service militaire obligatoire'], correct:1, hint:'Lois raciales de Nuremberg : les Juifs deviennent « sujets » (pas citoyens), marriages et relations sexuelles avec des Aryens interdits.' },
      { key:'ed-5', q:'En URSS, Staline met en place la collectivisation forcée, le Goulag et les grandes purges. Ces purges politiques débutent vers :', options:['1921','1929','1937','1941'], correct:2, hint:'Les grandes purges staliniennes (1936-1938) : procès de Moscou, exécution ou déportation de milliers de cadres du Parti et militaires.' },
      { key:'ed-6', q:'Le Front populaire arrive au pouvoir en France en 1936 sous la direction de :', options:['Charles de Gaulle','Léon Blum','Philippe Pétain','Georges Clemenceau'], correct:1, hint:'Léon Blum (socialiste SFIO) est Président du Conseil. Le Front populaire obtient les congés payés (2 semaines), la semaine de 40h et les conventions collectives.' },
      { key:'ed-7', q:'La Nuit de Cristal (9-10 novembre 1938) désigne :', options:['L\'invasion de la Pologne','Les pogroms antisémites organisés par les nazis en Allemagne et Autriche','La prise de la Bastille','Le début du Blitz sur Londres'], correct:1, hint:'Environ 7 500 commerces juifs détruits, synagogues brûlées, 91 Juifs tués et 30 000 déportés en camps de concentration.' },
    ],
    gm2: [
      { key:'gm2-1', q:'La Seconde Guerre mondiale commence le 1er septembre 1939 avec :', options:['L\'attaque japonaise sur Pearl Harbor','L\'invasion de la Pologne par l\'Allemagne nazie','L\'entrée en guerre de la France','La capitulation de la France'], correct:1, hint:'Le 1er septembre 1939, Hitler envahit la Pologne. La France et le Royaume-Uni déclarent la guerre à l\'Allemagne le 3 septembre.' },
      { key:'gm2-2', q:'Qui lance l\'Appel du 18 juin 1940 depuis Londres ?', options:['Philippe Pétain','Winston Churchill','Charles de Gaulle','Jean Moulin'], correct:2, hint:'Le général de Gaulle, depuis la BBC à Londres, appelle les Français à ne pas accepter la défaite et à continuer le combat.' },
      { key:'gm2-3', q:'L\'attaque japonaise sur Pearl Harbor (7 décembre 1941) entraîne :', options:['La capitulation du Japon','L\'entrée en guerre des États-Unis','La défaite de l\'Allemagne','La création de l\'ONU'], correct:1, hint:'L\'attaque surprise sur la base navale américaine à Hawaï provoque l\'entrée en guerre des États-Unis le 8 décembre 1941.' },
      { key:'gm2-4', q:'La bataille de Stalingrad (1942-1943) marque :', options:['La conquête de Moscou par l\'Allemagne','Le tournant de la guerre à l\'Est : première grande défaite allemande','La capitulation de la France','Le début de la Shoah'], correct:1, hint:'La reddition du maréchal Paulus (2 fév. 1943) : 300 000 soldats allemands perdus. Tournant décisif sur le front Est.' },
      { key:'gm2-5', q:'La Shoah est l\'extermination systématique des Juifs d\'Europe par les nazis. Le nombre de victimes est estimé à :', options:['Environ 600 000','Environ 2 millions','Environ 6 millions','Environ 15 millions'], correct:2, hint:'Environ 6 millions de Juifs assassinés, soit deux tiers des Juifs d\'Europe, dans les camps d\'extermination (Auschwitz, Treblinka…) et les fusillades.' },
      { key:'gm2-6', q:'La conférence de Wannsee (janvier 1942) décide de :', options:['La reddition de l\'Allemagne','La « solution finale » : l\'extermination industrielle de tous les Juifs d\'Europe','L\'opération Overlord','La création de la SDN'], correct:1, hint:'Wannsee (banlieue de Berlin) : Heydrich et 14 hauts responsables nazis coordonnent l\'extermination systématique.' },
      { key:'gm2-7', q:'Le débarquement allié en Normandie (D-Day) a lieu le :', options:['6 juin 1944','8 mai 1945','11 novembre 1943','1er septembre 1944'], correct:0, hint:'Opération Overlord : 6 juin 1944, les Alliés débarquent sur les plages normandes. Plus grand débarquement amphibie de l\'histoire.' },
      { key:'gm2-8', q:'La capitulation de l\'Allemagne nazie est signée le :', options:['6 août 1945','2 septembre 1945','8 mai 1945','11 novembre 1944'], correct:2, hint:'8 mai 1945 : capitulation sans condition de l\'Allemagne. Date commémorée chaque année comme jour de la Victoire en Europe.' },
      { key:'gm2-9', q:'La bombe atomique est lâchée sur Hiroshima le :', options:['2 septembre 1945','6 août 1945','8 mai 1945','7 décembre 1941'], correct:1, hint:'6 août 1945 : première bombe atomique sur Hiroshima, puis Nagasaki le 9 août → capitulation du Japon le 2 septembre 1945.' },
      { key:'gm2-10', q:'L\'Organisation des Nations Unies (ONU) est fondée en :', options:['1919','1939','1945','1947'], correct:2, hint:'Charte de San Francisco signée le 26 juin 1945 ; l\'ONU remplace la SDN avec 51 membres fondateurs.' },
    ],
    guerrefroide: [
      { key:'gf-1', q:'Le terme « rideau de fer » est utilisé par Churchill lors de son discours de :', options:['Yalta (1945)','Fulton (1946)','Berlin (1948)','Genève (1955)'], correct:1, hint:'Discours de Fulton (Missouri), 5 mars 1946 : « Un rideau de fer est descendu à travers le continent européen. »' },
      { key:'gf-2', q:'Le plan Marshall (1947) est un :', options:['Plan d\'armement américain','Programme d\'aide économique américaine à l\'Europe occidentale','Accord militaire de l\'OTAN','Plan de reconstruction soviétique'], correct:1, hint:'Plan Marshall = aide économique américaine (~13 milliards de $) pour reconstruire l\'Europe de l\'Ouest et endiguer le communisme.' },
      { key:'gf-3', q:'Le blocus de Berlin par l\'URSS (1948-1949) est contourné par :', options:['Un tunnel creusé par les Américains','Un pont aérien américain et britannique','Une percée militaire de l\'OTAN','Un accord de paix diplomatique'], correct:1, hint:'Les Alliés organisent un gigantesque pont aérien (277 000 vols en 11 mois) pour ravitailler Berlin-Ouest bloquée par les Soviétiques.' },
      { key:'gf-4', q:'Le mur de Berlin est construit le :', options:['13 août 1961','9 novembre 1989','4 juillet 1954','12 octobre 1962'], correct:0, hint:'Dans la nuit du 12 au 13 août 1961, l\'Allemagne de l\'Est bâtit le mur pour stopper l\'exode vers l\'Ouest (3 millions de fuyards depuis 1945).' },
      { key:'gf-5', q:'La crise des missiles de Cuba (octobre 1962) oppose :', options:['La France et l\'Angleterre','Les États-Unis (Kennedy) et l\'URSS (Khrouchtchev)','L\'OTAN et la Chine','Cuba et les États-Unis seuls'], correct:1, hint:'L\'URSS installe des missiles à Cuba à 90 km des côtes américaines. 13 jours de tension intense → retrait soviétique en échange d\'engagements américains.' },
      { key:'gf-6', q:'La chute du mur de Berlin a lieu le :', options:['13 août 1961','25 décembre 1991','9 novembre 1989','3 octobre 1990'], correct:2, hint:'Le 9 novembre 1989, le régime est-allemand ouvre ses frontières ; des milliers de Berlinois déchirent le mur. Symbole de la fin de la Guerre froide.' },
      { key:'gf-7', q:'Mikhaïl Gorbatchev engage en URSS des réformes appelées :', options:['New Deal et Fair Deal','Glasnost (transparence) et Perestroïka (restructuration)','Plan quinquennal et collectivisation','Détente et coexistence pacifique'], correct:1, hint:'Gorbatchev (1985-1991) : glasnost = liberté d\'expression, perestroïka = réforme économique. Ces réformes accélèrent la désintégration de l\'URSS.' },
      { key:'gf-8', q:'L\'URSS est officiellement dissoute le :', options:['9 novembre 1989','3 octobre 1990','25 décembre 1991','1er janvier 1992'], correct:2, hint:'Le 25 décembre 1991, Gorbatchev démissionne et le drapeau soviétique est abaissé du Kremlin. Fin officielle de l\'URSS.' },
    ],
    decolonisation: [
      { key:'dec-1', q:'L\'Inde accède à l\'indépendance en :', options:['1945','1947','1954','1962'], correct:1, hint:'15 août 1947 : indépendance de l\'Inde (Jawaharlal Nehru) et du Pakistan. Gandhi a mené la résistance non-violente contre la colonisation britannique.' },
      { key:'dec-2', q:'La bataille de Dien Bien Phu (1954) met fin à la guerre d\'Indochine par :', options:['La victoire française','La défaite française face au Viêt-minh de Hô Chi Minh','Un accord américain','Une médiation de l\'ONU'], correct:1, hint:'7 mai 1954 : la garnison française capitule. Les accords de Genève (juillet 1954) reconnaissent l\'indépendance du Vietnam, Laos et Cambodge.' },
      { key:'dec-3', q:'La guerre d\'Algérie commence en :', options:['1945','1950','1954','1958'], correct:2, hint:'1er novembre 1954 : insurrection déclenchée par le FLN (Front de Libération Nationale). Guerre qui durera jusqu\'en 1962.' },
      { key:'dec-4', q:'Les accords d\'Évian (18 mars 1962) mettent fin à :', options:['La guerre d\'Indochine','La guerre d\'Algérie','La crise de Suez','La guerre de Corée'], correct:1, hint:'Accords d\'Évian signés entre le gouvernement français (De Gaulle) et le FLN : cessez-le-feu et indépendance de l\'Algérie reconnue.' },
      { key:'dec-5', q:'La conférence de Bandung (1955) réunit les pays d\'Asie et d\'Afrique pour :', options:['Rejoindre l\'OTAN','Affirmer leur indépendance et créer le mouvement des non-alignés','S\'allier avec l\'URSS','Intégrer le marché commun européen'], correct:1, hint:'29 pays d\'Asie et d\'Afrique se réunissent à Bandung (Indonésie) : refus de s\'aligner sur les deux blocs, affirmation de la solidarité du Tiers-Monde.' },
      { key:'dec-6', q:'L\'année 1960 est appelée « l\'année de l\'Afrique » car :', options:['L\'Afrique du Sud gagne la Coupe du monde','17 pays africains accèdent à l\'indépendance','La guerre d\'Algérie commence','L\'OUA est fondée'], correct:1, hint:'En 1960, 17 colonies africaines (dont les colonies françaises d\'Afrique subsaharienne) deviennent indépendantes.' },
    ],
    france45: [
      { key:'fr-1', q:'La IVe République française est instaurée en :', options:['1944','1946','1951','1958'], correct:1, hint:'La Constitution de la IVe République est adoptée par référendum le 13 octobre 1946. Elle est marquée par une forte instabilité gouvernementale.' },
      { key:'fr-2', q:'De Gaulle revient au pouvoir en 1958 et fonde la Ve République dont la Constitution est adoptée le :', options:['8 mai 1945','13 mai 1958','4 octobre 1958','22 novembre 1963'], correct:2, hint:'4 octobre 1958 : la Constitution de la Ve République est promulguée. Elle renforce l\'exécutif (président) au détriment du Parlement.' },
      { key:'fr-3', q:'Les événements de mai 1968 en France se caractérisent par :', options:['Un coup d\'État militaire','Une grève générale, des manifestations étudiantes et ouvrières remettant en cause la société','L\'arrivée au pouvoir de Mitterrand','Une guerre civile'], correct:1, hint:'Mai 68 : barricades du Quartier Latin, grève générale (10 millions de grévistes), accords de Grenelle. Crise sociale et culturelle majeure.' },
      { key:'fr-4', q:'La loi Veil (1975) légalise en France :', options:['Le droit de vote des femmes','L\'interruption volontaire de grossesse (IVG)','L\'abolition de la peine de mort','Le mariage homosexuel'], correct:1, hint:'Simone Veil, ministre de la Santé de Giscard d\'Estaing, fait adopter la loi légalisant l\'avortement le 17 janvier 1975 malgré l\'opposition massive.' },
      { key:'fr-5', q:'L\'abolition de la peine de mort en France est obtenue en 1981 sous la présidence de :', options:['Georges Pompidou','Valéry Giscard d\'Estaing','François Mitterrand','Jacques Chirac'], correct:2, hint:'Robert Badinter, garde des Sceaux de Mitterrand, fait voter l\'abolition le 9 octobre 1981 — un an après l\'élection de Mitterrand.' },
      { key:'fr-6', q:'Valéry Giscard d\'Estaing abaisse la majorité électorale à 18 ans en :', options:['1958','1968','1974','1981'], correct:2, hint:'Juillet 1974 : la majorité (civile et électorale) est abaissée de 21 à 18 ans, donnant le droit de vote à environ 3 millions de jeunes Français.' },
      { key:'fr-7', q:'La première « cohabitation » de la Ve République (1986-1988) voit coexister :', options:['De Gaulle président et Pompidou Premier ministre','Mitterrand président et Chirac Premier ministre','Chirac président et Jospin Premier ministre','Giscard président et Mauroy Premier ministre'], correct:1, hint:'1986-1988 : Mitterrand (socialiste) est président, Chirac (RPR, droite) est Premier ministre — première cohabitation de la Ve République.' },
    ],
    europe: [
      { key:'eur-1', q:'La CECA (Communauté Européenne du Charbon et de l\'Acier), premier pas vers l\'Europe unie, est créée en :', options:['1945','1948','1951','1957'], correct:2, hint:'Traité de Paris, 18 avril 1951 : France, Allemagne, Italie, Belgique, Pays-Bas, Luxembourg — inspiré par Robert Schuman et Jean Monnet.' },
      { key:'eur-2', q:'Le traité de Rome du 25 mars 1957 crée :', options:['L\'OTAN','La CEE (Communauté Économique Européenne) et l\'Euratom','Le Conseil de l\'Europe','L\'euro'], correct:1, hint:'Traité de Rome : 6 pays fondateurs créent la CEE (marché commun, libre circulation) et l\'Euratom (énergie nucléaire civile).' },
      { key:'eur-3', q:'Le traité de Maastricht (1992) crée :', options:['La CECA','L\'Union européenne et prépare la monnaie unique','L\'espace Schengen','Le Conseil de l\'Europe'], correct:1, hint:'Signé le 7 février 1992, il crée l\'Union européenne, établit la citoyenneté européenne et prépare l\'euro (Union économique et monétaire).' },
      { key:'eur-4', q:'L\'euro entre en circulation comme monnaie fiduciaire (billets et pièces) le :', options:['1er janvier 1999','1er janvier 2002','1er mai 2004','9 novembre 1989'], correct:1, hint:'1er janvier 2002 : les billets et pièces en euros remplacent les monnaies nationales dans 12 pays. Le taux de change avait été fixé le 1er janvier 1999.' },
      { key:'eur-5', q:'Le Brexit désigne :', options:['L\'entrée de la Bulgarie dans l\'UE','La sortie du Royaume-Uni de l\'Union européenne (effective en 2020)','Le référendum irlandais de 2008','L\'élargissement de l\'UE à l\'Est'], correct:1, hint:'Référendum britannique du 23 juin 2016 : 51,9% pour quitter l\'UE. Sortie effective le 31 janvier 2020.' },
      { key:'eur-6', q:'La Politique Agricole Commune (PAC), pilier de la construction européenne, garantit :', options:['La défense commune','Des prix agricoles stables et des revenus aux agriculteurs européens','La libre circulation des personnes','La politique étrangère commune'], correct:1, hint:'La PAC (depuis 1962) est la première grande politique commune : soutien des prix, subventions aux agriculteurs, auto-suffisance alimentaire.' },
    ],
    reperes: [
      { key:'chr-1', q:'Replacez dans l\'ordre chronologique : mur de Berlin construit / D-Day / armistice SGM / chute du mur', options:['D-Day → armistice → mur construit → chute du mur','Armistice → D-Day → mur construit → chute du mur','Mur construit → D-Day → armistice → chute du mur','Chute du mur → D-Day → armistice → mur construit'], correct:0, hint:'D-Day = 6 juin 1944 → armistice = 8 mai 1945 → mur construit = 13 août 1961 → chute du mur = 9 nov. 1989.' },
      { key:'chr-2', q:'Lequel de ces événements appartient au XXe siècle mais PAS au programme de 3ème ?', options:['La Révolution française (1789)','La Première Guerre mondiale (1914-1918)','La chute du mur de Berlin (1989)','La construction européenne (1957)'], correct:0, hint:'La Révolution française (1789) est du XVIIIe siècle et relève du programme de 4ème. Les trois autres sont au programme de 3ème.' },
      { key:'chr-3', q:'Le terme « génocide » désigne :', options:['Une guerre entre deux États','L\'extermination systématique d\'un groupe national, ethnique ou religieux','Une épidémie mondiale','Un régime de terreur politique'], correct:1, hint:'Génocide (Raphael Lemkin, 1944) : destruction intentionnelle et systématique d\'un groupe. La Shoah et le génocide des Arméniens sont les exemples étudiés en 3ème.' },
      { key:'chr-4', q:'Un régime totalitaire se caractérise par :', options:['Des élections libres et pluralistes','Le contrôle total de l\'État sur la société, un parti unique, une idéologie officielle et la terreur','La séparation des pouvoirs','La liberté de la presse et des partis'], correct:1, hint:'Totalitarisme (nazisme, stalinisme, fascisme) : parti unique, chef tout-puissant, propagande, police politique, encadrement de la population.' },
    ],
  },
  PICK: {
    gm1: 4, entredeux: 4, gm2: 6, guerrefroide: 4, decolonisation: 3, france45: 4, europe: 3, reperes: 2,
  },
  PLANS: {
    gm1: {
      'non-acquis': ['Révise la chronologie : 1914 (attentat) → 1917 (EU + révolution russe) → 1918 (armistice) → 1919 (traité Versailles)', 'Mémorise les caractéristiques de la guerre des tranchées (Verdun, gaz, no man\'s land, poilus)', 'Retiens les termes clés : SDN, Triple Entente, Triple Alliance, armistice, gueules cassées'],
      'fragile': ['Distingue armistice (11 nov 1918) et traité de paix (Versailles, 28 juin 1919)']
    },
    entredeux: {
      'non-acquis': ['Mémorise les dates clés : 1929 (krach), 1922 (Mussolini), 1933 (Hitler chancelier), 1936 (Front populaire)', 'Comprends les caractéristiques du nazisme et du stalinisme (régimes totalitaires)', 'Retiens les signes avant-coureurs de la WWII : lois Nuremberg, Nuit de Cristal, réarmement'],
      'fragile': ['Distingue fascisme (Italie), nazisme (Allemagne) et stalinisme (URSS) — 3 totalitarismes différents']
    },
    gm2: {
      'non-acquis': ['Chronologie : 1939 (Pologne) → 1940 (France, appel 18 juin) → 1941 (Pearl Harbor) → 1942-43 (Stalingrad) → 1942 (Wannsee) → 1944 (D-Day) → 1945 (capitulations)', 'La Shoah : définition, Wannsee, 6 millions de victimes, camps d\'extermination (Auschwitz)', 'Distingue Résistance (De Gaulle, Londres) et Collaboration (Pétain, Vichy)'],
      'fragile': ['Savoir que 8 mai = capitulation Allemagne ET 2 septembre = capitulation Japon (fin officielle de la guerre)']
    },
    guerrefroide: {
      'non-acquis': ['Mémorise le cadre : deux blocs (USA/OTAN vs URSS/Pacte de Varsovie) de 1947 à 1991', 'Dates clés : 1947 (plan Marshall), 1961 (mur Berlin construit), 1962 (Cuba), 1989 (chute mur), 1991 (dissolution URSS)', 'Comprends la notion de dissuasion nucléaire et de coexistence pacifique'],
      'fragile': ['Distingue la Guerre froide (pas de conflit direct USA-URSS) des conflits par procuration (Corée, Vietnam)']
    },
    decolonisation: {
      'non-acquis': ['Dates à retenir : 1947 (Inde), 1954 (Indochine + début guerre Algérie), 1955 (Bandung), 1960 (année de l\'Afrique), 1962 (accords Évian)', 'Comprends les deux voies : négociée (Inde) vs armée (Algérie, Indochine)', 'Le mouvement des non-alignés refuse les deux blocs — Tiers-Monde'],
      'fragile': ['Sais qui est Gandhi (résistance non-violente, Inde) et Hô Chi Minh (Viêt-minh, Indochine)']
    },
    france45: {
      'non-acquis': ['Mémorise les deux républiques : IVe (1946, instable) → Ve (1958, De Gaulle, Constitution renforcée)', 'Dates clés : 1958 (Ve République), 1968 (mai 68), 1974 (majorité à 18 ans), 1975 (loi Veil), 1981 (abolition peine de mort)', 'Comprends la cohabitation : président et Premier ministre de partis opposés'],
      'fragile': ['Distingue IVe République (instable, régime parlementaire) et Ve République (présidentielle forte)']
    },
    europe: {
      'non-acquis': ['Chronologie : 1951 (CECA) → 1957 (traité de Rome, CEE) → 1992 (Maastricht, UE) → 2002 (euro en circulation)', 'Les 6 fondateurs de la CEE : France, Allemagne, Italie, Belgique, Pays-Bas, Luxembourg', 'Comprends les 4 libertés du marché commun : libre circulation des marchandises, services, capitaux, personnes'],
      'fragile': ['Distingue Conseil de l\'Europe (1949, droits de l\'homme) et Communauté/Union européenne (intégration économique)']
    },
    reperes: {
      'non-acquis': ['Mémorise la grille chronologique du programme : 1914, 1918, 1929, 1933, 1939, 1945, 1947, 1958, 1962, 1968, 1989, 1991, 2002', 'Maîtrise les définitions : totalitarisme, dictature, génocide, crimes contre l\'humanité, résistance, collaboration', 'Sais à quel siècle appartient chaque événement (XXe = 1901-2000)'],
      'fragile': ['Entraîne-toi à replacer les événements sur une frise chronologique sans aide']
    },
  },
};
