// Source éditable — quiz maths-4. Régénéré automatiquement dans index.html via build.sh.
window.ALL_QUIZZES['maths-4'] = {
  SEARCH_SITES: 'site:maths-et-tiques.fr OR site:fr.khanacademy.org OR site:lumni.fr',
  YT_SUFFIX: 'Yvan Monka',
  SUMMER_TOPIC: 'maths',
  SUBJECT: {
  id: 'maths',
  name: 'Mathématiques',
  short: 'Maths',
  level: 'Fin de 4ème',
  mark: '∑',
  tagline: 'Évaluation diagnostique',
    id: 'maths-4',
  },
  DOMAINS: {
  relatifs:   { id:'relatifs',   name:'Nombres relatifs',                  short:'Relatifs',    coef:2, color:'#0f5e6b', icon:'±',   search:'nombres relatifs 4eme' },
  fractions:  { id:'fractions',  name:'Fractions',                         short:'Fractions',   coef:3, color:'#0d7a6f', icon:'⅔',   search:'fractions 4eme' },
  puissances: { id:'puissances', name:'Puissances & écriture scientifique',short:'Puissances',  coef:2, color:'#6d28d9', icon:'xⁿ',  search:'puissances ecriture scientifique 4eme' },
  litteral:   { id:'litteral',   name:'Calcul littéral & équations',       short:'Littéral',    coef:4, color:'#b8323d', icon:'2x',  search:'calcul litteral equations 4eme' },
  pythagore:  { id:'pythagore',  name:'Théorème de Pythagore',             short:'Pythagore',   coef:4, color:'#a01b34', icon:'△',   search:'theoreme de pythagore 4eme' },
  thales:     { id:'thales',     name:'Théorème de Thalès',                short:'Thalès',      coef:3, color:'#7a2ca8', icon:'//',  search:'theoreme de thales 4eme' },
  trigo:      { id:'trigo',      name:'Trigonométrie (cosinus)',           short:'Trigo',       coef:2, color:'#1d4ed8', icon:'cos', search:'trigonometrie cosinus 4eme' },
  transfo:    { id:'transfo',    name:'Transformations (symétries, translations)', short:'Transfo', coef:2, color:'#1e7a8a', icon:'↔', search:'symetrie translation 4eme' },
  grandeurs:  { id:'grandeurs',  name:'Grandeurs & volumes',               short:'Grandeurs',   coef:2, color:'#166a39', icon:'V',   search:'grandeurs volumes 4eme' },
  proportion: { id:'proportion', name:'Proportionnalité & %',              short:'Proportion',  coef:2, color:'#b97a0e', icon:'%',   search:'proportionnalite pourcentage 4eme' },
  probas:     { id:'probas',     name:'Statistiques & probabilités',       short:'Probas',      coef:2, color:'#c4307a', icon:'p',   search:'statistiques probabilites 4eme' },
  },
  RESOURCES: [
  { label:'Maths et Tiques',  author:'Yvan Monka (gratuit)',   url:'https://www.maths-et-tiques.fr/index.php/cours-en-ligne/cours-quatrieme' },
  { label:'Khan Academy',     author:'Cours + exos gratuits',  url:'https://fr.khanacademy.org/math/cycle-4-4eme-v2' },
  { label:'Lumni',            author:'France TV éducation',    url:'https://www.lumni.fr/college/quatrieme/mathematiques' },
  { label:'Sésamath',         author:'Manuel en ligne gratuit',url:'https://manuel.sesamath.net/' },
  ],
  POOL: {
  relatifs: [
    { key:'rel-1', q:<>Calcule : <M>(−7) + (−5) =</M></>,
      options:['−12','−2','+12','+2'], correct:0,
      hint:'Deux négatifs qu\'on additionne → on additionne les valeurs et on garde le signe −.' },
    { key:'rel-2', q:<>Calcule : <M>(−8) × (−3) =</M></>,
      options:['−24','+24','−11','+11'], correct:1,
      hint:'Règle des signes : − × − = +' },
    { key:'rel-3', q:<>Calcule : <M>15 − (−4) + (−6) =</M></>,
      options:['5','13','17','25'], correct:1,
      hint:'15 − (−4) = 15 + 4 = 19, puis 19 + (−6) = 13' },
    { key:'rel-4', q:<>Calcule : <M>(−36) ÷ (+4) =</M></>,
      options:['+9','−9','−32','+32'], correct:1,
      hint:'− ÷ + = − , et 36 ÷ 4 = 9, donc −9' },
    { key:'rel-5', q:<>Quel est l\'opposé du nombre <M>−12</M> ?</>,
      options:['−12','+12','0','1/12'], correct:1,
      hint:'L\'opposé d\'un nombre n a pour somme 0 avec lui : opposé de −12 est +12.' },
    { key:'rel-6', q:<>Calcule : <M>−3 × (5 − 8) =</M></>,
      options:['+9','−9','+39','−39'], correct:0,
      hint:'5 − 8 = −3, puis −3 × (−3) = +9' },
  ],

  fractions: [
    { key:'fra-1', q:<>Calcule : <F n="2" d="3"/> + <F n="1" d="4"/> =</>,
      options:[<F n="3" d="7"/>, <F n="11" d="12"/>, <F n="2" d="12"/>, <F n="8" d="12"/>], correct:1,
      hint:'Dénominateur commun 12 : 8/12 + 3/12 = 11/12' },
    { key:'fra-2', q:<>Calcule (en simplifiant) : <F n="3" d="5"/> × <F n="10" d="9"/> =</>,
      options:[<F n="2" d="3"/>, <F n="13" d="14"/>, <F n="3" d="2"/>, <F n="6" d="5"/>], correct:0,
      hint:'(3×10)/(5×9) = 30/45 = 2/3 après simplification par 15' },
    { key:'fra-3', q:<>Calcule : <F n="5" d="6"/> ÷ <F n="2" d="3"/> =</>,
      options:[<F n="10" d="18"/>, <F n="5" d="9"/>, <F n="5" d="4"/>, <F n="4" d="5"/>], correct:2,
      hint:'Diviser = multiplier par l\'inverse : 5/6 × 3/2 = 15/12 = 5/4' },
    { key:'fra-4', q:<>Simplifie au maximum : <F n="18" d="24"/> =</>,
      options:[<F n="4" d="5"/>, <F n="2" d="3"/>, <F n="3" d="4"/>, <F n="9" d="8"/>], correct:2,
      hint:'PGCD(18,24) = 6 → 18/24 = 3/4 (irréductible)' },
    { key:'fra-5', q:<>Calcule : <F n="7" d="10"/> − <F n="1" d="2"/> =</>,
      options:[<F n="6" d="8"/>, <F n="1" d="5"/>, <F n="2" d="5"/>, <F n="6" d="10"/>], correct:1,
      hint:'1/2 = 5/10, donc 7/10 − 5/10 = 2/10 = 1/5. Attention à simplifier !' },
    { key:'fra-6', q:<>Que vaut <F n="3" d="4"/> de 60 ?</>,
      options:['15','20','45','80'], correct:2,
      hint:'3/4 × 60 = 180/4 = 45' },
  ],

  puissances: [
    { key:'pui-1', q:<>Calcule : <M>2<sup>5</sup> =</M></>,
      options:['10','25','32','64'], correct:2,
      hint:'2×2×2×2×2 = 32' },
    { key:'pui-2', q:<>Simplifie : <M>3<sup>4</sup> × 3<sup>2</sup> =</M></>,
      options:[<>3<sup>6</sup></>, <>3<sup>8</sup></>, <>9<sup>6</sup></>, <>6<sup>6</sup></>], correct:0,
      hint:'On additionne les exposants : 3⁴ × 3² = 3⁶' },
    { key:'pui-3', q:'Écris 47 500 en notation scientifique :',
      options:[<>4,75 × 10<sup>3</sup></>, <>47,5 × 10<sup>3</sup></>, <>4,75 × 10<sup>4</sup></>, <>475 × 10<sup>2</sup></>], correct:2,
      hint:'Un seul chiffre non nul avant la virgule : 4,75 × 10⁴' },
    { key:'pui-4', q:<>Calcule : <M>10<sup>−3</sup> =</M></>,
      options:['−1000','−0,001','0,001','0,01'], correct:2,
      hint:'10⁻³ = 1/10³ = 1/1000 = 0,001' },
    { key:'pui-5', q:<>Simplifie : <M>(2<sup>3</sup>)<sup>2</sup> =</M></>,
      options:[<>2<sup>5</sup></>, <>2<sup>6</sup></>, <>2<sup>9</sup></>, '32'], correct:1,
      hint:'Puissance de puissance : on multiplie les exposants → 2^(3×2) = 2⁶' },
    { key:'pui-6', q:'Écris 0,00062 en notation scientifique :',
      options:[<>6,2 × 10<sup>−4</sup></>, <>62 × 10<sup>−5</sup></>, <>6,2 × 10<sup>4</sup></>, <>0,62 × 10<sup>−3</sup></>], correct:0,
      hint:'Virgule déplacée de 4 rangs vers la droite → exposant −4' },
  ],

  litteral: [
    { key:'lit-1', q:<>Développe : <M>5(2x − 3) =</M></>,
      options:['10x − 3','10x − 15','7x − 8','2x − 15'], correct:1,
      hint:'Distributivité : 5×2x + 5×(−3) = 10x − 15' },
    { key:'lit-2', q:<>Réduis : <M>4x + 7 − 2x + 5 =</M></>,
      options:['2x + 12','6x + 12','2x + 2','14x'], correct:0,
      hint:'(4x − 2x) + (7 + 5) = 2x + 12' },
    { key:'lit-3', q:<>Résous : <M>3x + 7 = 22</M></>,
      options:['x = 5','x = 7','x = 15','x = 29'], correct:0,
      hint:'3x = 15, donc x = 5' },
    { key:'lit-4', q:<>Résous : <M>5x − 4 = 2x + 11</M></>,
      options:['x = 3','x = 5','x = 7','x = −5'], correct:1,
      hint:'5x − 2x = 11 + 4 → 3x = 15 → x = 5' },
    { key:'lit-5', q:<>Si <M>x = −2</M>, que vaut <M>A = 3x² + 4x − 1</M> ?</>,
      options:['3','−21','19','−5'], correct:0,
      hint:'3×4 + 4×(−2) − 1 = 12 − 8 − 1 = 3' },
    { key:'lit-6', q:<>Factorise : <M>6x + 9 =</M></>,
      options:['3(2x + 3)','3(2x + 6)','6(x + 9)','2(3x + 9)'], correct:0,
      hint:'Facteur commun 3 : 6x = 3×2x et 9 = 3×3 → 3(2x + 3)' },
    { key:'lit-7', q:<>Développe : <M>(x + 3)(x − 2) =</M></>,
      options:['x² − 6','x² + x − 6','x² + 5x − 6','x² − x − 6'], correct:1,
      hint:'Double distributivité : x² − 2x + 3x − 6 = x² + x − 6' },
    { key:'lit-8', q:<>Résous : <M>2(x − 1) = x + 5</M></>,
      options:['x = 7','x = 3','x = 6','x = 4'], correct:0,
      hint:'2x − 2 = x + 5 → x = 7' },
  ],

  pythagore: [
    { key:'pyt-1', q:'ABC est rectangle en A avec AB = 3 cm et AC = 4 cm. Combien mesure BC ?',
      options:['5 cm','7 cm','25 cm','√7 cm'], correct:0,
      hint:'BC² = 3² + 4² = 25 → BC = 5 cm' },
    { key:'pyt-2', q:'Un triangle a pour côtés 6, 8 et 10. Est-il rectangle ?',
      options:['Oui, car 6² + 8² = 10²','Non, car 6 + 8 ≠ 10','Oui, car 6 × 8 = 48','On ne peut pas savoir'], correct:0,
      hint:'Réciproque : 36 + 64 = 100 = 10² → rectangle' },
    { key:'pyt-3', q:'Dans un triangle rectangle, l\'hypoténuse mesure 13 cm et un côté 5 cm. L\'autre côté mesure :',
      options:['8 cm','12 cm','18 cm','√194 cm'], correct:1,
      hint:'c² = 13² − 5² = 144 → c = 12' },
    { key:'pyt-4', q:'Dans un triangle rectangle, l\'hypoténuse est :',
      options:['Le côté le plus court','Le côté opposé à l\'angle droit','N\'importe quel côté','Le côté vertical'], correct:1,
      hint:'Hypoténuse = côté opposé à l\'angle droit, le plus long.' },
    { key:'pyt-5', q:'Un triangle a pour côtés 7, 24 et 25. Est-il rectangle ?',
      options:['Oui','Non','Isocèle seulement','Équilatéral'], correct:0,
      hint:'49 + 576 = 625 = 25² ✓' },
  ],

  thales: [
    { key:'tha-1', q:<>Dans la configuration de Thalès, si <M>(MN) // (BC)</M> avec AM = 2, AB = 6 et AN = 3, alors AC vaut :</>,
      options:['4','7','9','1'], correct:2,
      hint:'AM/AB = AN/AC → 2/6 = 3/AC → AC = 9' },
    { key:'tha-2', q:'Le théorème de Thalès permet de :',
      options:['Calculer une aire','Calculer des longueurs (droites parallèles)','Calculer un angle','Démontrer qu\'un triangle est isocèle'], correct:1,
      hint:'Thalès = longueurs dans une configuration avec droites parallèles' },
    { key:'tha-3', q:<>Dans un triangle ABC, M ∈ [AB] et N ∈ [AC] avec <M>(MN) // (BC)</M>. Si AM = 4, MB = 2 et MN = 6, alors BC vaut :</>,
      options:['8','9','12','4'], correct:1,
      hint:'AM/AB = MN/BC → 4/6 = 6/BC → BC = 9' },
    { key:'tha-4', q:'Pour appliquer Thalès il faut impérativement :',
      options:['Un triangle rectangle','Deux droites parallèles et sécantes à deux autres droites','Un cercle','Deux angles égaux'], correct:1,
      hint:'La configuration repose sur deux parallèles coupées par deux sécantes concourantes.' },
  ],

  trigo: [
    { key:'tri-1', q:'Dans un triangle rectangle, le cosinus d\'un angle aigu est :',
      options:[<F n="opposé" d="hypoténuse"/>, <F n="adjacent" d="hypoténuse"/>, <F n="opposé" d="adjacent"/>, <F n="hypoténuse" d="adjacent"/>], correct:1,
      hint:'CAH : Cosinus = Adjacent / Hypoténuse' },
    { key:'tri-2', q:<>Dans un triangle ABC rectangle en A, AB = 4 et BC = 5. Que vaut cos(<span style={{textDecoration:'overline'}}>ABC</span>) ?</>,
      options:['0,6','0,8','1,25','0,75'], correct:1,
      hint:'adjacent/hyp = 4/5 = 0,8' },
    { key:'tri-3', q:<>Si cos(α) = 0,5 dans un triangle rectangle, l\'angle α mesure :</>,
      options:['30°','45°','60°','90°'], correct:2,
      hint:'cos(60°) = 0,5' },
    { key:'tri-4', q:'Le cosinus d\'un angle aigu est toujours :',
      options:['Supérieur à 1','Entre 0 et 1','Négatif','Égal à 1'], correct:1,
      hint:'Rapport de deux longueurs où l\'hypoténuse est la plus grande → 0 < cos < 1 pour un angle aigu.' },
  ],

  grandeurs: [
    { key:'gra-1', q:'Un cycliste parcourt 45 km en 1 h 30 min. Sa vitesse moyenne est :',
      options:['20 km/h','30 km/h','45 km/h','67,5 km/h'], correct:1,
      hint:'v = d/t = 45 / 1,5 = 30 km/h (1h30 = 1,5h, pas 1,3h)' },
    { key:'gra-2', q:'Le volume d\'une pyramide de base 12 cm² et de hauteur 5 cm est :',
      options:['60 cm³','20 cm³','17 cm³','180 cm³'], correct:1,
      hint:'V = (B × h)/3 = 60/3 = 20 cm³' },
    { key:'gra-3', q:<>Convertis : <M>2,5 L =</M></>,
      options:['25 cm³','250 cm³','2 500 cm³','25 000 cm³'], correct:2,
      hint:'1 L = 1000 cm³ → 2,5 L = 2500 cm³' },
    { key:'gra-4', q:'Volume d\'un cube d\'arête 4 cm :',
      options:['12 cm³','16 cm³','48 cm³','64 cm³'], correct:3,
      hint:'V = a³ = 4×4×4 = 64' },
    { key:'gra-5', q:'Un piéton marche à 5 km/h pendant 45 min. Distance parcourue ?',
      options:['2,25 km','3,75 km','4 km','5 km'], correct:1,
      hint:'45 min = 0,75 h → 5 × 0,75 = 3,75 km' },
    { key:'gra-6', q:<>Convertis : <M>3 m³ =</M></>,
      options:['30 dm³','300 dm³','3 000 dm³','30 000 dm³'], correct:2,
      hint:'1 m³ = 1000 dm³ → 3 m³ = 3000 dm³' },
  ],

  proportion: [
    { key:'pro-1', q:'Un article à 80 € est soldé à −25 %. Son nouveau prix est :',
      options:['55 €','60 €','65 €','75 €'], correct:1,
      hint:'80 × 0,75 = 60 €' },
    { key:'pro-2', q:'5 stylos coûtent 7,50 €. Combien coûtent 12 stylos ?',
      options:['14,50 €','18 €','15 €','12,50 €'], correct:1,
      hint:'1 stylo = 1,50 € → 12 × 1,50 = 18 €' },
    { key:'pro-3', q:'Un prix augmente de 20 %. Pour revenir au prix initial, il faut diminuer de :',
      options:['20 %','16,67 %','25 %','10 %'], correct:1,
      hint:'Multiplier par 1,2 puis par 1/1,2 = 0,833… soit −16,67 %' },
    { key:'pro-4', q:'Sur une carte à l\'échelle 1/50 000, 4 cm représentent :',
      options:['200 m','2 km','20 km','500 m'], correct:1,
      hint:'4 × 50 000 = 200 000 cm = 2 km' },
  ],

  transfo: [
    { key:'tra-1', q:'Par symétrie centrale de centre O, un segment a pour image :',
      options:['Un segment de même longueur','Un segment plus court','Un point','Un cercle'], correct:0,
      hint:'Une symétrie centrale conserve les longueurs : l\'image d\'un segment est un segment de même longueur.' },
    { key:'tra-2', q:'Par translation, une figure est :',
      options:['Retournée','Déplacée sans déformation','Réduite','Tournée'], correct:1,
      hint:'Une translation glisse la figure sans la déformer, ni la tourner, ni la retourner.' },
    { key:'tra-3', q:'Par symétrie centrale, les angles sont :',
      options:['Doublés','Conservés','Inversés','Égaux à 180°'], correct:1,
      hint:'Les symétries (centrale et axiale) conservent les angles et les longueurs.' },
    { key:'tra-4', q:'Le centre de symétrie d\'un parallélogramme est :',
      options:['Un sommet','Le milieu d\'un côté','Le point d\'intersection des diagonales','Il n\'y en a pas'], correct:2,
      hint:'Les diagonales d\'un parallélogramme se coupent en leur milieu, qui est son centre de symétrie.' },
  ],

  probas: [
    { key:'pb-1', q:'Moyenne de la série : 8 ; 12 ; 10 ; 14 ; 6',
      options:['10','8','50','12'], correct:0,
      hint:'(8+12+10+14+6)/5 = 50/5 = 10' },
    { key:'pb-2', q:'On lance un dé équilibré à 6 faces. Probabilité d\'obtenir un nombre pair ?',
      options:[<F n="1" d="6"/>, <F n="1" d="3"/>, <F n="1" d="2"/>, <F n="2" d="3"/>], correct:2,
      hint:'3 cas favorables (2,4,6) sur 6 → 1/2' },
    { key:'pb-3', q:'Urne : 3 boules rouges, 5 bleues. Probabilité de tirer une rouge ?',
      options:[<F n="3" d="5"/>, <F n="3" d="8"/>, <F n="5" d="8"/>, <F n="1" d="3"/>], correct:1,
      hint:'3 rouges sur 8 → 3/8' },
    { key:'pb-4', q:'Médiane de la série : 2 ; 4 ; 5 ; 7 ; 9 ; 12 ; 15',
      options:['5','7','8','9'], correct:1,
      hint:'7 valeurs triées → médiane = 4ᵉ valeur = 7' },
    { key:'pb-5', q:'Étendue de la série : 4 ; 9 ; 2 ; 11 ; 6 ; 7',
      options:['5','7','9','11'], correct:2,
      hint:'Max − Min = 11 − 2 = 9' },
    { key:'pb-6', q:'On tire une carte dans un jeu de 32. Probabilité d\'un cœur ?',
      options:[<F n="1" d="4"/>, <F n="1" d="8"/>, <F n="1" d="32"/>, <F n="4" d="32"/>], correct:0,
      hint:'8 cœurs sur 32 cartes → 8/32 = 1/4' },
  ],
  },
  PICK: {
  relatifs: 3, fractions: 3, puissances: 3, litteral: 5, pythagore: 3,
  thales: 2, trigo: 2, transfo: 2, grandeurs: 3, proportion: 2, probas: 2,
  },
  PLANS: {
    relatifs: {
      'non-acquis': ['Revoir la règle des signes (+ et −) pour addition et multiplication', 'Refaire 15 calculs par jour pendant 1 semaine', 'S\'entraîner avec des jeux de cartes (signe +/−)'],
      'fragile':    ['Consolider par 10 exercices variés (parenthèses imbriquées)', 'Attention particulière aux soustractions de nombres négatifs']
    },
    fractions: {
      'non-acquis': ['Reprendre la notion de dénominateur commun (multiples)', 'Mémoriser : diviser = multiplier par l\'inverse', '5 exercices par jour sur 2 semaines'],
      'fragile':    ['Travailler la simplification avant de calculer', 'Exercices mixtes + et × avec 3 fractions']
    },
    puissances: {
      'non-acquis': ['Revoir la définition : aⁿ = a × a × … × a (n fois)', 'Apprendre par cœur les règles : aⁿ × aᵐ = aⁿ⁺ᵐ', 'Écriture scientifique : s\'entraîner sur 20 exemples'],
      'fragile':    ['Focus sur les puissances négatives (10⁻ⁿ) et l\'écriture scientifique']
    },
    litteral: {
      'non-acquis': ['PRIORITÉ ABSOLUE : revoir la distributivité k(a+b) = ka + kb', 'Progression : réduction → développement → équations', 'Au moins 30 min/jour pendant 3 semaines', 'Méthode : isoler x étape par étape'],
      'fragile':    ['Équations avec x des deux côtés', 'Vérifier chaque solution en remplaçant x']
    },
    pythagore: {
      'non-acquis': ['Identifier l\'hypoténuse (face à l\'angle droit)', 'Mémoriser la formule et sa réciproque', 'Triplets 3-4-5 et 5-12-13 par cœur', '3 exercices par jour sur 2 semaines'],
      'fragile':    ['Bien distinguer théorème direct et réciproque', 'Problèmes concrets : échelle, diagonale, etc.']
    },
    thales: {
      'non-acquis': ['Revoir la configuration : parallèles + sécantes', 'Écrire les 3 rapports égaux', 'Attention à l\'ordre des points (AM/AB, pas AM/AN)'],
      'fragile':    ['Travailler la configuration "papillon" en anticipation de la 3ème']
    },
    trigo: {
      'non-acquis': ['Mémoriser CAH : Cos = Adjacent / Hypoténuse', 'Identifier côté opposé/adjacent selon l\'angle', 'Utiliser la calculatrice : touches cos et cos⁻¹'],
      'fragile':    ['Distinguer "calculer un côté" vs "calculer un angle"']
    },
    grandeurs: {
      'non-acquis': ['V cube, V pavé, V cylindre, V pyramide, V cône par cœur', 'Tableau de conversions : L / dm³ / cm³ / mL', 'Formule v = d/t et ses dérivées'],
      'fragile':    ['Attention aux unités de temps (1h30 = 1,5h ≠ 1,3h)']
    },
    proportion: {
      'non-acquis': ['Revoir le produit en croix', 'Pourcentages : augmentation/diminution', 'Vitesse, échelle, situations concrètes'],
      'fragile':    ['Remises successives et problèmes à plusieurs étapes']
    },
    transfo: {
      'non-acquis': ['Revoir les 3 transformations : symétrie centrale, symétrie axiale, translation', 'Retenir : toutes conservent les longueurs et les angles', 'Identifier le centre / l\'axe / le vecteur avant de construire'],
      'fragile':    ['Construire l\'image par symétrie centrale (milieu) puis par translation', 'Reconnaître une figure qui a un centre ou un axe de symétrie']
    },
    probas: {
      'non-acquis': ['Moyenne simple', 'Probabilité = cas favorables / cas possibles', 'Événements simples : dé, pièce, urne'],
      'fragile':    ['Arbres de probabilités (préparation 3ème)']
    },
  },
};
