// Source éditable — quiz physique-4. Régénéré automatiquement dans index.html via build.sh.
window.ALL_QUIZZES['physique-4'] = {
  SEARCH_SITES: 'site:fr.khanacademy.org OR site:lumni.fr OR site:maxicours.com',
  YT_SUFFIX: 'college physique',
  SUMMER_TOPIC: 'physique-chimie',
  SUBJECT: {
  id: 'physique',
  name: 'Physique-Chimie',
  short: 'Physique',
  level: 'Fin de 4ème',
  mark: '⚛',
  tagline: 'Évaluation diagnostique',
    id: 'physique-4',
  },
  DOMAINS: {
  electricite: { id:'electricite', name:'Électricité & circuits',            short:'Électricité', coef:4, color:'#b45309', icon:'⚡', search:'electricite circuit intensite tension loi ohm 4eme' },
  loiOhm:      { id:'loiOhm',      name:'Loi d\'Ohm (U = R × I)',             short:'Loi d\'Ohm',  coef:3, color:'#ca8a04', icon:'Ω', search:'loi d ohm 4eme' },
  optique:     { id:'optique',     name:'Optique & lumière',                  short:'Optique',     coef:2, color:'#ca9a04', icon:'☀', search:'optique lumiere sources 4eme' },
  couleurs:    { id:'couleurs',    name:'Lumières colorées (RVB / CMJ)',      short:'Couleurs',    coef:2, color:'#db2777', icon:'◐', search:'synthese additive soustractive couleurs 4eme' },
  matiere:     { id:'matiere',     name:'Matière & masse volumique',          short:'Matière',     coef:3, color:'#0f5e6b', icon:'ρ', search:'masse volumique etats matiere 4eme' },
  atomes:      { id:'atomes',      name:'Atomes, molécules & ions',           short:'Atomes',      coef:3, color:'#7c3aed', icon:'A', search:'atomes molecules ions 4eme' },
  chimie:      { id:'chimie',      name:'Transformations chimiques',          short:'Chimie',      coef:4, color:'#a01b34', icon:'⇌', search:'transformation chimique reactifs produits 4eme' },
  ph:          { id:'ph',          name:'Acidité, basicité & pH',             short:'pH',          coef:2, color:'#059669', icon:'pH',search:'ph acide base 4eme' },
  mouvement:   { id:'mouvement',   name:'Mouvement & vitesse',                short:'Mouvement',   coef:2, color:'#1d4ed8', icon:'→', search:'mouvement vitesse 4eme' },
  poids:       { id:'poids',       name:'Poids & masse (P = m × g)',          short:'Poids',       coef:3, color:'#166a39', icon:'g', search:'poids masse 4eme' },
  },
  RESOURCES: [
  { label:'Physique-Chimie Khan Academy', author:'Cours + exercices gratuits', url:'https://fr.khanacademy.org/science/college-physique-chimie-4eme-v2' },
  { label:'Lumni — Physique-Chimie 4ème', author:'France TV éducation',         url:'https://www.lumni.fr/college/quatrieme/physique-chimie' },
  { label:'PhET Simulations',             author:'Université Colorado (gratuit)', url:'https://phet.colorado.edu/fr/simulations/filter?subjects=physics,chemistry&type=html' },
  { label:'Physique-Chimie au collège',   author:'Paul Olivier (YouTube)',       url:'https://www.youtube.com/@PaulOlivier' },
  ],
  POOL: {
  electricite: [
    { key:'ele-1', q:'Dans un circuit en série, l\'intensité du courant électrique :',
      options:['Est la même partout','Se divise aux nœuds','Augmente avec la résistance','Disparaît dans la lampe'], correct:0,
      hint:'En série, le courant est identique en tout point du circuit (un seul chemin).' },
    { key:'ele-2', q:'Dans un circuit en dérivation (parallèle), les tensions aux bornes de chaque branche :',
      options:['Se divisent','S\'additionnent','Sont égales','Sont nulles'], correct:2,
      hint:'En dérivation, toutes les branches ont la même tension (loi d\'unicité des tensions).' },
    { key:'ele-3', q:'L\'unité de l\'intensité électrique est :',
      options:['Le volt (V)','L\'ampère (A)','L\'ohm (Ω)','Le watt (W)'], correct:1,
      hint:'Intensité → ampère (A). La tension est en volts (V).' },
    { key:'ele-4', q:'L\'appareil qui mesure l\'intensité du courant s\'appelle :',
      options:['Un voltmètre','Un ampèremètre','Un ohmmètre','Un thermomètre'], correct:1,
      hint:'Ampèremètre : branché en SÉRIE. Voltmètre : branché en DÉRIVATION.' },
    { key:'ele-5', q:'Un voltmètre se branche :',
      options:['En série','En dérivation (aux bornes du dipôle)','Dans la pile','À la masse'], correct:1,
      hint:'Le voltmètre mesure la tension aux bornes : branché en parallèle sur le dipôle.' },
    { key:'ele-6', q:'Dans un circuit série, si on ajoute une lampe identique, les lampes brillent :',
      options:['Plus fort','Moins fort','Pareil','S\'éteignent toutes'], correct:1,
      hint:'Plus de récepteurs en série → résistance totale plus grande → courant plus faible → éclat moindre.' },
    { key:'ele-7', q:'Un court-circuit, c\'est :',
      options:['Un circuit trop long','Un fil direct entre les bornes d\'un dipôle','Une pile déchargée','Un circuit ouvert'], correct:1,
      hint:'Un fil (résistance ≈ 0) court-circuite le dipôle : tout le courant y passe, c\'est dangereux.' },
  ],

  loiOhm: [
    { key:'ohm-1', q:<>La loi d\'Ohm s\'écrit :</>,
      options:[<><M>U = R + I</M></>, <><M>U = R × I</M></>, <><M>U = R / I</M></>, <><M>R = U × I</M></>], correct:1,
      hint:'Loi d\'Ohm : U (volts) = R (ohms) × I (ampères).' },
    { key:'ohm-2', q:<>Une résistance R = 20 Ω est traversée par I = 0,5 A. La tension vaut :</>,
      options:['10 V','40 V','0,025 V','100 V'], correct:0,
      hint:'U = R × I = 20 × 0,5 = 10 V' },
    { key:'ohm-3', q:<>Pour U = 12 V et R = 4 Ω, l\'intensité vaut :</>,
      options:['48 A','3 A','0,33 A','8 A'], correct:1,
      hint:'I = U / R = 12 / 4 = 3 A' },
    { key:'ohm-4', q:'L\'unité de la résistance électrique est :',
      options:['L\'ampère','Le volt','L\'ohm','Le hertz'], correct:2,
      hint:'Résistance → ohm (Ω). Symbole du matériau : conducteur peu conducteur.' },
    { key:'ohm-5', q:<>Si la tension aux bornes d\'une résistance double, l\'intensité :</>,
      options:['Double','Est divisée par 2','Reste égale','Disparaît'], correct:0,
      hint:'U et I sont proportionnels à R fixé (loi d\'Ohm).' },
  ],

  optique: [
    { key:'opt-1', q:'La lumière se propage :',
      options:['En ligne courbe','En ligne droite dans un milieu transparent homogène','Uniquement dans le vide','En zigzag'], correct:1,
      hint:'Propagation rectiligne dans un milieu transparent et homogène (air, eau, verre).' },
    { key:'opt-2', q:'La vitesse de la lumière dans le vide est environ :',
      options:['300 km/s','300 000 km/h','300 000 km/s','3 000 m/s'], correct:2,
      hint:'c ≈ 300 000 km/s = 3 × 10⁸ m/s' },
    { key:'opt-3', q:'Le Soleil est une source :',
      options:['Secondaire','Primaire','Diffuse uniquement','Ponctuelle froide'], correct:1,
      hint:'Une source primaire produit sa propre lumière (Soleil, lampe). Secondaire = diffuse (Lune, objets).' },
    { key:'opt-4', q:'Une année-lumière est une unité :',
      options:['De temps','De vitesse','De distance','De masse'], correct:2,
      hint:'Distance parcourue par la lumière en 1 an (≈ 9,5 × 10¹² km).' },
    { key:'opt-5', q:'On ne peut voir un objet que si :',
      options:['Il est coloré','De la lumière venue de cet objet entre dans notre œil','Il est proche','Il fait jour'], correct:1,
      hint:'Vision = lumière émise ou diffusée par l\'objet qui parvient à l\'œil.' },
    { key:'opt-6', q:'Un rayon lumineux est représenté par :',
      options:['Un cercle','Un point','Une flèche sur une droite','Une onde sinusoïdale'], correct:2,
      hint:'Flèche indiquant le sens de propagation sur une droite.' },
  ],

  couleurs: [
    { key:'col-1', q:'Les trois lumières primaires de la synthèse additive sont :',
      options:['Rouge, vert, bleu','Jaune, cyan, magenta','Rouge, jaune, bleu','Noir, blanc, gris'], correct:0,
      hint:'RVB (additive, écrans). CMJ (soustractive, imprimantes).' },
    { key:'col-2', q:'Rouge + Vert (en lumières) donne :',
      options:['Jaune','Blanc','Orange','Marron'], correct:0,
      hint:'Synthèse additive : R + V = Jaune ; V + B = Cyan ; R + B = Magenta ; R + V + B = Blanc.' },
    { key:'col-3', q:'Rouge + Vert + Bleu (en lumières) donne :',
      options:['Noir','Blanc','Gris','Rien, incompatibles'], correct:1,
      hint:'Les trois primaires additives à pleine intensité donnent du blanc.' },
    { key:'col-4', q:'Un objet rouge éclairé en lumière bleue apparaît :',
      options:['Rouge','Bleu','Noir','Blanc'], correct:2,
      hint:'L\'objet ne diffuse que le rouge ; en lumière bleue il n\'a rien à diffuser → il paraît noir.' },
    { key:'col-5', q:'Les couleurs primaires utilisées en imprimerie (synthèse soustractive) sont :',
      options:['RVB','CMJ (cyan, magenta, jaune)','Rouge, blanc, noir','Toutes les couleurs'], correct:1,
      hint:'CMJN en imprimerie (cyan, magenta, jaune, noir).' },
  ],

  matiere: [
    { key:'mat-1', q:<>La masse volumique se calcule par :</>,
      options:[<><M>ρ = m × V</M></>, <><M>ρ = m / V</M></>, <><M>ρ = V / m</M></>, <><M>ρ = m + V</M></>], correct:1,
      hint:'ρ (rho) = masse / volume. Unité : kg/m³ ou g/cm³.' },
    { key:'mat-2', q:'La masse volumique de l\'eau (liquide) est environ :',
      options:['1 g/cm³','10 g/cm³','0,1 g/cm³','100 g/cm³'], correct:0,
      hint:'Eau pure : 1 g/cm³ = 1 kg/L = 1000 kg/m³.' },
    { key:'mat-3', q:'Un objet flotte sur l\'eau si sa masse volumique est :',
      options:['Plus grande que celle de l\'eau','Plus petite que celle de l\'eau','Égale à zéro','Peu importe'], correct:1,
      hint:'Densité < 1 g/cm³ → flotte. Densité > 1 → coule.' },
    { key:'mat-4', q:'Les trois états physiques de la matière sont :',
      options:['Chaud, froid, tiède','Solide, liquide, gazeux','Dur, mou, fluide','Lourd, léger, flottant'], correct:1,
      hint:'Solide (forme propre), liquide (épouse le récipient), gaz (occupe tout le volume).' },
    { key:'mat-5', q:'Lors d\'un changement d\'état, la masse :',
      options:['Diminue','Reste constante','Augmente','S\'évapore'], correct:1,
      hint:'Conservation de la masse : la quantité de matière ne change pas. Le volume, si.' },
    { key:'mat-6', q:'Passage de l\'état liquide à l\'état solide :',
      options:['Fusion','Solidification','Vaporisation','Sublimation'], correct:1,
      hint:'Solidification = liquide → solide (l\'inverse de la fusion).' },
  ],

  atomes: [
    { key:'ato-1', q:'Un atome est constitué de :',
      options:['Un noyau et des électrons','Deux noyaux','Uniquement d\'électrons','De molécules'], correct:0,
      hint:'Noyau (protons + neutrons) + électrons qui tournent autour.' },
    { key:'ato-2', q:'Le noyau d\'un atome contient :',
      options:['Des électrons et des protons','Des protons et des neutrons','Uniquement des neutrons','Rien'], correct:1,
      hint:'Noyau = protons (charge +) + neutrons (neutres).' },
    { key:'ato-3', q:'Une molécule est :',
      options:['Un atome isolé','Un groupe d\'atomes liés','Un noyau','Un ion'], correct:1,
      hint:'Molécule = plusieurs atomes liés (H₂O, CO₂…).' },
    { key:'ato-4', q:'La formule de l\'eau est :',
      options:['H₂O','CO₂','O₂','H₂'], correct:0,
      hint:'H₂O : 2 hydrogènes + 1 oxygène.' },
    { key:'ato-5', q:'Un ion est un atome qui a :',
      options:['Perdu ou gagné des électrons','Perdu ses neutrons','Changé de noyau','Fondu'], correct:0,
      hint:'Ion positif = a perdu un ou plusieurs électrons. Ion négatif = en a gagné.' },
    { key:'ato-6', q:'L\'ion Na⁺ correspond à :',
      options:['Un atome de sodium ayant perdu 1 électron','Un atome de sodium ayant gagné 1 électron','Un atome d\'azote','Une molécule'], correct:0,
      hint:'Le + indique qu\'il manque un électron ; Na⁺ = sodium cation.' },
  ],

  chimie: [
    { key:'chi-1', q:'Dans une transformation chimique :',
      options:['De nouvelles substances apparaissent','La masse des produits est plus grande','Les atomes disparaissent','Rien ne se passe'], correct:0,
      hint:'Les réactifs sont consommés et donnent des produits. Atomes conservés, masse conservée.' },
    { key:'chi-2', q:'Lors d\'une combustion, il faut trois éléments :',
      options:['Air, eau, feu','Combustible, comburant (O₂), énergie d\'activation','CO₂, H₂O, chaleur','Métal, acide, sel'], correct:1,
      hint:'Triangle du feu : combustible + comburant + énergie.' },
    { key:'chi-3', q:'Le test du dioxyde de carbone CO₂ utilise :',
      options:['Un test à la flamme','L\'eau de chaux (se trouble)','Du sulfate de cuivre','Un aimant'], correct:1,
      hint:'CO₂ + eau de chaux limpide → eau de chaux qui se trouble (devient blanche laiteuse).' },
    { key:'chi-4', q:'Le test du dioxygène O₂ se fait avec :',
      options:['L\'eau de chaux','Une bûchette incandescente qui se rallume','Du sulfate de cuivre anhydre','Un papier pH'], correct:1,
      hint:'Le dioxygène ravive la flamme d\'une bûchette incandescente.' },
    { key:'chi-5', q:'Les espèces avant la réaction s\'appellent :',
      options:['Produits','Réactifs','Solvants','Catalyseurs'], correct:1,
      hint:'Réactifs → Produits (sens de la flèche d\'équation chimique).' },
    { key:'chi-6', q:'La combustion du carbone donne :',
      options:['De l\'eau','Du dioxyde de carbone (CO₂)','Du dihydrogène','De l\'azote'], correct:1,
      hint:'C + O₂ → CO₂' },
  ],

  ph: [
    { key:'ph-1', q:'Une solution est acide si son pH est :',
      options:['= 7','> 7','< 7','= 0'], correct:2,
      hint:'pH < 7 : acide ; pH = 7 : neutre ; pH > 7 : basique.' },
    { key:'ph-2', q:'L\'eau pure a un pH de :',
      options:['0','7','14','1'], correct:1,
      hint:'Eau pure = neutre = pH 7.' },
    { key:'ph-3', q:'Plus une solution acide est diluée, son pH :',
      options:['Se rapproche de 0','Se rapproche de 7','Se rapproche de 14','Ne change pas'], correct:1,
      hint:'Dilution d\'un acide → pH se rapproche de 7 (neutre).' },
    { key:'ph-4', q:'Exemples de solutions basiques :',
      options:['Jus de citron','Vinaigre','Eau savonneuse, soude','Eau gazeuse'], correct:2,
      hint:'Acides : citron, vinaigre, cola. Bases : savon, soude, ammoniaque.' },
    { key:'ph-5', q:'Le papier pH donne une mesure :',
      options:['Du poids','De l\'acidité','De la température','Du volume'], correct:1,
      hint:'Le papier pH change de couleur selon l\'acidité/basicité de la solution.' },
  ],

  mouvement: [
    { key:'mou-1', q:<>La formule de la vitesse moyenne est :</>,
      options:[<><M>v = d × t</M></>, <><M>v = d / t</M></>, <><M>v = t / d</M></>, <><M>v = d + t</M></>], correct:1,
      hint:'v = distance / temps. Unités : m/s ou km/h.' },
    { key:'mou-2', q:'Une voiture roule à 90 km/h pendant 2 h. Distance parcourue :',
      options:['45 km','92 km','180 km','88 km'], correct:2,
      hint:'d = v × t = 90 × 2 = 180 km' },
    { key:'mou-3', q:'Un mouvement est dit uniforme quand :',
      options:['La vitesse augmente','La vitesse diminue','La vitesse est constante','Il n\'y a pas de vitesse'], correct:2,
      hint:'Uniforme = vitesse constante. Accéléré = v augmente. Décéléré (ou ralenti) = v diminue.' },
    { key:'mou-4', q:'Un coureur fait 100 m en 10 s. Sa vitesse moyenne est :',
      options:['1 m/s','10 m/s','100 m/s','36 m/s'], correct:1,
      hint:'100 / 10 = 10 m/s (soit 36 km/h).' },
    { key:'mou-5', q:'Pour étudier un mouvement, il faut choisir :',
      options:['Une couleur','Un référentiel','Un kilo','Un ami'], correct:1,
      hint:'Un référentiel (objet de référence) : sans lui, impossible de dire si un corps bouge.' },
  ],

  poids: [
    { key:'poi-1', q:<>La relation entre le poids et la masse est :</>,
      options:[<><M>P = m + g</M></>, <><M>P = m × g</M></>, <><M>P = m / g</M></>, <><M>m = P × g</M></>], correct:1,
      hint:'P (newtons) = m (kg) × g (N/kg). Sur Terre : g ≈ 9,8 N/kg (on utilise souvent 10).' },
    { key:'poi-2', q:'L\'unité du poids est :',
      options:['Le kilogramme','Le newton','Le gramme','Le pascal'], correct:1,
      hint:'Poids → newton (N). Masse → kilogramme (kg). Attention à ne pas confondre !' },
    { key:'poi-3', q:'Sur Terre, la valeur de la pesanteur g vaut environ :',
      options:['1 N/kg','10 N/kg','100 N/kg','0 N/kg'], correct:1,
      hint:'g ≈ 9,8 N/kg sur Terre, arrondi à 10 N/kg en 4ème.' },
    { key:'poi-4', q:'Un objet de masse 2 kg a un poids sur Terre d\'environ :',
      options:['2 N','5 N','20 N','200 N'], correct:2,
      hint:'P = m × g = 2 × 10 = 20 N' },
    { key:'poi-5', q:'Si on emmène un objet de la Terre vers la Lune, sa masse :',
      options:['Diminue','Augmente','Reste la même','Disparaît'], correct:2,
      hint:'La masse est invariable (quantité de matière). Le poids, lui, dépend de g et change.' },
    { key:'poi-6', q:'Un astronaute qui pèse 700 N sur Terre pèse sur la Lune environ :',
      options:['700 N','350 N','120 N','0 N'], correct:2,
      hint:'g_lune ≈ 1,6 N/kg (≈ 1/6 de Terre). Poids lunaire ≈ 1/6 du poids terrestre.' },
  ],

  },
  PICK: {
  electricite: 4, loiOhm: 3, optique: 3, couleurs: 3, matiere: 3,
  atomes: 3, chimie: 4, ph: 2, mouvement: 3, poids: 2,
  },
  PLANS: {
    electricite: {
      'non-acquis': ['Distinguer clairement CIRCUIT SÉRIE (un seul chemin) et DÉRIVATION (plusieurs branches)', 'Apprendre par cœur : ampèremètre en SÉRIE, voltmètre en DÉRIVATION', 'Revoir les unités : ampère (A), volt (V), ohm (Ω)', 'S\'entraîner à repérer un court-circuit sur un schéma'],
      'fragile':    ['Exercices avec 2-3 lampes en configurations mixtes', 'Savoir prévoir l\'éclat d\'une lampe quand on ajoute/enlève un dipôle']
    },
    loiOhm: {
      'non-acquis': ['Retenir la formule : U = R × I (et ses 2 dérivées : I = U/R et R = U/I)', 'S\'entraîner sur 10 calculs simples par jour', 'Attention aux unités : si R en ohms et I en A, alors U en volts'],
      'fragile':    ['Problèmes avec changement de R ou de tension d\'alimentation', 'Tracer la caractéristique U = f(I) d\'un conducteur ohmique']
    },
    optique: {
      'non-acquis': ['Propagation rectiligne dans un milieu transparent et homogène', 'Vitesse de la lumière : c = 300 000 km/s', 'Source primaire (Soleil, lampe) vs secondaire (objets éclairés)'],
      'fragile':    ['Représenter un rayon lumineux par une demi-droite avec flèche', 'Savoir expliquer pourquoi on voit un objet']
    },
    couleurs: {
      'non-acquis': ['Synthèse ADDITIVE (lumières, écrans) : RVB → R+V+B = blanc', 'Synthèse SOUSTRACTIVE (peinture, impression) : CMJ', 'Un objet rouge = diffuse le rouge et absorbe le reste'],
      'fragile':    ['Prévoir la couleur d\'un objet selon la lumière qui l\'éclaire']
    },
    matiere: {
      'non-acquis': ['Formule ρ = m / V, unité kg/m³ ou g/cm³', 'Eau = 1 g/cm³. Si ρ_objet < 1 → flotte ; > 1 → coule', 'Les 3 états et leurs 6 changements d\'état (fusion/solidification, vaporisation/liquéfaction, sublimation/condensation)'],
      'fragile':    ['Calculs de masse volumique avec conversions d\'unités', 'Conservation de la masse lors d\'un changement d\'état']
    },
    atomes: {
      'non-acquis': ['Atome = noyau (protons + neutrons) + électrons', 'Molécule = groupe d\'atomes liés (ex. H₂O, CO₂, O₂)', 'Ion = atome qui a perdu ou gagné des électrons'],
      'fragile':    ['Écrire les formules des molécules usuelles', 'Différencier atomes, molécules et ions sur des exemples']
    },
    chimie: {
      'non-acquis': ['PRIORITÉ : RÉACTIFS → PRODUITS, conservation des atomes et de la masse', 'Tests à connaître par cœur : CO₂ (eau de chaux), O₂ (bûchette), H₂ (détonation), eau (sulfate de cuivre anhydre)', 'Combustion : combustible + O₂ (comburant) + énergie'],
      'fragile':    ['Équilibrer une équation-bilan simple', 'Calcul de masse dans une réaction chimique']
    },
    ph: {
      'non-acquis': ['Échelle : pH 0-14. Acide < 7, neutre = 7, basique > 7', 'Papier pH ou indicateur coloré pour mesurer', 'Exemples : citron (acide), eau pure (neutre), eau savonneuse (basique)'],
      'fragile':    ['Dilution d\'un acide ou d\'une base : pH se rapproche de 7']
    },
    mouvement: {
      'non-acquis': ['Formule v = d / t, unités m/s et km/h', 'Conversions : 1 km/h = 1000 m / 3600 s ≈ 0,28 m/s (et ×3,6 pour l\'inverse)', 'Notion de référentiel indispensable'],
      'fragile':    ['Mouvement uniforme / accéléré / décéléré', 'Exercices avec changement de vitesse']
    },
    poids: {
      'non-acquis': ['PRIORITÉ : masse (kg, invariable) ≠ poids (newtons, dépend de g)', 'Formule P = m × g ; sur Terre g ≈ 10 N/kg', 'Le poids change selon l\'astre ; la masse, non'],
      'fragile':    ['Calculs P ↔ m avec différentes valeurs de g (Terre, Lune, Mars)', 'Représenter le poids par un vecteur vertical vers le bas']
    },
  },
};
