// Source éditable — quiz svt-5. Régénéré automatiquement dans index.html via build.sh.
window.ALL_QUIZZES['svt-5'] = {
  SEARCH_SITES: 'site:fr.khanacademy.org OR site:lumni.fr OR site:planet-vie.ens.fr',
  YT_SUFFIX: 'svt 5eme college',
  SUMMER_TOPIC: 'SVT',
  SUBJECT: { id:'svt-5', name:'Sciences de la Vie et de la Terre', short:'SVT', level:'Fin de 5ème', mark:'🌿', tagline:'Évaluation diagnostique' },
  DOMAINS: {
    respiration: { id:'respiration', name:'Respiration humaine',           short:'Respiration',coef:3, color:'#b91c1c', icon:'O₂',search:'respiration humaine poumons 5eme' },
    circulation: { id:'circulation', name:'Circulation sanguine',          short:'Circulation',coef:3, color:'#a01b34', icon:'♥', search:'circulation sanguine coeur 5eme' },
    digestion:   { id:'digestion',   name:'Digestion & nutrition',         short:'Digestion',  coef:3, color:'#c2410c', icon:'☰', search:'digestion nutrition 5eme' },
    effortMuscle:{ id:'effortMuscle',name:'Activité physique & muscles',   short:'Effort',     coef:2, color:'#ca8a04', icon:'↯', search:'effort physique muscles 5eme' },
    microOrg:    { id:'microOrg',    name:'Microorganismes',               short:'Microbes',   coef:2, color:'#7c3aed', icon:'μ', search:'microorganismes bacteries 5eme' },
    plantesNutri:{ id:'plantesNutri',name:'Nutrition des végétaux',        short:'Plantes',    coef:2, color:'#15803d', icon:'✿', search:'nutrition vegetale photosynthese 5eme' },
    erosion:     { id:'erosion',     name:'Géologie : érosion & paysages', short:'Érosion',    coef:3, color:'#7c2d12', icon:'⚒', search:'erosion paysages roches 5eme' },
    climat:      { id:'climat',      name:'Météo & climat',                short:'Climat',     coef:2, color:'#0891b2', icon:'☁', search:'meteo climat 5eme' },
  },
  RESOURCES: [
    { label:'Lumni — SVT 5ème',      author:'France TV éducation',    url:'https://www.lumni.fr/college/cinquieme/svt' },
    { label:'Khan Academy — Biologie',author:'Cours + exos',           url:'https://fr.khanacademy.org/science/ms-biology' },
    { label:'Planet-Vie',            author:'ENS — ressources SVT',   url:'https://planet-vie.ens.fr/' },
    { label:'SVT à l\'école',        author:'YouTube',                url:'https://www.youtube.com/results?search_query=svt+5eme+cours' },
  ],
  POOL: {
    respiration: [
      { key:'res5-1', q:'Les poumons contiennent :', options:['Des alvéoles (où se font les échanges gazeux)','Uniquement du sang','Des os','De l\'eau'], correct:0, hint:'Alvéoles = petites cavités très nombreuses, très vascularisées, site des échanges O₂/CO₂.' },
      { key:'res5-2', q:'Lors de l\'inspiration :', options:['Les poumons se contractent eux-mêmes','Le diaphragme descend et l\'air entre dans les poumons','On expulse le CO₂','Rien ne se passe'], correct:1, hint:'Diaphragme s\'abaisse + côtes s\'écartent → volume augmente → air aspiré.' },
      { key:'res5-3', q:'L\'air expiré contient :', options:['Plus d\'O₂ que l\'air inspiré','Plus de CO₂ et moins d\'O₂ que l\'air inspiré','Aucun gaz','Seulement de la vapeur d\'eau'], correct:1, hint:'Les cellules consomment O₂ et produisent CO₂ → air expiré plus riche en CO₂.' },
      { key:'res5-4', q:'Lors de l\'expiration, le diaphragme :', options:['Descend encore plus','Remonte et les poumons se vident','Reste parfaitement immobile','Se contracte davantage'], correct:1, hint:'Expiration : diaphragme remonte + côtes s\'abaissent → volume diminue → air chassé.' },
      { key:'res5-5', q:'La proportion de dioxygène dans l\'air ambiant est d\'environ :', options:['10 %','21 %','50 %','100 %'], correct:1, hint:'Composition de l\'air : 78 % N₂, 21 % O₂, ~0,04 % CO₂.' },
      { key:'res5-6', q:'Les échanges gazeux au niveau des alvéoles permettent :', options:['De filtrer les microbes','D\'absorber O₂ dans le sang et d\'éliminer CO₂','De digérer les aliments','De produire du glucose'], correct:1, hint:'O₂ passe des alvéoles dans le sang ; CO₂ passe du sang dans les alvéoles.' },
      { key:'res5-7', q:'La trachée relie :', options:['L\'estomac aux poumons','Le larynx (gorge) aux bronches des poumons','Le nez à l\'estomac','Le cœur aux poumons'], correct:1, hint:'Voies aériennes : nez/bouche → larynx → trachée → bronches → bronchioles → alvéoles.' },
      { key:'res5-8', q:'La fréquence respiratoire au repos est d\'environ :', options:['2-3 cycles/min','15-18 cycles/min','50 cycles/min','100 cycles/min'], correct:1, hint:'Au repos : environ 15-20 inspirations/expirations par minute. Elle augmente à l\'effort.' },
      { key:'res5-9', q:'Le tabac :', options:['Est bon pour les poumons','Détruit les alvéoles et provoque cancers et BPCO','N\'a aucun effet prouvé','Augmente la capacité pulmonaire'], correct:1, hint:'Tabac : cause de cancers du poumon, bronchites chroniques, maladies cardiovasculaires.' },
      { key:'res5-10', q:'En cas d\'asthme, les bronches :', options:['Se dilatent fortement','Se contractent, gênant le passage de l\'air','Se remplissent de sang','Disparaissent progressivement'], correct:1, hint:'Asthme : bronchospasme (contraction des muscles des bronches) → difficultés respiratoires.' },
      { key:'res5-11', q:'La capacité pulmonaire totale d\'un adulte est d\'environ :', options:['0,5 L','5 L','50 L','500 L'], correct:1, hint:'Capacité pulmonaire totale ≈ 5-6 L. Au repos, on n\'utilise qu\'environ 0,5 L (volume courant). À l\'effort, on peut aller jusqu\'à ~4 L (CV).' },
      { key:'res5-12', q:'Pourquoi la fréquence respiratoire augmente-t-elle à l\'effort ?', options:['Pour éliminer la sueur','Pour fournir plus de dioxygène aux muscles et évacuer davantage de CO₂','Pour ralentir le cœur','Pour stocker de l\'azote'], correct:1, hint:'Effort → muscles consomment plus d\'O₂ et produisent plus de CO₂ → système nerveux accélère la respiration.' },
    ],
    circulation: [
      { key:'cir5-1', q:'Le cœur est :', options:['Un muscle creux qui pompe le sang','Un os','Une glande digestive','Un organe sans fonction connue'], correct:0, hint:'Cœur = muscle creux qui pompe le sang dans tout le corps.' },
      { key:'cir5-2', q:'Les artères transportent :', options:['Le sang du cœur vers les organes','Le sang des organes vers le cœur','Uniquement de l\'air','Du glucose pur'], correct:0, hint:'Artères : du cœur vers les tissus. Veines : vers le cœur.' },
      { key:'cir5-3', q:'Le cœur comporte :', options:['1 ventricule','2 ventricules et 2 oreillettes','Un seul espace indifférencié','3 cavités'], correct:1, hint:'4 cavités : 2 oreillettes (reçoivent) + 2 ventricules (pompent). Cœur droit = poumons, cœur gauche = corps.' },
      { key:'cir5-4', q:'Le sang apporte aux cellules :', options:['Seulement de l\'eau','O₂ et nutriments ; emporte CO₂ et déchets','Des vitamines uniquement','Rien'], correct:1, hint:'Rôle double du sang : apport (O₂, nutriments) et élimination (CO₂, déchets).' },
      { key:'cir5-5', q:'Les globules rouges (hématies) transportent :', options:['Les nutriments issus de la digestion','Le dioxygène grâce à l\'hémoglobine','Les déchets uniquement','Les anticorps'], correct:1, hint:'Hémoglobine : pigment rouge qui fixe l\'O₂ dans les poumons et le libère dans les tissus.' },
      { key:'cir5-6', q:'Les veines transportent :', options:['Le sang du cœur vers les organes','Le sang des organes vers le cœur','De l\'air','Des sels minéraux'], correct:1, hint:'Veines : retour veineux vers le cœur. Exception : veine pulmonaire (sang oxygéné des poumons).' },
      { key:'cir5-7', q:'Les capillaires sanguins sont :', options:['Des gros vaisseaux visibles','De très fins vaisseaux où se font les échanges avec les cellules','Des artères','Des os'], correct:1, hint:'Capillaires = réseau très fin. La paroi fine permet le passage de l\'O₂, glucose, CO₂.' },
      { key:'cir5-8', q:'La fréquence cardiaque au repos est environ :', options:['15 battements/min','70 battements/min','500 battements/min','10 battements/heure'], correct:1, hint:'Adulte au repos : 60-100 bpm. Sportif entraîné : plus bas. Enfant : plus élevé.' },
      { key:'cir5-9', q:'Un adulte a environ :', options:['1 L de sang','5 L de sang','20 L de sang','50 L de sang'], correct:1, hint:'≈ 5 L de sang chez un adulte moyen.' },
      { key:'cir5-10', q:'L\'hypertension artérielle, c\'est :', options:['Une pression sanguine trop basse','Une pression sanguine trop élevée dans les artères','Un manque de globules rouges','Un type d\'anémie'], correct:1, hint:'TA normale ≈ 120/80 mmHg. Hypertension : > 140/90. Facteur de risque cardiovasculaire majeur.' },
      { key:'cir5-11', q:'Les globules rouges (hématies) transportent l\'oxygène grâce à :', options:['La membrane plasmique','L\'hémoglobine (pigment contenant du fer)','Le noyau','Le cytoplasme vide'], correct:1, hint:'L\'hémoglobine, riche en fer, se lie à l\'O₂ dans les poumons et le libère dans les tissus. D\'où l\'anémie en cas de carence en fer.' },
      { key:'cir5-12', q:'La grande circulation (sang oxygéné) part :', options:['Du ventricule gauche vers les organes','Du ventricule droit vers les poumons','Des poumons vers le cœur','Du foie vers les reins'], correct:0, hint:'Grande circulation : ventricule gauche → aorte → organes → veines caves → oreillette droite. Petite circulation : ventricule droit → poumons → oreillette gauche.' },
    ],
    digestion: [
      { key:'dig5-1', q:'La digestion consiste à :', options:['Respirer plus vite','Transformer les aliments en nutriments absorbables','Brûler les calories directement','Se reproduire'], correct:1, hint:'Digestion : transformations mécaniques + chimiques → nutriments.' },
      { key:'dig5-2', q:'La digestion commence :', options:['Dans l\'estomac','Dans la bouche (dents + salive)','Dans l\'intestin grêle','Dans le foie'], correct:1, hint:'Dans la bouche : mastication + salive (amylase) commencent la dégradation des aliments.' },
      { key:'dig5-3', q:'L\'absorption des nutriments a lieu principalement :', options:['Dans la bouche','Dans l\'estomac','Dans l\'intestin grêle','Dans le foie'], correct:2, hint:'Intestin grêle : grande surface (villosités), passage des nutriments dans le sang.' },
      { key:'dig5-4', q:'Les enzymes digestives servent à :', options:['Transporter l\'O₂','Dégrader chimiquement les aliments en molécules plus petites','Contenir l\'eau','Produire de l\'énergie directement'], correct:1, hint:'Enzymes : catalyseurs biologiques. Ex. amylase (amidon), pepsine (protéines), lipase (graisses).' },
      { key:'dig5-5', q:'L\'estomac produit :', options:['De la bile','De l\'acide chlorhydrique qui aide à dégrader les protéines','Du glucose pur','Du dioxygène'], correct:1, hint:'Suc gastrique (HCl + pepsine) : pH très acide (~2) qui dénature les protéines.' },
      { key:'dig5-6', q:'Le foie produit la bile qui :', options:['Digère les protéines directement','Émulsionne les graisses pour faciliter leur digestion','Absorbe les vitamines','Filtre le sang à lui seul'], correct:1, hint:'Bile : émulsification des lipides → gouttelettes plus fines → meilleure action des lipases.' },
      { key:'dig5-7', q:'Les glucides (sucres) servent principalement à :', options:['Construire les muscles','Fournir de l\'énergie rapidement disponible','Former les os','Transporter l\'O₂'], correct:1, hint:'Glucides = carburant principal des cellules (glucose → énergie par la respiration cellulaire).' },
      { key:'dig5-8', q:'Les protéines servent à :', options:['Rien de particulier','Construire et réparer les cellules et tissus (muscles…)','Donner la couleur de la peau','Hydrater le corps'], correct:1, hint:'Protéines = matériaux de construction du corps.' },
      { key:'dig5-9', q:'Les fibres alimentaires :', options:['Sont digérées comme le sucre','Transitent et aident au bon fonctionnement du système digestif','Sont toxiques en grande quantité','Sont des vitamines'], correct:1, hint:'Non digérées mais utiles au transit intestinal.' },
      { key:'dig5-10', q:'Une alimentation équilibrée comporte :', options:['Uniquement des sucres rapides','Des glucides, protéines, lipides, fibres, vitamines, eau','Uniquement de la viande et des œufs','Uniquement des fruits et légumes'], correct:1, hint:'Variété : produits céréaliers, fruits/légumes, protéines, produits laitiers, matières grasses en juste proportion.' },
      { key:'dig5-11', q:'L\'intestin grêle est si efficace pour l\'absorption grâce à :', options:['Sa couleur rouge vif','Ses villosités intestinales qui multiplient la surface d\'échange','Sa position dans le ventre','Sa rigidité musculaire'], correct:1, hint:'Les villosités (et micro-villosités) de l\'intestin grêle multiplient la surface d\'absorption par 600 ≈ 200 m².' },
      { key:'dig5-12', q:'Le côlon (gros intestin) a pour rôle principal de :', options:['Digérer les protéines','Absorber l\'eau et former les fèces','Produire de la bile','Absorber le glucose'], correct:1, hint:'Le côlon réabsorbe l\'eau et les sels minéraux de la bouillie alimentaire → formation et compaction des matières fécales.' },
    ],
    effortMuscle: [
      { key:'eff5-1', q:'Pendant un effort, les muscles consomment plus :', options:['D\'eau uniquement','De dioxygène et de glucose','De vitamines D','De sel'], correct:1, hint:'Effort → respiration cellulaire accrue → besoin de plus de O₂ et de glucose.' },
      { key:'eff5-2', q:'Pendant un effort, la fréquence cardiaque :', options:['Diminue fortement','Augmente pour fournir plus d\'O₂ et glucose','Reste parfaitement constante','Devient nulle'], correct:1, hint:'Fréquence cardiaque et respiratoire augmentent pour fournir plus d\'O₂ et glucose aux muscles.' },
      { key:'eff5-3', q:'Pourquoi transpire-t-on quand on court ?', options:['Pour se rafraîchir (évaporation refroidit la peau)','Par réflexe nerveux uniquement','Pour se laver','Pas de raison précise'], correct:0, hint:'Thermorégulation : l\'évaporation de la sueur évacue la chaleur produite par les muscles.' },
      { key:'eff5-4', q:'Les muscles se contractent grâce à :', options:['La lumière','Des signaux nerveux envoyés par le cerveau ou la moelle épinière','La chaleur uniquement','L\'eau'], correct:1, hint:'Neurone moteur → influx nerveux → contraction musculaire. Ordre du système nerveux.' },
      { key:'eff5-5', q:'L\'acide lactique s\'accumule dans les muscles lors :', options:['D\'un effort très court (moins de 10 s)','D\'un effort intense et prolongé (manque d\'O₂)','Du sommeil','De la digestion'], correct:1, hint:'Effort anaérobie : pas assez d\'O₂ → fermentation lactique → accumulation d\'acide lactique → courbatures.' },
      { key:'eff5-6', q:'L\'échauffement avant le sport :', options:['Est totalement inutile','Prépare les muscles et réduit le risque de blessure','Augmente la fatigue dès le départ','Sert à manger davantage'], correct:1, hint:'Échauffement augmente la température musculaire, améliore la vascularisation et prépare l\'organisme.' },
      { key:'eff5-7', q:'Après un effort intense, il est conseillé de :', options:['Arrêter brutalement tout mouvement','S\'étirer et récupérer progressivement','Manger uniquement des graisses','Éviter de dormir'], correct:1, hint:'Récupération active : étirements, hydratation, repos. Permet d\'éliminer les déchets et réparer les micro-lésions.' },
      { key:'eff5-8', q:'L\'activité physique régulière :', options:['Affaiblit le cœur progressivement','Renforce le cœur et améliore la capacité respiratoire','Ne change rien sur le long terme','Diminue la masse musculaire'], correct:1, hint:'Entraînement : adaptation cardiovasculaire (cœur plus efficace), musculaire (hypertrophie) et respiratoire.' },
      { key:'eff5-9', q:'Lors d\'un effort intense, le cœur d\'un adolescent peut atteindre :', options:['30 bpm','80 bpm','190-200 bpm','500 bpm'], correct:2, hint:'FC max théorique ≈ 220 − âge. Pour un ado de 13 ans ≈ 207 bpm. Au repos : ~70 bpm.' },
    ],
    microOrg: [
      { key:'mic5-1', q:'Les microorganismes :', options:['Sont tous dangereux pour l\'humain','Sont souvent utiles (yaourt, pain, flore intestinale) mais peuvent aussi être pathogènes','N\'existent pas','Sont visibles à l\'œil nu'], correct:1, hint:'Flore intestinale, levures (pain), bactéries lactiques (yaourt)… mais aussi virus et bactéries pathogènes.' },
      { key:'mic5-2', q:'Une bactérie est :', options:['Un organisme unicellulaire procaryote','Un virus','Une cellule animale classique','Un champignon microscopique'], correct:0, hint:'Bactérie = cellule unique sans vrai noyau (procaryote). Différent des virus (non cellulaires).' },
      { key:'mic5-3', q:'Le yaourt est fabriqué par :', options:['Des virus','Des bactéries lactiques','Des champignons','Une réaction chimique seule'], correct:1, hint:'Fermentation lactique : les bactéries transforment le lactose en acide lactique → yaourt.' },
      { key:'mic5-4', q:'Les levures sont utilisées pour faire lever le pain car elles produisent :', options:['De l\'alcool uniquement','Du CO₂ (qui fait gonfler la pâte)','Du dioxygène pur','Des protéines'], correct:1, hint:'Fermentation : levures (champignons) → CO₂ + alcool. Le CO₂ forme des bulles dans la pâte.' },
      { key:'mic5-5', q:'Un antibiotique est efficace contre :', options:['Tous les microbes sans exception','Les bactéries uniquement, pas les virus','Les virus seulement','Les champignons uniquement'], correct:1, hint:'Antibiotiques ciblés sur les bactéries. Inutiles (et contre-productifs) contre les virus.' },
      { key:'mic5-6', q:'Notre flore intestinale (microbiote) :', options:['Est nuisible à la digestion','Aide à la digestion et protège contre certains pathogènes','N\'existe pas vraiment','Est identique chez tous les individus'], correct:1, hint:'Des milliards de bactéries "amies" colonisent notre intestin, participant à la digestion et l\'immunité.' },
      { key:'mic5-7', q:'Comment les microbes pathogènes entrent-ils dans le corps ?', options:['Par la peau uniquement','Par la bouche, le nez, des blessures, des contacts…','Par les cheveux','Par les os'], correct:1, hint:'Voies d\'entrée : respiratoires, digestives, cutanées (blessures), sexuelles.' },
      { key:'mic5-8', q:'La fermentation alcoolique produit :', options:['Uniquement de l\'eau','De l\'alcool et du CO₂ à partir de sucres','De l\'O₂','Des acides aminés'], correct:1, hint:'Levures + sucres → éthanol + CO₂. Utilisé dans le vin, la bière, le pain.' },
      { key:'mic5-9', q:'Les virus ne sont pas des cellules car ils :', options:['Sont trop petits pour être vivants','N\'ont pas de membrane, pas de cytoplasme, et ne se reproduisent qu\'en parasitant une cellule hôte','Mangent uniquement des bactéries','Ont un noyau mais pas de mitochondries'], correct:1, hint:'Virus = simple capside + acide nucléique. Ils "détournent" la machinerie cellulaire de l\'hôte pour se répliquer.' },
    ],
    plantesNutri: [
      { key:'pla5-1', q:'Les plantes prennent leurs nutriments minéraux :', options:['Dans le sol via les racines (sels minéraux + eau)','Dans l\'air uniquement','Uniquement dans les feuilles','Dans le soleil directement'], correct:0, hint:'Racines absorbent eau + sels minéraux du sol.' },
      { key:'pla5-2', q:'La photosynthèse se fait :', options:['Dans les racines','Dans les feuilles (chlorophylle), à la lumière','Dans les fleurs uniquement','La nuit'], correct:1, hint:'Feuilles + chlorophylle + lumière : H₂O + CO₂ → matière organique + O₂.' },
      { key:'pla5-3', q:'La chlorophylle est :', options:['Un gaz','Un pigment vert qui capte la lumière','Un minéral','Un organisme'], correct:1, hint:'La chlorophylle (verte) capte l\'énergie lumineuse nécessaire à la photosynthèse.' },
      { key:'pla5-4', q:'Pendant la photosynthèse, la plante :', options:['Consomme du CO₂ et rejette de l\'O₂','Consomme de l\'O₂ et rejette du CO₂','Ne fait aucun échange gazeux','Mange des insectes'], correct:0, hint:'C\'est l\'inverse de la respiration. Photosynthèse uniquement le jour.' },
      { key:'pla5-5', q:'La sève brute transportée dans le xylème est :', options:['De la matière organique','De l\'eau et des sels minéraux absorbés par les racines','Du CO₂','Du dioxygène'], correct:1, hint:'Xylème (vaisseaux ligneux) : transport sève brute (eau + minéraux) des racines vers les feuilles.' },
      { key:'pla5-6', q:'La sève élaborée produite par la photosynthèse :', options:['Est de l\'eau pure','Contient les sucres fabriqués par la feuille, distribués à toute la plante','Est du CO₂','Est du sel minéral'], correct:1, hint:'Phloème : transporte la sève élaborée (glucides, acides aminés) vers les organes consommateurs.' },
      { key:'pla5-7', q:'Les stomates des feuilles servent à :', options:['Absorber l\'eau du sol','Permettre les échanges gazeux (CO₂ entre, O₂ sort)','Produire des fleurs','Absorber directement la lumière'], correct:1, hint:'Stomates = pores à la surface des feuilles. Contrôlent l\'entrée de CO₂ et la sortie d\'O₂ et vapeur d\'eau.' },
      { key:'pla5-8', q:'Sans lumière pendant plusieurs jours, une plante :', options:['Pousse encore plus vite','Ne peut plus faire de photosynthèse et s\'affaiblit','N\'a pas besoin de lumière du tout','Devient rouge'], correct:1, hint:'Photosynthèse = source d\'énergie. Privée de lumière, la plante puise dans ses réserves.' },
      { key:'pla5-9', q:'Les plantes ont besoin pour la photosynthèse :', options:['D\'O₂ et de sucre','De CO₂, d\'eau et de lumière','De nitrates uniquement','De chaleur uniquement'], correct:1, hint:'Équation simplifiée : CO₂ + H₂O + énergie lumineuse → glucose + O₂.' },
      { key:'pla5-10', q:'Les racines servent à :', options:['Faire la photosynthèse','Ancrer la plante et absorber l\'eau et les sels minéraux','Produire du pollen','Stocker uniquement le dioxygène'], correct:1, hint:'Double rôle des racines : ancrage + absorption de l\'eau et des nutriments minéraux.' },
      { key:'pla5-11', q:'La transpiration des feuilles (évapotranspiration) sert à :', options:['Rien, c\'est une perte inutile','Créer un flux ascendant de sève brute depuis les racines','Produire de l\'O₂ supplémentaire','Attirer les pollinisateurs'], correct:1, hint:'L\'eau qui s\'évapore par les stomates "tire" la sève brute vers le haut (force aspirante). Indispensable au transport des sels minéraux.' },
      { key:'pla5-12', q:'La photosynthèse produit de la matière organique qui est :', options:['Immédiatement brûlée','Stockée et utilisée pour la croissance, la respiration et les réserves de la plante','Uniquement rejetée','Toujours transformée en CO₂'], correct:1, hint:'Le glucose produit par la photosynthèse permet la respiration cellulaire, la croissance (cellulose, amidon) et les réserves (lipides).' },
    ],
    erosion: [
      { key:'ero5-1', q:'L\'érosion, c\'est :', options:['L\'usure des roches par l\'eau, le vent, le gel…','La formation des volcans','Un séisme sous-marin','La naissance d\'une plante'], correct:0, hint:'Agents d\'érosion : eau, vent, gel, glaciers, vivants.' },
      { key:'ero5-2', q:'Les sédiments sont :', options:['Des morceaux de roches arrachés puis transportés et déposés','Des animaux aquatiques','Uniquement du sable fin','Des plantes aquatiques'], correct:0, hint:'Sédiments : particules issues de l\'érosion, transportées par l\'eau/vent, déposées ailleurs.' },
      { key:'ero5-3', q:'Une roche sédimentaire :', options:['Est issue de la consolidation de sédiments','N\'existe pas dans la nature','Est du magma refroidi','N\'a pas d\'origine précise'], correct:0, hint:'Ex. grès (sable), calcaire (coquilles), argile… formées par compaction de sédiments.' },
      { key:'ero5-4', q:'L\'érosion par le gel est due à :', options:['La chaleur intense du sol','L\'eau qui gèle dans les fissures et les élargit','Le vent froid uniquement','La neige fondue qui recouvre'], correct:1, hint:'L\'eau en gelant se dilate (+9 %) et écarte les parois des fissures → fragmentation de la roche.' },
      { key:'ero5-5', q:'Un canyon se forme par :', options:['Un tremblement de terre unique','L\'érosion d\'une rivière sur des millions d\'années','Un volcan','Le vent uniquement'], correct:1, hint:'Grand Canyon : creusé par le fleuve Colorado sur ~6 millions d\'années.' },
      { key:'ero5-6', q:'Les dunes de sable sont formées par :', options:['L\'eau des rivières','Le vent qui transporte et dépose des grains de sable','Un glissement de terrain','Des animaux'], correct:1, hint:'Le vent transporte les grains de sable, les dépose en formant des dunes (érosion éolienne).' },
      { key:'ero5-7', q:'Le calcaire se dissout par :', options:['La chaleur seule','L\'eau légèrement acide (pluie + CO₂)','Le vent','La lumière'], correct:1, hint:'Érosion chimique du calcaire : CaCO₃ + H₂O + CO₂ → Ca²⁺ soluble. Crée grottes et karsts.' },
      { key:'ero5-8', q:'Les alluvions dans une rivière sont :', options:['Des poissons d\'eau douce','Des sédiments déposés par le courant (sable, gravier, limon)','Des algues filamenteuses','De la roche en fusion'], correct:1, hint:'Alluvions = sédiments fluviaux. En dépôt dans les méandres ou à l\'embouchure (delta).' },
      { key:'ero5-9', q:'Le paysage change au fil :', options:['Des siècles/millénaires (érosion lente)','Des secondes uniquement','Il ne change jamais','Des heures uniquement'], correct:0, hint:'Érosion : processus lents (sauf cas extrême comme une crue ou un glissement).' },
      { key:'ero5-10', q:'Les Alpes vont continuer à :', options:['S\'élever (collision de plaques toujours en cours)','Disparaître sous l\'océan','Rester exactement pareilles','Devenir un désert'], correct:0, hint:'Collision plaque africaine / eurasienne en cours → les Alpes montent encore.' },
      { key:'ero5-11', q:'Un delta fluvial se forme :', options:['Au milieu d\'une rivière','À l\'embouchure d\'un fleuve, là où les alluvions s\'accumulent','Au sommet des montagnes','Dans les grottes souterraines'], correct:1, hint:'Quand un fleuve ralentit à son embouchure, il dépose ses alluvions → delta (ex. Nil, Rhône).' },
      { key:'ero5-12', q:'La dissolution du calcaire par l\'eau acide crée des paysages appelés :', options:['Plaines alluviales','Paysages karstiques (grottes, gouffres, lapiaz)','Deltas fluviaux','Dunes côtières'], correct:1, hint:'Karst : dissolution du CaCO₃ par l\'eau chargée de CO₂ → grottes (stalactites, stalagmites), gouffres, pertes.' },
    ],
    climat: [
      { key:'cli5-1', q:'Le climat d\'une région :', options:['Change tous les jours','Est la météo moyenne sur plusieurs années','Est identique partout sur Terre','Dépend uniquement de la ville'], correct:1, hint:'Météo = court terme (jours). Climat = moyennes à long terme (années/décennies).' },
      { key:'cli5-2', q:'Un été à 28 °C en France : météo ou climat ?', options:['Météo (observation court terme)','Climat (moyenne long terme)','Les deux à la fois','Ni l\'un ni l\'autre'], correct:0, hint:'1 été = météo. 30 ans de moyennes = climat.' },
      { key:'cli5-3', q:'Le changement climatique actuel est :', options:['Dû à des causes naturelles uniquement','Accéléré par les activités humaines (CO₂, méthane…)','Impossible à mesurer','Sans aucune conséquence'], correct:1, hint:'GES (gaz à effet de serre) émis par combustions fossiles, élevage, déforestation.' },
      { key:'cli5-4', q:'Les énergies fossiles émettent en brûlant :', options:['De l\'oxygène pur','Du CO₂ (principal GES)','Rien de particulier','De l\'azote pur'], correct:1, hint:'Combustion : CₓHy + O₂ → CO₂ + H₂O. Le CO₂ s\'accumule dans l\'atmosphère.' },
      { key:'cli5-5', q:'L\'effet de serre naturel :', options:['Est uniquement nuisible','Est indispensable (sans lui la Terre serait à -18 °C)','N\'existe pas','Chauffe la Terre à +100 °C'], correct:1, hint:'Effet de serre naturel → T° moyenne actuelle +15 °C. Le problème = son amplification par l\'humain.' },
      { key:'cli5-6', q:'Les zones climatiques de la Terre comprennent :', options:['Une seule zone uniforme','Des zones tropicale, tempérée, polaire et aride selon la latitude','Uniquement des zones chaudes','Deux zones : nord et sud seulement'], correct:1, hint:'Latitude (angle par rapport à l\'équateur), altitude et courants marins créent des zones climatiques variées.' },
      { key:'cli5-7', q:'Un anticyclone correspond à :', options:['Des vents forts et pluies importantes','Une zone de haute pression avec temps calme et ensoleillé','Un cyclone tropical','Une dépression pluvieuse'], correct:1, hint:'Anticyclone : haute pression → air descend → temps sec et calme. Dépression : basse pression → pluie.' },
      { key:'cli5-8', q:'La déforestation contribue au réchauffement car :', options:['Les arbres font de l\'ombre','Les arbres absorbent du CO₂ ; les couper réduit ce puits de carbone','Les forêts refroidissent la pluie','Les arbres rejettent du méthane'], correct:1, hint:'Forêts = puits de carbone. Déforestation + combustion du bois → double émission de CO₂.' },
      { key:'cli5-9', q:'La montée du niveau des mers est due à :', options:['Plus de pluie tombant dans la mer','La fonte des glaces continentales et la dilatation thermique de l\'eau','Moins d\'évaporation des océans','Plus de rivières se déversant à la mer'], correct:1, hint:'Deux causes : fonte des glaciers/calotte polaire + eau qui se dilate en se réchauffant.' },
      { key:'cli5-10', q:'Pour limiter le réchauffement climatique :', options:['Augmenter la consommation d\'énergies fossiles','Réduire les GES (transport, énergie, alimentation)','Rien ne peut être fait','Planter moins d\'arbres'], correct:1, hint:'Solutions : énergies renouvelables, sobriété, reforestation, moins de viande.' },
      { key:'cli5-11', q:'Les îlots de chaleur urbains sont dus principalement à :', options:['Plus de vent en ville','L\'absorption de chaleur par le béton et l\'asphalte, et moins de végétation','Plus de pluie en ville','L\'altitude des bâtiments qui fait monter la chaleur'], correct:1, hint:'Bitume + béton absorbent la chaleur le jour et la restituent la nuit. Moins de végétation → moins d\'évapotranspiration rafraîchissante.' },
      { key:'cli5-12', q:'Les énergies renouvelables (solaire, éolien, hydraulique) ont comme point commun :', options:['Elles ne produisent aucune énergie','Elles ne rejettent pas (ou peu) de CO₂ lors de la production d\'électricité','Elles nécessitent du charbon','Elles sont toutes issues de l\'énergie nucléaire'], correct:1, hint:'Renouvelables = sources inépuisables (soleil, vent, eau) + bilan carbone faible en fonctionnement. Clés de la transition énergétique.' },
    ],
  },
  PICK: {
    respiration: 4, circulation: 4, digestion: 4, effortMuscle: 3, microOrg: 3,
    plantesNutri: 4, erosion: 4, climat: 4,
  },
  PLANS: {
    respiration: {
      'non-acquis': ['Rôle des alvéoles pulmonaires dans les échanges gazeux', 'Mécanique respiratoire : rôle du diaphragme (inspire = descend)', 'Tabac : connaître les risques'],
      'fragile':    ['Voies aériennes dans l\'ordre : nez → trachée → bronches → alvéoles']
    },
    circulation: {
      'non-acquis': ['Cœur = pompe musculaire à 4 cavités', 'Artères (cœur → organes) vs veines (organes → cœur)', 'Rôle du sang : transport O₂, nutriments, CO₂, déchets'],
      'fragile':    ['Double circulation (pulmonaire + générale)']
    },
    digestion: {
      'non-acquis': ['Digestion commence dans la bouche', 'Absorption dans l\'intestin grêle', 'Alimentation équilibrée (variée, proportionnée)'],
      'fragile':    ['Rôles des glucides, lipides, protéines ; rôle de la bile']
    },
    effortMuscle: {
      'non-acquis': ['Effort → augmentation FC et FR pour plus d\'O₂/glucose', 'Transpiration = thermorégulation', 'Échauffement indispensable'],
      'fragile':    ['Récupération post-effort ; acide lactique']
    },
    microOrg: {
      'non-acquis': ['Microbes : utiles (flore, fermentation) ou pathogènes', 'Bactérie ≠ virus ≠ champignon', 'Antibiotiques = contre bactéries seulement'],
      'fragile':    ['Fermentation lactique (yaourt) vs alcoolique (pain, vin)']
    },
    plantesNutri: {
      'non-acquis': ['Racines absorbent eau et sels minéraux', 'Photosynthèse dans les feuilles : CO₂ + H₂O → matière organique + O₂', 'Rôle de la chlorophylle et de la lumière'],
      'fragile':    ['Sève brute (xylème) vs sève élaborée (phloème)']
    },
    erosion: {
      'non-acquis': ['Érosion = usure des roches par l\'eau, vent, gel', 'Sédiments → roches sédimentaires', 'Temps géologique long'],
      'fragile':    ['Cycle des roches et notion de paysage']
    },
    climat: {
      'non-acquis': ['Différencier météo (court terme) et climat (long terme)', 'Changement climatique : origine anthropique (GES)', 'Conséquences : fonte glaces, montée eaux, sécheresses'],
      'fragile':    ['Éco-gestes pour réduire son empreinte']
    },
  },
};
