// Source éditable — quiz svt-4. Régénéré automatiquement dans index.html via build.sh.
window.ALL_QUIZZES['svt-4'] = {
  SEARCH_SITES: 'site:fr.khanacademy.org OR site:lumni.fr OR site:planet-vie.ens.fr',
  YT_SUFFIX: 'college svt',
  SUMMER_TOPIC: 'SVT',
  SUBJECT: {
    id: 'svt-4',
    name: 'Sciences de la Vie et de la Terre',
    short: 'SVT',
    level: 'Fin de 4ème',
    mark: '🌿',
    tagline: 'Évaluation diagnostique',
  },
  DOMAINS: {
  reproduction: { id:'reproduction', name:'Reproduction humaine & puberté',        short:'Reproduction', coef:3, color:'#be185d', icon:'♂♀', search:'reproduction humaine puberte 4eme' },
  cycle:        { id:'cycle',        name:'Cycle menstruel & fécondation',         short:'Cycle',        coef:3, color:'#db2777', icon:'○',  search:'cycle menstruel fecondation 4eme' },
  contraception:{ id:'contraception',name:'Contraception & IST',                   short:'Contraception',coef:3, color:'#a21caf', icon:'⊘',  search:'contraception ist sida 4eme' },
  plaques:      { id:'plaques',      name:'Tectonique des plaques',                short:'Plaques',      coef:3, color:'#7c2d12', icon:'≡',  search:'tectonique plaques 4eme' },
  seismes:      { id:'seismes',      name:'Séismes & risques',                     short:'Séismes',      coef:3, color:'#a01b34', icon:'⚠',  search:'seismes ondes sismiques 4eme' },
  volcans:      { id:'volcans',      name:'Volcanisme',                            short:'Volcans',      coef:3, color:'#c2410c', icon:'▲',  search:'volcanisme eruption magma 4eme' },
  reproVeg:     { id:'reproVeg',     name:'Reproduction des végétaux',             short:'Plantes',      coef:2, color:'#15803d', icon:'✿',  search:'reproduction plantes pollinisation 4eme' },
  biodiversite: { id:'biodiversite', name:'Biodiversité & évolution',              short:'Biodiversité', coef:2, color:'#166a39', icon:'♾',  search:'biodiversite evolution 4eme' },
  nutrition:    { id:'nutrition',    name:'Nutrition, respiration, circulation',   short:'Corps humain', coef:3, color:'#b91c1c', icon:'♥',  search:'nutrition respiration circulation 4eme' },
  environnement:{ id:'environnement',name:'Environnement & santé',                 short:'Environnement',coef:2, color:'#059669', icon:'☘',  search:'environnement sante hygiene 4eme' },
  },
  RESOURCES: [
  { label:'Khan Academy — Biologie', author:'Cours + exos gratuits',          url:'https://fr.khanacademy.org/science/ms-biology' },
  { label:'Lumni — SVT 4ème',        author:'France TV éducation',            url:'https://www.lumni.fr/college/quatrieme/svt' },
  { label:'Planet-Vie',              author:'ENS — ressources SVT',           url:'https://planet-vie.ens.fr/' },
  { label:'SVT à l\'école',          author:'YouTube (cours de collège)',     url:'https://www.youtube.com/results?search_query=svt+4eme+cours' },
  ],
  POOL: {
  reproduction: [
    { key:'rep4-1', q:'La puberté correspond au moment où :',
      options:['Le corps cesse de grandir','Le corps devient capable de se reproduire','On entre en primaire','On arrête la croissance osseuse définitivement'], correct:1,
      hint:'Puberté = passage à la maturité sexuelle. Les appareils reproducteurs deviennent fonctionnels.' },
    { key:'rep4-2', q:'Les cellules reproductrices masculines sont :',
      options:['Les ovules','Les spermatozoïdes','Les neurones','Les globules rouges'], correct:1,
      hint:'Spermatozoïdes (produits par les testicules). Les femmes produisent des ovules (ovaires).' },
    { key:'rep4-3', q:'Les ovaires libèrent :',
      options:['Un ovule par cycle (ovulation)','Des spermatozoïdes','Du sang menstruel','De la salive'], correct:0,
      hint:'Environ 1 ovule libéré par cycle (ovulation), vers le 14ᵉ jour.' },
    { key:'rep4-4', q:'Les caractères sexuels secondaires apparaissent :',
      options:['À la naissance','À la puberté sous l\'effet des hormones','À 20 ans','Jamais'], correct:1,
      hint:'Caractères secondaires (pilosité, voix, poitrine, musculature) = à la puberté sous l\'effet des hormones.' },
    { key:'rep4-5', q:'Les hormones responsables de la puberté sont produites par :',
      options:['Le cerveau (hypophyse) et les gonades (ovaires/testicules)','Le foie','Les poumons','La peau uniquement'], correct:0,
      hint:'L\'hypophyse (cerveau) commande les ovaires/testicules qui produisent œstrogènes/testostérone.' },
    { key:'rep4-6', q:'L\'appareil reproducteur féminin comprend :',
      options:['Les poumons et le cœur','Les ovaires, les trompes, l\'utérus et le vagin','Les reins et la vessie','Les muscles uniquement'], correct:1,
      hint:'Organes reproducteurs féminins : ovaires (ovules), trompes (fécondation), utérus (nidation), vagin.' },
    { key:'rep4-7', q:'Les testicules produisent :',
      options:['Des ovules','Du sang','Des spermatozoïdes et la testostérone','Des hormones uniquement'], correct:2,
      hint:'Les testicules sont à la fois producteurs de spermatozoïdes et de la testostérone.' },
    { key:'rep4-8', q:'Les œstrogènes sont des hormones :',
      options:['Masculines uniquement','Féminines (produites surtout par les ovaires)','Sans aucun effet connu','Produites par les reins'], correct:1,
      hint:'Œstrogènes produits par les ovaires : développement des caractères féminins et contrôle du cycle.' },
    { key:'rep4-9', q:'La testostérone est une hormone qui :',
      options:['Déclenche l\'ovulation','Contrôle les caractères masculins et la production de spermatozoïdes','Régule la digestion','Est produite uniquement par le cerveau'], correct:1,
      hint:'Testostérone = hormone stéroïde masculine produite par les testicules sous contrôle de l\'hypophyse.' },
  ],

  cycle: [
    { key:'cyc4-1', q:'La durée moyenne d\'un cycle menstruel est d\'environ :',
      options:['7 jours','14 jours','28 jours','365 jours'], correct:2,
      hint:'Cycle menstruel moyen = 28 jours, mais il peut varier de 21 à 35 jours selon les femmes.' },
    { key:'cyc4-2', q:'L\'ovulation a lieu en général :',
      options:['Au 1er jour du cycle','Vers le 14ᵉ jour du cycle','Au 28ᵉ jour','Jamais spontanément'], correct:1,
      hint:'Ovulation vers le milieu du cycle (jour 14 pour un cycle de 28 jours).' },
    { key:'cyc4-3', q:'La fécondation correspond à :',
      options:['La rencontre d\'un ovule et d\'un spermatozoïde → cellule-œuf','La naissance du bébé','L\'ovulation elle-même','Les règles'], correct:0,
      hint:'Fécondation = fusion du noyau de l\'ovule et d\'un spermatozoïde → zygote (cellule-œuf).' },
    { key:'cyc4-4', q:'Les règles correspondent à :',
      options:['La fécondation de l\'ovule','L\'élimination de la paroi de l\'utérus (endomètre)','La naissance','La puberté'], correct:1,
      hint:'Si pas de fécondation, la paroi utérine (endomètre) se détache → saignements = règles.' },
    { key:'cyc4-5', q:'La fécondation a lieu habituellement :',
      options:['Dans l\'utérus','Dans une trompe de Fallope','Dans l\'ovaire','Dans le vagin'], correct:1,
      hint:'Rencontre ovule-spermatozoïde dans une trompe de Fallope, puis l\'œuf migre vers l\'utérus.' },
    { key:'cyc4-6', q:'La durée normale d\'une grossesse humaine est d\'environ :',
      options:['3 mois','6 mois','9 mois (40 semaines)','12 mois'], correct:2,
      hint:'Environ 9 mois (40 semaines d\'aménorrhée = depuis les dernières règles).' },
    { key:'cyc4-7', q:'La nidation, c\'est :',
      options:['L\'ovulation','L\'implantation de l\'embryon dans la paroi de l\'utérus','La fécondation','Les règles'], correct:1,
      hint:'Quelques jours après la fécondation, l\'embryon s\'implante dans l\'endomètre (nidation).' },
    { key:'cyc4-8', q:'Si la fécondation a lieu, les règles :',
      options:['Deviennent plus abondantes','N\'ont pas lieu (le cycle est interrompu)','Continuent normalement','Commencent plus tôt'], correct:1,
      hint:'En cas de grossesse, la paroi utérine ne se détache pas → pas de règles.' },
    { key:'cyc4-9', q:'La durée de vie d\'un ovule après l\'ovulation est d\'environ :', options:['24 heures','7 jours','1 mois','5 jours'], correct:0, hint:'Ovule viable pendant ~24 h. Les spermatozoïdes peuvent rester fécondants jusqu\'à 5 jours → fenêtre de fécondité.' },
  ],

  contraception: [
    { key:'con4-1', q:'Le SIDA est causé par :',
      options:['Une bactérie','Un virus (le VIH)','Un champignon','Un parasite'], correct:1,
      hint:'VIH = Virus de l\'Immunodéficience Humaine. Il détruit les défenses immunitaires.' },
    { key:'con4-2', q:'Quelle méthode de contraception protège aussi des IST ?',
      options:['La pilule','Le préservatif','Le stérilet (DIU)','L\'implant'], correct:1,
      hint:'Seul le préservatif protège à la fois d\'une grossesse non désirée ET des IST.' },
    { key:'con4-3', q:'La pilule contraceptive agit en :',
      options:['Bloquant l\'ovulation (hormones de synthèse)','Tuant les spermatozoïdes directement','Protégeant des IST','Stoppant les règles définitivement'], correct:0,
      hint:'La pilule apporte des hormones qui empêchent l\'ovulation.' },
    { key:'con4-4', q:'Parmi ces IST, laquelle est causée par un virus ?',
      options:['La chlamydia (bactérie)','Le VIH/SIDA','La gonorrhée (bactérie)','La syphilis (bactérie)'], correct:1,
      hint:'VIH = virus. Chlamydia, gonorrhée, syphilis = bactéries. HPV, herpès, hépatite B = aussi des virus.' },
    { key:'con4-5', q:'Les IST se transmettent principalement par :',
      options:['Les poignées de main','Les relations sexuelles non protégées','L\'air que l\'on respire','Les repas partagés'], correct:1,
      hint:'IST = Infections Sexuellement Transmissibles. Transmission essentiellement lors des rapports sexuels.' },
    { key:'con4-6', q:'Le stérilet (DIU) est :',
      options:['Un médicament avalé chaque jour','Un dispositif placé dans l\'utérus par un médecin','Un préservatif interne','Un vaccin'], correct:1,
      hint:'DIU = Dispositif Intra-Utérin. Contraception longue durée, ne protège pas des IST.' },
    { key:'con4-7', q:'En cas de rapport à risque, la contraception d\'urgence :',
      options:['Doit être prise au plus tôt après le rapport','Peut être prise n\'importe quand dans le mois','Protège des IST','Est totalement inutile'], correct:0,
      hint:'Pilule du lendemain : plus elle est prise tôt, plus elle est efficace. Consulter pour test IST.' },
    { key:'con4-8', q:'Pourquoi le VIH est-il si grave ?',
      options:['Il cause des rhumes répétés','Il détruit les lymphocytes T4, affaiblissant toute la défense immunitaire','Il bloque la digestion','Il attaque les os'], correct:1,
      hint:'VIH → SIDA : destruction des lymphocytes T4 → incapacité à se défendre contre d\'autres infections.' },
    { key:'con-9', q:'Le préservatif est le seul moyen de contraception qui :', options:['Est réutilisable','Protège aussi contre les IST (dont le VIH)','Agit sur le cycle hormonal','Ne marche qu\'avec une ordonnance'], correct:1, hint:'La pilule, le stérilet, l\'implant contraceptent mais ne protègent pas des infections sexuellement transmissibles. Seul le préservatif (masculin ou féminin) fait les deux.' },
    { key:'con-10', q:'La pilule contraceptive agit en :', options:['Tuant les spermatozoïdes mécaniquement','Bloquant l\'ovulation par action hormonale','Empêchant la fécondation dans les trompes','Déclenchant des règles permanentes'], correct:1, hint:'La pilule combinée (œstrogène + progestérone) bloque l\'ovulation et rend la glaire cervicale hostile aux spermatozoïdes.' },
  ],

  plaques: [
    { key:'pla4-1', q:'La surface de la Terre est découpée en :',
      options:['2 morceaux','Des plaques lithosphériques','Des continents fixes','Un seul bloc rigide'], correct:1,
      hint:'La lithosphère est découpée en une dizaine de plaques qui bougent lentement.' },
    { key:'pla4-2', q:'Les plaques lithosphériques se déplacent de :',
      options:['Quelques km par seconde','Quelques cm par an','Quelques mètres par heure','Elles sont complètement immobiles'], correct:1,
      hint:'Vitesse de l\'ordre de quelques cm/an (aussi vite que pousse un ongle).' },
    { key:'pla4-3', q:'Aux zones de subduction :',
      options:['Une plaque plonge sous une autre','Les plaques se séparent','Rien de particulier ne se passe','Un désert se forme'], correct:0,
      hint:'Subduction = convergence où la plaque océanique plonge sous l\'autre → séismes et volcanisme.' },
    { key:'pla4-4', q:'Aux dorsales océaniques :',
      options:['Les plaques se rapprochent','Les plaques s\'écartent (création de croûte océanique)','Rien ne bouge','Uniquement des volcans explosifs'], correct:1,
      hint:'Dorsale = zone de divergence. Création de nouvelle croûte océanique par remontée de magma.' },
    { key:'pla4-5', q:'L\'Himalaya est né de :',
      options:['Une divergence de plaques','La collision de la plaque indienne et eurasienne','Un seul grand volcan','Un seul séisme majeur'], correct:1,
      hint:'Collision de deux plaques continentales → pas de subduction → surrection montagnarde (Alpes, Himalaya).' },
    { key:'pla4-6', q:'La lithosphère est composée :',
      options:['Uniquement de la croûte terrestre','De la croûte + la partie supérieure du manteau (rigide)','Du noyau externe','Du magma uniquement'], correct:1,
      hint:'Lithosphère = croûte + manteau supérieur rigide. Flotte sur l\'asthénosphère (manteau ductile).' },
    { key:'pla4-7', q:'La preuve du mouvement des plaques vient notamment de :',
      options:['La couleur des roches en surface','La correspondance des formes des côtes et la similitude des fossiles','La température de l\'air','La présence de l\'eau'], correct:1,
      hint:'Wegener (1912) : côtes de l\'Amérique du Sud et de l\'Afrique s\'emboîtent + mêmes fossiles des deux côtés.' },
    { key:'pla4-8', q:'Les mouvements des plaques créent aussi :',
      options:['Les saisons','Les chaînes de montagnes (orogénèse)','La rotation de la Terre','Les marées'], correct:1,
      hint:'Collision entre plaques → surrection → chaînes de montagnes. Subduction → arc volcanique.' },
    { key:'pla4-9', q:'La "ceinture de feu du Pacifique" est :', options:['Une région toujours couverte de neige','Une zone très sismique et volcanique qui entoure l\'océan Pacifique','Un courant océanique chaud','Une chaîne de montagnes sous-marine'], correct:1, hint:'La ceinture de feu (Ring of Fire) : ~75 % des volcans et ~90 % des séismes de la planète → limites de plaques.' },
  ],

  seismes: [
    { key:'sei4-1', q:'L\'endroit où se produit la rupture à l\'origine d\'un séisme s\'appelle :',
      options:['L\'épicentre','Le foyer (ou hypocentre)','La faille','Le magma'], correct:1,
      hint:'Foyer = point de la rupture en profondeur. Épicentre = point en surface juste au-dessus.' },
    { key:'sei4-2', q:'Les séismes se propagent sous forme :',
      options:['De courants d\'air','D\'ondes sismiques','De chaleur rayonnante','De lumière'], correct:1,
      hint:'Ondes sismiques (P rapides, puis S, puis L de surface). Détectées par les sismographes.' },
    { key:'sei4-3', q:'La magnitude d\'un séisme mesure :',
      options:['Les effets ressentis en surface par les habitants','L\'énergie libérée à la source (échelle de Richter)','La durée des secousses','La couleur des ondes'], correct:1,
      hint:'Magnitude (Richter) = énergie libérée. Intensité (Mercalli) = effets ressentis en surface.' },
    { key:'sei4-4', q:'Le risque sismique dépend :',
      options:['Uniquement de l\'aléa (probabilité)','De l\'aléa et de la vulnérabilité (bâtiments, population)','De la météo du jour','De la population seule'], correct:1,
      hint:'Risque = aléa (probabilité d\'un séisme) × enjeu/vulnérabilité (constructions, population).' },
    { key:'sei4-5', q:'Un tsunami est causé par :',
      options:['Un fort vent marin','Un séisme sous-marin ou un glissement de terrain sous-marin','Un volcan terrestre','La marée'], correct:1,
      hint:'Séisme sous-marin → déplacement vertical du fond → vague géante. Ex. Sumatra 2004.' },
    { key:'sei4-6', q:'Pour se protéger lors d\'un séisme en intérieur :',
      options:['Courir dehors immédiatement','Se mettre sous une table solide ou dans un angle de mur','Utiliser l\'ascenseur','Ouvrir toutes les fenêtres'], correct:1,
      hint:'Consignes : se protéger la tête, s\'éloigner des vitres, ne jamais prendre l\'ascenseur.' },
    { key:'sei4-7', q:'Les zones les plus sismiques sur Terre se trouvent :',
      options:['Au centre des continents','Aux limites des plaques tectoniques','Uniquement dans les océans','Aux pôles'], correct:1,
      hint:'Ceinture de feu du Pacifique, failles transformantes, zones de subduction = zones sismiques majeures.' },
    { key:'sei4-8', q:'Les séismes résultent :',
      options:['De marées','D\'une rupture brutale des roches en profondeur','D\'orages violents','Du vent'], correct:1,
      hint:'Les roches accumulent des contraintes, puis cassent brutalement → ondes qui se propagent.' },
    { key:'sei4-9', q:'Parmi ces pays, lequel est particulièrement exposé aux risques sismiques ?', options:['France métropolitaine','Japon','Belgique','Pays-Bas'], correct:1, hint:'Le Japon est sur la ceinture de feu du Pacifique, à la jonction de plusieurs plaques. Plusieurs milliers de séismes par an.' },
  ],

  volcans: [
    { key:'vol4-1', q:'Le magma est :',
      options:['De la roche fondue en profondeur (chambre magmatique)','De l\'eau très chaude','Du sable en fusion','Du sel minéral'], correct:0,
      hint:'Magma = roche fondue dans la chambre magmatique. Une fois sorti du volcan = lave.' },
    { key:'vol4-2', q:'Une éruption effusive se caractérise par :',
      options:['De grosses explosions et nuées ardentes','Des coulées de lave fluide','Des nuées ardentes uniquement','Aucune lave visible'], correct:1,
      hint:'Effusive = lave fluide qui coule (volcans hawaïens). Explosive = lave visqueuse + forte explosion (Vésuve).' },
    { key:'vol4-3', q:'Une éruption explosive produit souvent :',
      options:['Des nuées ardentes (mélange gaz+cendres très chaud)','Uniquement de la neige','Rien de dangereux','Juste de la fumée'], correct:0,
      hint:'Nuées ardentes = mélange gaz+cendres+blocs à plus de 500 °C, dévalent à 100 km/h. Très mortel.' },
    { key:'vol4-4', q:'Les volcans se forment principalement :',
      options:['N\'importe où sur Terre','Aux limites des plaques tectoniques (subduction, dorsales)','Au centre des continents uniquement','Dans les déserts'], correct:1,
      hint:'Zones volcaniques = dorsales, zones de subduction, points chauds (ex. Hawaï).' },
    { key:'vol4-5', q:'Le Piton de la Fournaise (La Réunion) est un volcan :',
      options:['Explosif très dangereux','Effusif (lave fluide, peu explosif)','Inactif depuis 200 ans','Uniquement sous-marin'], correct:1,
      hint:'Piton de la Fournaise = volcan de point chaud, type hawaïen, effusif. Lave basaltique fluide.' },
    { key:'vol4-6', q:'La lave solidifiée forme :',
      options:['Des sédiments calcaires','Des roches magmatiques (basalte, granite)','Du calcaire','De l\'argile'], correct:1,
      hint:'Lave refroidie → basalte (éruption). Magma refroidi en profondeur → granite (plutonique).' },
    { key:'vol4-7', q:'Les cendres volcaniques peuvent :',
      options:['Être bénéfiques uniquement','Provoquer effondrements de toits, bloquer avions, polluer l\'air et l\'eau','Être toujours inoffensives','Ne jamais se disperser loin du volcan'], correct:1,
      hint:'Cendres : risques à court terme (aviation, toits) et long terme (fertilisation des sols).' },
    { key:'vol4-8', q:'Quelle est la différence principale entre magma et lave ?',
      options:['Ce sont exactement la même chose','Le magma est en profondeur, la lave est sortie à la surface','La lave est plus chaude','Le magma est solide'], correct:1,
      hint:'Même roche fondue : appelée magma dans la chambre magmatique, lave une fois sortie par l\'éruption.' },
    { key:'vol4-9', q:'Le Vésuve (Italie) est un exemple de volcan :', options:['Effusif, très peu dangereux','Explosif, avec risque de nuées ardentes (type Pompéi en 79 après J.-C.)','Sous-marin uniquement','Éteint depuis plus de 10 000 ans'], correct:1, hint:'Le Vésuve est explosif : en 79 après J.-C., il a enseveli Pompéi sous des cendres et des nuées ardentes.' },
  ],

  reproVeg: [
    { key:'veg4-1', q:'Chez les plantes à fleurs, l\'organe reproducteur est :',
      options:['La feuille','La fleur','La racine','La tige'], correct:1,
      hint:'La fleur contient étamines (mâle, pollen) et pistil (femelle, ovules).' },
    { key:'veg4-2', q:'La pollinisation est :',
      options:['Le transport du pollen vers le pistil','La germination de la graine','La pousse d\'une racine','La chute des feuilles en automne'], correct:0,
      hint:'Pollinisation par vent, insectes (abeilles), oiseaux… Le pollen féconde l\'ovule du pistil.' },
    { key:'veg4-3', q:'Après fécondation, l\'ovule devient :',
      options:['Une racine','Une graine','Une feuille','Un fruit'], correct:1,
      hint:'Ovule fécondé → graine. Le pistil (ovaire floral) se transforme en fruit.' },
    { key:'veg4-4', q:'La reproduction asexuée chez les plantes :',
      options:['N\'existe pas dans la nature','Produit des clones (bouturage, marcottage, stolons)','Nécessite deux parents obligatoirement','Est extrêmement rare'], correct:1,
      hint:'Reproduction asexuée = bouturage, marcottage, stolons. Descendants identiques au parent.' },
    { key:'veg4-5', q:'Le rôle du fruit est principalement :',
      options:['De décorer la plante','De protéger la graine et favoriser sa dispersion','De produire de l\'énergie','D\'empêcher la pollinisation'], correct:1,
      hint:'Le fruit protège la graine et aide à sa dispersion (animaux, vent, eau).' },
    { key:'veg4-6', q:'La germination d\'une graine nécessite :',
      options:['La lumière uniquement','De l\'eau, de la chaleur et parfois de l\'oxygène','Du sel','Un animal'], correct:1,
      hint:'Conditions de germination : eau (imbibition), température adéquate, O₂ pour la respiration.' },
    { key:'veg4-7', q:'Chez les conifères (pins, sapins), les graines sont contenues dans :',
      options:['Des fruits charnus','Des cônes','Des fleurs','Des feuilles'], correct:1, hint:'Conifères = gymnospermes : graines nues protégées dans des cônes (pas de vrai fruit).' },
    { key:'veg4-8', q:'Les abeilles contribuent à la reproduction des plantes en :', options:['Mangeant les fleurs','Transportant le pollen d\'une fleur à l\'autre (pollinisation)','Arrosant les racines','Creusant le sol'], correct:1, hint:'Pollinisateurs : abeilles, papillons, bourdons → essentiels pour la reproduction des plantes à fleurs.' },
    { key:'veg4-9', q:'La dispersion des graines peut se faire par :', options:['La photosynthèse','Le vent, les animaux (en mangeant les fruits) ou l\'eau','Uniquement par les racines','La lumière solaire'], correct:1, hint:'Anémochorie (vent), zoochorie (animaux), hydrochorie (eau). La diversité des fruits reflète ces stratégies.' },
  ],

  biodiversite: [
    { key:'bio4-1', q:'La biodiversité désigne :',
      options:['Seulement les animaux visibles','La diversité du vivant (espèces, gènes, écosystèmes)','Seulement les plantes','Les minéraux'], correct:1,
      hint:'Biodiversité = diversité des espèces + diversité génétique + diversité des écosystèmes.' },
    { key:'bio4-2', q:'Les fossiles permettent :',
      options:['De dater les roches et d\'étudier l\'évolution des espèces','De chauffer les maisons','De produire de l\'électricité','De manger'], correct:0,
      hint:'Fossiles = témoins de la vie passée. Ils montrent que les espèces ont changé au cours des temps géologiques.' },
    { key:'bio4-3', q:'Les espèces actuelles :',
      options:['Existent depuis toujours sans changer','Résultent d\'une évolution à partir d\'ancêtres communs','Ont été créées récemment','N\'ont aucun lien entre elles'], correct:1,
      hint:'Les espèces évoluent au cours du temps par sélection naturelle (Darwin).' },
    { key:'bio4-4', q:'La sélection naturelle favorise :',
      options:['Les individus les plus grands uniquement','Les individus les mieux adaptés à leur milieu (plus de descendants)','Tous les individus identiquement','Aucun individu particulier'], correct:1,
      hint:'Darwin : les individus avec des variations avantageuses survivent et se reproduisent davantage → transmission des caractères.' },
    { key:'bio4-5', q:'Deux espèces appartenant à un même groupe ont :',
      options:['Rien en commun','Un ancêtre commun','Obligatoirement la même taille','Obligatoirement le même habitat'], correct:1,
      hint:'La parenté phylogénétique se lit via les caractères communs hérités d\'un ancêtre commun.' },
    { key:'bio4-6', q:'L\'activité humaine peut :',
      options:['Toujours augmenter la biodiversité','Menacer la biodiversité (destruction d\'habitats, pollution)','N\'avoir aucun impact','Créer de nouvelles espèces en quelques années'], correct:1,
      hint:'Pollution, déforestation, surexploitation, changement climatique → 6ᵉ extinction de masse en cours.' },
    { key:'bio4-7', q:'Une espèce est dite "menacée d\'extinction" quand :',
      options:['Elle est très nombreuse','Ses effectifs diminuent au point qu\'elle risque de disparaître','Elle vit dans plusieurs pays','Elle est très commune'], correct:1,
      hint:'UICN : liste rouge des espèces menacées. Ex. tigre de Sibérie, rhinocéros, gorille des montagnes.' },
    { key:'bio4-8', q:'La déforestation tropicale est une menace pour la biodiversité car :',
      options:['Les forêts ne servent à rien','Les forêts tropicales abritent 50-80 % des espèces terrestres','Les arbres bloquent la lumière','Les forêts produisent trop d\'O₂'], correct:1,
      hint:'La forêt tropicale = hotspot de biodiversité. Sa destruction entraîne des extinctions massives.' },
    { key:'bio4-9', q:'La notion de "services écosystémiques" désigne :', options:['Les services commerciaux rendus par les parcs nationaux','Les bénéfices que les humains tirent des écosystèmes (eau propre, pollinisation, air pur…)','Les animaux domestiques','Les industries agroalimentaires'], correct:1, hint:'Services écosystémiques : pollinisation, purification de l\'eau, régulation du climat, sols fertiles… bénéfices gratuits fournis par la nature.' },
  ],

  nutrition: [
    { key:'nut4-1', q:'Lors de la respiration, le corps :',
      options:['Rejette du O₂ et absorbe du CO₂','Absorbe du O₂ et rejette du CO₂','N\'échange rien','Rejette de l\'azote uniquement'], correct:1,
      hint:'On inspire du dioxygène (O₂) et on rejette du dioxyde de carbone (CO₂) issu des cellules.' },
    { key:'nut4-2', q:'Les échanges gazeux respiratoires ont lieu dans :',
      options:['L\'estomac','Les alvéoles pulmonaires','Le cœur','Le foie'], correct:1,
      hint:'Alvéoles = petits sacs au bout des bronchioles, très vascularisés → échanges O₂/CO₂ avec le sang.' },
    { key:'nut4-3', q:'La digestion transforme les aliments en :',
      options:['Déchets uniquement','Nutriments absorbables par l\'intestin','Gaz digestifs','Eau pure'], correct:1,
      hint:'Digestion mécanique + chimique → nutriments → absorbés dans l\'intestin grêle puis transportés par le sang.' },
    { key:'nut4-4', q:'Les cellules produisent de l\'énergie à partir :',
      options:['Uniquement d\'eau','De nutriments + dioxygène (respiration cellulaire)','De lumière directement','De rien'], correct:1,
      hint:'Respiration cellulaire : nutriments + O₂ → énergie + CO₂ + eau.' },
    { key:'nut4-5', q:'La respiration cellulaire a lieu dans :',
      options:['Le noyau','Les mitochondries','La membrane cellulaire','Le cytoplasme uniquement'], correct:1,
      hint:'Mitochondries = centrales énergétiques de la cellule (ATP). Nutriments + O₂ → énergie + CO₂ + H₂O.' },
    { key:'nut4-6', q:'Le sang est mis en mouvement par :',
      options:['Les muscles squelettiques','Le cœur','Les poumons','L\'estomac'], correct:1,
      hint:'Le cœur fait circuler le sang dans les artères, capillaires et veines (appareil circulatoire).' },
    { key:'nut4-7', q:'L\'urée est un déchet produit par :',
      options:['Les poumons','La dégradation des protéines dans le foie, éliminé par les reins','Les muscles uniquement','Les os'], correct:1,
      hint:'Urée = déchet azoté du catabolisme des protéines. Foie → sang → reins → urine.' },
    { key:'nut4-8', q:'La glycémie correspond à :',
      options:['Le taux de lipides dans le sang','Le taux de glucose dans le sang (normal ≈ 1 g/L)','La pression sanguine','Le nombre de globules rouges'], correct:1,
      hint:'Glycémie normale à jeun : ~1 g/L. Diabète : glycémie chroniquement > 1,26 g/L à jeun.' },
    { key:'nut4-9', q:'Les nutriments sont transportés dans le corps par :',
      options:['L\'air','Le sang','La peau','La salive'], correct:1,
      hint:'Le sang apporte aux organes dioxygène et nutriments, et emporte les déchets (CO₂, urée).' },
    { key:'nut4-10', q:'Le rôle du foie dans la nutrition est :',
      options:['Uniquement de produire la bile','Stocker le glycogène, réguler la glycémie, détoxifier, produire la bile','Pomper le sang','Absorber les lipides directement'], correct:1,
      hint:'Foie = organe central du métabolisme : glycogène, lipides, protéines, bile, détoxification.' },
    { key:'nut4-11', q:'L\'insuline est une hormone qui :', options:['Augmente le taux de glucose dans le sang','Fait entrer le glucose dans les cellules et abaisse la glycémie','Détruit les globules rouges','Produit de la bile'], correct:1, hint:'Après un repas, la glycémie monte → pancréas sécrète insuline → les cellules captent le glucose → glycémie revient à 1 g/L.' },
    { key:'nut4-12', q:'Les reins servent à :', options:['Produire de l\'insuline','Filtrer le sang et éliminer les déchets (urée, eau en excès) dans les urines','Pomper le sang','Absorber les vitamines'], correct:1, hint:'Reins = organes épurateurs : filtration du sang, élimination de l\'urée, régulation de l\'eau et des minéraux.' },
  ],

  environnement: [
    { key:'env4-1', q:'Pour rester en bonne santé, il est important :',
      options:['De manger varié, bouger, dormir suffisamment','De rester couché toute la journée','De manger uniquement du sucre','De sauter des repas régulièrement'], correct:0,
      hint:'Hygiène de vie = alimentation équilibrée + activité physique + sommeil + hygiène corporelle.' },
    { key:'env4-2', q:'Le tabac et l\'alcool :',
      options:['Sont sans aucun effet prouvé','Sont des facteurs de risque pour la santé','Aident à grandir plus vite','Sont recommandés aux adolescents'], correct:1,
      hint:'Tabac : cancers, maladies cardiovasculaires. Alcool : foie, cerveau, dépendance.' },
    { key:'env4-3', q:'Un écosystème comprend :',
      options:['Uniquement les animaux visibles','Les êtres vivants + leur milieu (biotope)','Les roches seules','Les humains seuls'], correct:1,
      hint:'Écosystème = biocénose (communauté vivante) + biotope (milieu physique).' },
    { key:'env4-4', q:'Les activités humaines peuvent modifier un écosystème par :',
      options:['Pollution, urbanisation, déforestation','Rien de mesurable','Seulement les pluies acides','La rotation de la Terre'], correct:0,
      hint:'Actions humaines majeures : pollution, urbanisation, agriculture intensive, changement climatique.' },
    { key:'env4-5', q:'Les perturbateurs endocriniens sont des substances qui :',
      options:['Nourrissent les cellules','Imitent ou bloquent les hormones, perturbant le système hormonal','Protègent les hormones','Sont totalement sans danger'], correct:1,
      hint:'Perturbateurs endocriniens (pesticides, plastiques, etc.) : effets sur la reproduction, la croissance, le cancer.' },
  ],
  },
  PICK: {
  reproduction: 3, cycle: 3, contraception: 3, plaques: 3, seismes: 3,
  volcans: 3, reproVeg: 3, biodiversite: 3, nutrition: 4, environnement: 2,
  },
  PLANS: {
    reproduction: {
      'non-acquis': ['Revoir le schéma légendé des appareils reproducteurs (masculin et féminin)', 'Mémoriser les organes : testicules, ovaires, utérus, trompes, pénis, vagin', 'Rôle des hormones : testostérone, œstrogènes, progestérone'],
      'fragile':    ['Distinguer caractères sexuels primaires vs secondaires', 'Chronologie de la puberté']
    },
    cycle: {
      'non-acquis': ['Frise du cycle menstruel sur 28 jours avec ovulation au J14', 'Définir : menstruations, ovulation, fécondation, nidation', 'Localiser la fécondation (dans une trompe) et la nidation (utérus)'],
      'fragile':    ['Comprendre la coordination hormones / ovaires / utérus', 'Durée de vie des spermatozoïdes (5j) et ovule (24h) → période féconde']
    },
    contraception: {
      'non-acquis': ['PRIORITÉ : apprendre que seul le préservatif protège des IST', 'Citer 3-4 IST : VIH, chlamydia, hépatite B, HPV', 'Retenir les méthodes principales : préservatif, pilule, stérilet (DIU)'],
      'fragile':    ['Comprendre mode d\'action de la pilule (blocage ovulation)', 'Savoir où se faire dépister (CeGIDD, planning familial)']
    },
    plaques: {
      'non-acquis': ['Mémoriser : la lithosphère est découpée en plaques qui bougent', 'Vitesse ~ quelques cm/an', 'Limites de plaques : dorsales (divergence) et subduction (convergence)'],
      'fragile':    ['Savoir situer sur un planisphère les grandes plaques et les zones sismiques/volcaniques']
    },
    seismes: {
      'non-acquis': ['Distinguer : foyer (profondeur) et épicentre (surface)', 'Cause : rupture brutale des roches → ondes sismiques', 'Différence magnitude (Richter) / intensité (Mercalli)'],
      'fragile':    ['Mesures de prévention : normes parasismiques, plans d\'évacuation', 'Notion de risque = aléa × vulnérabilité']
    },
    volcans: {
      'non-acquis': ['Effusif (lave fluide, coulées) vs explosif (nuées ardentes, forte explosion)', 'Magma → lave + gaz + projections solides', 'Volcans liés aux limites de plaques (zones de subduction surtout)'],
      'fragile':    ['Exemples : Piton de la Fournaise (effusif), Vésuve / Montagne Pelée (explosif)']
    },
    reproVeg: {
      'non-acquis': ['Schéma d\'une fleur : pétales, sépales, étamines (♂), pistil (♀)', 'Pollinisation : vent, insectes → fécondation', 'Ovule → graine ; ovaire → fruit'],
      'fragile':    ['Reproduction asexuée : bouturage, marcottage, stolon (clones)']
    },
    biodiversite: {
      'non-acquis': ['Biodiversité = diversité des espèces + gènes + écosystèmes', 'Fossiles = preuves de l\'évolution', 'Notion d\'ancêtre commun'],
      'fragile':    ['Impact des activités humaines sur la biodiversité', 'Introduction à la sélection naturelle (Darwin)']
    },
    nutrition: {
      'non-acquis': ['Respiration : O₂ entre, CO₂ sort (échanges dans les alvéoles)', 'Digestion → nutriments → sang → cellules', 'Cœur = pompe ; sang = transport des nutriments et gaz'],
      'fragile':    ['Respiration cellulaire dans les mitochondries : nutriments + O₂ → énergie + CO₂', 'Trajet du sang : cœur → artères → capillaires → veines → cœur']
    },
    environnement: {
      'non-acquis': ['Hygiène de vie : alimentation variée, sommeil, activité physique', 'Dangers du tabac et de l\'alcool', 'Écosystème = êtres vivants + milieu'],
      'fragile':    ['Actions humaines qui perturbent les écosystèmes (pollution, déforestation, climat)']
    },
  },
};
