// Source éditable — quiz svt-6. Régénéré automatiquement dans index.html via build.sh.
window.ALL_QUIZZES['svt-6'] = {
  SEARCH_SITES: 'site:fr.khanacademy.org OR site:lumni.fr OR site:planet-vie.ens.fr',
  YT_SUFFIX: 'svt 6eme college',
  SUMMER_TOPIC: 'SVT',
  SUBJECT: { id:'svt-6', name:'Sciences de la Vie et de la Terre', short:'SVT', level:'Fin de 6ème', mark:'🌿', tagline:'Évaluation diagnostique' },
  DOMAINS: {
    vivant:      { id:'vivant',      name:'Caractéristiques du vivant',       short:'Vivant',     coef:3, color:'#15803d', icon:'✦', search:'caracteristiques du vivant 6eme' },
    classification:{id:'classification',name:'Classification des êtres vivants', short:'Classif.', coef:3, color:'#166a39', icon:'≡', search:'classification des etres vivants 6eme' },
    peuplements: { id:'peuplements', name:'Peuplement des milieux',           short:'Peuplement', coef:2, color:'#059669', icon:'☘', search:'peuplement milieux saisons 6eme' },
    respiration: { id:'respiration', name:'Respiration des êtres vivants',    short:'Respiration',coef:2, color:'#b91c1c', icon:'O₂',search:'respiration etres vivants 6eme' },
    alimentation:{ id:'alimentation',name:'Besoins alimentaires',             short:'Alimentation',coef:3, color:'#be185d', icon:'♥', search:'alimentation besoins 6eme' },
    reproduction:{ id:'reproduction',name:'Reproduction & cycle de vie',      short:'Reproduction',coef:2, color:'#7c3aed', icon:'○', search:'reproduction animaux plantes 6eme' },
    sol:         { id:'sol',         name:'Sol & biodiversité',               short:'Sol',        coef:2, color:'#7c2d12', icon:'⨯', search:'sol biodiversite 6eme' },
    hygiene:     { id:'hygiene',     name:'Hygiène & santé',                  short:'Santé',      coef:2, color:'#c2410c', icon:'☘', search:'hygiene sante 6eme' },
  },
  RESOURCES: [
    { label:'Lumni — SVT 6ème',      author:'France TV éducation',    url:'https://www.lumni.fr/college/sixieme/svt' },
    { label:'Khan Academy — Biologie',author:'Cours + exos',           url:'https://fr.khanacademy.org/science/ms-biology' },
    { label:'La main à la pâte',     author:'Fondation sciences cycle 3', url:'https://fondation-lamap.org/' },
    { label:'SVT à l\'école',        author:'YouTube (cours de collège)', url:'https://www.youtube.com/results?search_query=svt+6eme+cours' },
  ],
  POOL: {
    vivant: [
      { key:'viv-1', q:'Un être vivant :', options:['Ne bouge jamais','Naît, grandit, se reproduit, meurt','Est forcément un animal','Est toujours visible à l\'œil nu'], correct:1, hint:'Cycle commun : naissance → croissance → reproduction → mort.' },
      { key:'viv-2', q:'Tous les êtres vivants sont constitués de :', options:['Roches','Cellules','Plastique','Eau uniquement'], correct:1, hint:'Cellule = unité de base du vivant (animale, végétale, bactérienne).' },
      { key:'viv-3', q:'Un rocher est-il vivant ?', options:['Oui','Non (il ne se reproduit pas, ne respire pas, n\'a pas de cellules)','Parfois','On ne sait pas'], correct:1, hint:'Le rocher fait partie du minéral (non vivant).' },
      { key:'viv-4', q:'La cellule végétale se différencie de la cellule animale par :', options:['L\'absence de noyau','La présence d\'une paroi, de chloroplastes et d\'une grande vacuole','Des os','Des muscles'], correct:1, hint:'Paroi cellulosique + chloroplastes + vacuole centrale = caractères propres à la cellule végétale.' },
      { key:'viv-5', q:'Un virus est-il un être vivant comme une bactérie ?', options:['Oui, ils sont identiques','Non : le virus ne peut pas se reproduire sans une cellule hôte','Oui uniquement dans l\'air','Oui, car il a des cellules'], correct:1, hint:'Les virus ne sont pas des cellules et ne se reproduisent que dans un hôte. Leur statut est débattu.' },
      { key:'viv-6', q:'Parmi ces choses, laquelle est vivante ?', options:['Le soleil','Un champignon','Un cristal de sel','Un volcan'], correct:1, hint:'Les champignons sont vivants (règne Fungi).' },
      { key:'viv-7', q:'Les bactéries sont des êtres vivants :', options:['Unicellulaires (une seule cellule)','Pluricellulaires comme les humains','Sans aucune cellule','Minéraux'], correct:0, hint:'Bactéries = organismes unicellulaires procaryotes (sans noyau distinct).' },
      { key:'viv-8', q:'Un champignon appartient au règne :', options:['Animal','Végétal','Fungi (champignons)','Minéral'], correct:2, hint:'Ni animal ni végétal : les champignons forment leur propre règne (Fungi).' },
      { key:'viv-9', q:'Quel est le point commun entre un humain, une rose et une bactérie ?', options:['Ils ont tous des poumons','Ils sont tous constitués d\'au moins une cellule','Ils vivent tous dans l\'eau','Ils se déplacent tous'], correct:1, hint:'La cellule est l\'unité structurale et fonctionnelle commune à tous les êtres vivants.' },
      { key:'viv-10', q:'La cellule eucaryote se distingue de la cellule procaryote par :', options:['L\'absence de cytoplasme','La présence d\'un vrai noyau délimité par une membrane','L\'absence d\'ADN','Sa taille toujours plus petite'], correct:1, hint:'Eucaryotes (animaux, plantes, champignons) ont un noyau délimité par une membrane. Les bactéries sont procaryotes.' },
      { key:'viv-11', q:'Pourquoi une plante est-elle aussi un être vivant ?', options:['Elle peut courir','Elle naît, grandit, se reproduit et meurt comme tous les vivants','Elle parle','Elle est chaude'], correct:1, hint:'Les plantes sont vivantes : elles se développent, respirent, se reproduisent — même si elles ne bougent pas.' },
      { key:'viv-12', q:'La nutrition est une fonction du vivant qui permet :', options:['Uniquement de grossir','D\'obtenir la matière et l\'énergie nécessaires au fonctionnement et à la croissance','De se déplacer plus vite','De ne pas avoir besoin d\'eau'], correct:1, hint:'Nutrition = s\'alimenter pour obtenir matière (construction cellulaire) et énergie (activité cellulaire). Commune à tous les vivants.' },
    ],
    classification: [
      { key:'cla-1', q:'On classe les êtres vivants selon :', options:['Leur couleur','Leurs caractères communs hérités','Leur taille','Leur nom de famille'], correct:1, hint:'Classification basée sur les caractères partagés (et leur origine évolutive).' },
      { key:'cla-2', q:'Un mammifère :', options:['Pond des œufs','Allaite ses petits et a des poils','Respire dans l\'eau','A des plumes'], correct:1, hint:'Mammifères : allaitent, ont des poils, respirent avec des poumons.' },
      { key:'cla-3', q:'Les oiseaux ont :', options:['Des plumes, un bec et pondent des œufs','De la fourrure','Des écailles','Des branchies'], correct:0, hint:'Plumes + bec + œufs = caractéristiques des oiseaux.' },
      { key:'cla-4', q:'Les insectes ont :', options:['2 pattes','4 pattes','6 pattes','8 pattes'], correct:2, hint:'Insectes : 6 pattes + 3 parties (tête, thorax, abdomen) + souvent des ailes.' },
      { key:'cla-5', q:'Les arachnides (araignées, scorpions) ont :', options:['6 pattes','8 pattes','4 pattes','10 pattes'], correct:1, hint:'Arachnides = 8 pattes. Différence clé avec les insectes (6 pattes).' },
      { key:'cla-6', q:'Une baleine est :', options:['Un poisson','Un mammifère (respire par des poumons, allaite)','Un amphibien','Un reptile'], correct:1, hint:'Vit dans l\'eau mais c\'est un mammifère : elle respire à la surface avec ses poumons.' },
      { key:'cla-7', q:'Les reptiles (lézards, serpents) ont :', options:['Des plumes','Des poils','Des écailles','Des branchies'], correct:2, hint:'Reptiles : corps couvert d\'écailles, sang froid (ectothermes).' },
      { key:'cla-8', q:'Les amphibiens (grenouilles, tritons) :', options:['Vivent uniquement dans l\'eau','Vivent sur terre et dans l\'eau, respirent par poumons et peau','N\'existent pas en France','Ont des plumes'], correct:1, hint:'Amphibiens = double vie : larve aquatique (têtard) puis adulte terrestre/aquatique.' },
      { key:'cla-9', q:'Dans la classification du vivant, un "vertébré" est un animal qui :', options:['Vole forcément','Possède une colonne vertébrale','Vit dans l\'eau','A 4 membres'], correct:1, hint:'Vertébrés : colonne vertébrale (poissons, amphibiens, reptiles, oiseaux, mammifères).' },
      { key:'cla-10', q:'Un végétal à fleurs est dit :', options:['Cryptogame','Angiosperme','Gymnosperme','Champignon'], correct:1, hint:'Angiosperme = plante à fleurs et à fruits renfermant les graines.' },
      { key:'cla-11', q:'Les groupes emboîtés signifient que :', options:['Chaque groupe a le même nombre d\'espèces','Un groupe peut en contenir un autre plus petit partageant plus de caractères','Tous les animaux sont dans un seul groupe','Les groupes ne se recoupent jamais'], correct:1, hint:'Ex : tous les mammifères sont des vertébrés, mais tous les vertébrés ne sont pas des mammifères.' },
      { key:'cla-12', q:'La chauve-souris est :', options:['Un oiseau','Un mammifère volant','Un insecte','Un reptile'], correct:1, hint:'Seul mammifère qui vole vraiment. Allaite ses petits, pas de plumes.' },
      { key:'cla-13', q:'La grenouille est un :', options:['Mammifère','Reptile','Poisson','Amphibien'], correct:3, hint:'Grenouille = amphibien (vie jeune dans l\'eau, adulte terrestre/aquatique).' },
      { key:'cla-14', q:'La baleine est :', options:['Un poisson géant','Un mammifère marin','Un reptile aquatique','Un oiseau sans ailes'], correct:1, hint:'La baleine respire avec des poumons (remonte à la surface), allaite ses petits et est à sang chaud : c\'est un mammifère, même si elle vit dans l\'eau.' },
      { key:'cla-15', q:'L\'araignée possède :', options:['6 pattes (elle est un insecte)','8 pattes (elle est un arachnide)','4 pattes (elle est un mammifère)','Aucune patte'], correct:1, hint:'Arachnide = 8 pattes (araignée, scorpion). Insecte = 6 pattes (mouche, fourmi, abeille).' },
    ],
    peuplements: [
      { key:'peu-1', q:'En hiver, beaucoup d\'arbres :', options:['Perdent leurs feuilles','Produisent des fleurs','Meurent définitivement','Rapetissent'], correct:0, hint:'Les caduques (chêne, hêtre, érable) perdent leurs feuilles en hiver.' },
      { key:'peu-2', q:'Certains animaux passent l\'hiver en :', options:['Hibernation (ralentissant leur activité)','Nageant plus vite','Chantant sous la neige','Volant en cercle'], correct:0, hint:'Hibernation : marmotte, ours, loir… Métabolisme très ralenti.' },
      { key:'peu-3', q:'La migration, c\'est :', options:['Rester au même endroit toute l\'année','Se déplacer de région selon les saisons','Se reproduire au printemps','Hiberner sous terre'], correct:1, hint:'Oiseaux migrateurs : hirondelles, cigognes… vont vers le Sud l\'hiver.' },
      { key:'peu-4', q:'Un milieu de vie :', options:['Est toujours sec','Contient des conditions (T°, humidité, lumière) et des êtres vivants','Est toujours vide','N\'existe que dans les forêts'], correct:1, hint:'Milieu = conditions physiques + communauté d\'êtres vivants qui y vivent.' },
      { key:'peu-5', q:'Les hirondelles quittent la France en :', options:['Printemps','Été','Automne','Jamais'], correct:2, hint:'Elles migrent vers l\'Afrique subsaharienne à l\'automne, puis reviennent au printemps.' },
      { key:'peu-6', q:'Dans un étang en hiver :', options:['Il n\'y a plus du tout de vie','La vie ralentit sous la glace','Tout meurt rapidement','Les poissons deviennent des œufs'], correct:1, hint:'Sous la glace, la température reste autour de 4 °C. Poissons et plantes ralentissent mais survivent.' },
      { key:'peu-7', q:'Le printemps entraîne chez les plantes :', options:['La perte des feuilles','La reprise de la croissance et la floraison','L\'hibernation','Aucun changement visible'], correct:1, hint:'Hausse des températures + allongement des jours → débourrement et floraison.' },
      { key:'peu-8', q:'Un animal adapté au froid possède souvent :', options:['Un pelage très fin','Un pelage épais ou une couche de graisse isolante','Des branchies supplémentaires','Des plumes de couleur vive'], correct:1, hint:'Isolation thermique : fourrure épaisse (ours polaire), graisse sous-cutanée (phoque, baleine).' },
      { key:'peu-9', q:'La notion de peuplement désigne :', options:['Un seul individu isolé','L\'ensemble des êtres vivants d\'un milieu donné','La végétation uniquement','La température d\'un lieu'], correct:1, hint:'Peuplement = biocénose : tous les organismes vivants (animaux, végétaux, microbes) d\'un milieu.' },
      { key:'peu-10', q:'Quelle stratégie les coccinelles utilisent-elles pour survivre à l\'hiver ?', options:['Elles migrent vers l\'Afrique','Elles se regroupent et ralentissent leur activité (diapause)','Elles pondent massivement en automne','Elles meurent toutes et renaissent au printemps'], correct:1, hint:'Les coccinelles hivernent regroupées sous l\'écorce ou dans la litière — diapause.' },
      { key:'peu-11', q:'Les plantes à feuilles persistantes (conifères, houx…) :', options:['Perdent aussi leurs feuilles en hiver','Gardent leurs feuilles en hiver car elles sont protégées contre le froid','N\'existent pas en France','Se comportent exactement comme les caduques'], correct:1, hint:'Feuilles persistantes : fines (aiguilles), cireuses, résistantes au gel → pas de chute saisonnière obligatoire.' },
      { key:'peu-12', q:'Le renard roux en France, l\'hiver :', options:['Hiberne complètement','Reste actif toute l\'année et adapte son régime alimentaire','Migre vers l\'Afrique','Perd toute sa fourrure'], correct:1, hint:'Le renard ne hiberne pas : il reste actif, mange ce qu\'il trouve (baies, rongeurs, déchets). Son pelage s\'épaissit.' },
    ],
    respiration: [
      { key:'res-1', q:'Respirer, c\'est :', options:['Manger des aliments','Prendre du dioxygène (O₂) et rejeter du dioxyde de carbone (CO₂)','Faire pousser les feuilles','Boire de l\'eau'], correct:1, hint:'Respiration : absorber O₂ et rejeter CO₂. Vrai pour tous les êtres vivants.' },
      { key:'res-2', q:'Les plantes respirent-elles ?', options:['Non, elles ne le font pas','Oui, elles respirent 24h/24 (O₂ consommé, CO₂ rejeté)','Non, elles ne font que de la photosynthèse','Seulement la nuit'], correct:1, hint:'Les plantes respirent ET font la photosynthèse. Elles respirent 24h/24.' },
      { key:'res-3', q:'Les poissons respirent :', options:['L\'air au-dessus de l\'eau','Le dioxygène dissous dans l\'eau, via leurs branchies','Ils n\'ont pas besoin de respirer','Ils absorbent du sel'], correct:1, hint:'Branchies extraient l\'O₂ présent dans l\'eau.' },
      { key:'res-4', q:'Les insectes respirent par :', options:['Des poumons','Des trachées (petits tubes débouchant sur l\'abdomen)','Des branchies','Uniquement par la peau'], correct:1, hint:'Insectes : trachées ouvertes par des stigmates sur l\'abdomen.' },
      { key:'res-5', q:'Pourquoi un poisson meurt hors de l\'eau ?', options:['Il a trop chaud au soleil','Ses branchies se dessèchent et ne peuvent plus extraire l\'O₂ de l\'air','Il n\'y a pas de nourriture à l\'air','La lumière lui est fatale'], correct:1, hint:'Les branchies doivent rester humides pour fonctionner. Hors de l\'eau, elles collent et s\'assèchent.' },
      { key:'res-6', q:'Un ver de terre respire :', options:['Par des poumons miniatures','Par sa peau humide (respiration cutanée)','Par des branchies','Par des trachées'], correct:1, hint:'Les vers de terre respirent par diffusion cutanée : leur peau doit rester humide.' },
      { key:'res-7', q:'Les grenouilles adultes respirent :', options:['Uniquement par des branchies','Par des poumons et par la peau','Uniquement par la peau','Elles ne respirent pas'], correct:1, hint:'Grenouille adulte : poumons + respiration cutanée (peau perméable aux gaz).' },
      { key:'res-8', q:'Les baleines respirent :', options:['Par des branchies comme les poissons','Par des poumons (elles remontent à la surface)','Par leur peau','Elles n\'ont pas besoin de dioxygène'], correct:1, hint:'Mammifères marins = poumons. Les baleines doivent remonter respirer régulièrement.' },
      { key:'res-9', q:'Photosynthèse et respiration chez les plantes :', options:['Sont la même chose','Sont différentes : photosynthèse consomme CO₂ / respiration consomme O₂','N\'existent pas toutes les deux','Se produisent uniquement en automne'], correct:1, hint:'Photosynthèse (jour) : CO₂ → O₂. Respiration (24h/24) : O₂ → CO₂. Les deux ont lieu en même temps le jour.' },
      { key:'res-10', q:'Quel gaz est rejeté par tous les êtres vivants lors de la respiration ?', options:['O₂ (dioxygène)','CO₂ (dioxyde de carbone)','N₂ (azote)','H₂ (hydrogène)'], correct:1, hint:'La respiration consomme O₂ et produit CO₂ comme déchet gazeux — chez tous les vivants.' },
      { key:'res-11', q:'Comment les dauphins et les baleines respirent-ils ?', options:['Par des branchies comme les poissons','Ils remontent régulièrement à la surface pour respirer avec leurs poumons','Par leur peau','Ils n\'ont pas besoin de dioxygène'], correct:1, hint:'Mammifères marins = poumons. Ils plongent mais doivent revenir en surface pour inspirer. Leur évent (narine) est au sommet du crâne.' },
      { key:'res-12', q:'Si l\'on met un bocal hermétique avec une plante verte et du CO₂ en plein soleil, que se passe-t-il ?', options:['Rien du tout','La plante consomme le CO₂ (photosynthèse) et produit de l\'O₂','La plante produit plus de CO₂','Le CO₂ se transforme en azote'], correct:1, hint:'Photosynthèse le jour : CO₂ + H₂O + lumière → glucides + O₂. La plante "mange" le CO₂ et produit de l\'O₂.' },
    ],
    alimentation: [
      { key:'ali-1', q:'Les plantes se nourrissent :', options:['En mangeant d\'autres plantes','En fabriquant leur matière organique grâce à la lumière (photosynthèse)','Comme les animaux','Uniquement de sels du sol'], correct:1, hint:'Photosynthèse : H₂O + CO₂ + lumière → matière organique + O₂. Autotrophes.' },
      { key:'ali-2', q:'Un animal herbivore mange :', options:['De la viande','Des végétaux uniquement','Des insectes et de la viande','Des pierres'], correct:1, hint:'Herbivore : végétaux. Carnivore : viande. Omnivore : les deux.' },
      { key:'ali-3', q:'Dans une chaîne alimentaire, la flèche signifie :', options:['Est mangé par','Mange','Fuit','Est à côté de'], correct:0, hint:'Herbe → lapin → renard : le sens indique "est mangé par".' },
      { key:'ali-4', q:'Les producteurs primaires sont :', options:['Les carnivores','Les plantes vertes (et autres photosynthétiques)','Les décomposeurs','Les bactéries uniquement'], correct:1, hint:'Producteurs primaires fabriquent la matière organique à partir du minéral (photosynthèse).' },
      { key:'ali-5', q:'Dans la chaîne : herbe → lapin → renard, le lapin est :', options:['Producteur','Consommateur primaire (herbivore)','Consommateur secondaire','Décomposeur'], correct:1, hint:'Consommateur primaire = mange le producteur (plante).' },
      { key:'ali-6', q:'Un animal omnivore mange :', options:['Uniquement des végétaux','Uniquement de la viande','Des végétaux et de la viande','Des minéraux'], correct:2, hint:'Omnivore : régime mixte végétal + animal. Ex. : humain, cochon, ours.' },
      { key:'ali-7', q:'Le renard dans la chaîne herbe → lapin → renard est :', options:['Producteur','Consommateur primaire','Consommateur secondaire (carnivore)','Décomposeur'], correct:2, hint:'Le renard mange le lapin (consommateur primaire) → il est consommateur secondaire.' },
      { key:'ali-8', q:'La photosynthèse a lieu :', options:['La nuit uniquement','Dans les racines','Dans les feuilles (parties vertes), à la lumière','Dans les fleurs uniquement'], correct:2, hint:'Feuilles : chlorophylle + lumière → matière organique + O₂.' },
      { key:'ali-9', q:'Un écosystème sans décomposeurs :', options:['Fonctionnerait mieux','S\'accumulerait en matière organique morte non recyclée','Resterait identique','Produirait plus d\'O₂'], correct:1, hint:'Les décomposeurs recyclent la matière organique morte en sels minéraux réutilisables par les plantes.' },
      { key:'ali-10', q:'Qui décompose les feuilles mortes dans le sol ?', options:['Personne : elles disparaissent seules','Des bactéries et champignons (décomposeurs)','Les vers de terre uniquement','Le soleil'], correct:1, hint:'Décomposeurs : bactéries, champignons, vers, insectes → recyclent la matière organique.' },
      { key:'ali-11', q:'Un réseau alimentaire est :', options:['Une seule chaîne alimentaire','L\'ensemble des chaînes alimentaires interconnectées d\'un milieu','Un classement des espèces par taille','Les relations entre les végétaux uniquement'], correct:1, hint:'Réseau trophique = superposition de nombreuses chaînes alimentaires. Plus stable qu\'une chaîne unique (si une espèce disparaît, une autre la remplace).' },
      { key:'ali-12', q:'Les bactéries et champignons décomposeurs jouent quel rôle dans le cycle de la matière ?', options:['Ils bloquent le recyclage des éléments','Ils transforment la matière organique morte en sels minéraux réutilisables par les plantes','Ils produisent de l\'O₂ comme les plantes','Ils stockent le carbone définitivement'], correct:1, hint:'Sans décomposeurs, les cadavres et feuilles mortes s\'accumuleraient. Ils "ferment" le cycle : matière organique → minéral → plantes.' },
    ],
    reproduction: [
      { key:'rep-1', q:'La reproduction sexuée nécessite :', options:['Un seul individu','Deux individus (mâle et femelle) qui produisent des cellules reproductrices','Trois individus au minimum','Aucun individu'], correct:1, hint:'Sexuée : gamètes mâle + gamète femelle → nouvel individu.' },
      { key:'rep-2', q:'Chez les plantes à fleurs, la fleur sert à :', options:['Sentir bon uniquement','Se reproduire (organe reproducteur)','Fabriquer des feuilles','À rien'], correct:1, hint:'Fleur = organe reproducteur : étamines (♂) + pistil (♀).' },
      { key:'rep-3', q:'La grenouille pond :', options:['Des petits vivants','Des œufs dans l\'eau','Des graines','Des cellules isolées'], correct:1, hint:'Ovipare : les grenouilles pondent dans l\'eau, les têtards y naissent.' },
      { key:'rep-4', q:'Une bouture, c\'est :', options:['Une graine','Un morceau de tige qui donne naissance à une nouvelle plante','Une fleur coupée','Un fruit pourri'], correct:1, hint:'Bouture = multiplication asexuée. La nouvelle plante est identique à la mère.' },
      { key:'rep-5', q:'La reproduction asexuée produit :', options:['Des individus différents du parent','Des individus identiques au parent (clones)','Uniquement des graines','Toujours deux parents'], correct:1, hint:'Asexuée = sans gamètes → clones. Bouturage, stolons, division.' },
      { key:'rep-6', q:'La pollinisation chez les plantes à fleurs :', options:['Est totalement inutile','Permet le transport du pollen vers le pistil pour la fécondation','Produit des feuilles','Est réalisée uniquement par le vent'], correct:1, hint:'Pollinisation : vent, insectes, oiseaux transportent le pollen. Précède la fécondation.' },
      { key:'rep-7', q:'Chez les mammifères, le développement de l\'embryon se fait :', options:['Dans un œuf extérieur','Dans l\'utérus de la mère (viviparité)','Dans l\'eau','Sur une feuille'], correct:1, hint:'Mammifères vivipares : l\'embryon se développe dans l\'utérus, nourri par le placenta.' },
      { key:'rep-8', q:'Après la pollinisation, l\'ovule fécondé devient :', options:['Une feuille','Une graine (puis le pistil devient le fruit)','Une racine','Une tige'], correct:1, hint:'Ovule fécondé → graine. La paroi du pistil forme le fruit qui protège la graine.' },
      { key:'rep-9', q:'Les grenouilles se retrouvent près des mares au printemps pour :', options:['Se désaltérer uniquement','Se reproduire : pondre des œufs dans l\'eau','Hiberner','Chasser les poissons'], correct:1, hint:'Printemps : saison de reproduction des grenouilles. Les œufs (frai) donnent des larves aquatiques (têtards).' },
    ],
    sol: [
      { key:'sol-1', q:'Le sol est formé :', options:['Uniquement de roches','De matière minérale (roches) + matière organique (débris) + êtres vivants','Que de sable','Que d\'eau'], correct:1, hint:'Sol = minéral + matière organique + biodiversité (vers, bactéries, champignons).' },
      { key:'sol-2', q:'Les vers de terre :', options:['Sont nuisibles au jardin','Aèrent le sol et le fertilisent','Mangent les racines','Tuent les plantes'], correct:1, hint:'Les vers brassent la terre, améliorent l\'aération et produisent un humus fertile.' },
      { key:'sol-3', q:'L\'humus est :', options:['De la roche','De la matière organique issue de la décomposition des débris végétaux et animaux','De l\'eau souterraine','Un minéral pur'], correct:1, hint:'Humus = matière organique humifiée, essentielle à la fertilité du sol.' },
      { key:'sol-4', q:'Les champignons du sol participent :', options:['À la décomposition de la matière organique','À la production d\'O₂ en surface','À la fabrication de roche','À l\'irrigation du sol'], correct:0, hint:'Champignons = décomposeurs clés du sol : recyclent la litière (feuilles mortes, bois mort).' },
      { key:'sol-5', q:'Un sol imperméabilisé (béton, bitume) :', options:['Reste aussi fertile','Perd sa biodiversité et n\'absorbe plus la pluie','Devient plus fertile','Favorise les vers de terre'], correct:1, hint:'L\'imperméabilisation coupe le sol de la lumière et de l\'eau → perte de biodiversité et risques d\'inondations.' },
      { key:'sol-6', q:'Combien environ d\'organismes dans 1 g de sol ?', options:['Quelques dizaines','Des millions de bactéries et microorganismes','Quelques centaines d\'insectes','Aucun être vivant'], correct:1, hint:'1 g de sol contient des milliards de microorganismes. Le sol est l\'un des écosystèmes les plus denses.' },
      { key:'sol-7', q:'Quel rôle jouent les décomposeurs dans le cycle de la matière ?', options:['Ils bloquent le recyclage','Ils transforment la matière organique morte en sels minéraux réutilisables','Ils produisent de l\'O₂','Ils créent de nouvelles espèces'], correct:1, hint:'Sans décomposeurs, les feuilles mortes et cadavres s\'accumuleraient indéfiniment. Ils ferment le cycle.' },
      { key:'sol-8', q:'L\'érosion des sols en pente est aggravée par :', options:['La présence de végétaux','L\'absence de végétaux (racines ne retiennent plus la terre)','Des pluies légères','La présence de vers de terre'], correct:1, hint:'Les racines retiennent le sol. Sans couverture végétale, l\'eau emporte rapidement la couche fertile.' },
      { key:'sol-9', q:'Le sol met combien de temps à se former (1 cm) ?', options:['Quelques jours','Quelques années','Des centaines à des milliers d\'années','Une semaine'], correct:2, hint:'Formation du sol : processus lentissime (100 à 1000 ans/cm). C\'est pourquoi il faut préserver les sols fertiles.' },
    ],
    hygiene: [
      { key:'hyg-1', q:'Pour rester en bonne santé :', options:['Ne jamais se laver','Alimentation variée, activité physique, sommeil, hygiène corporelle','Ne pas dormir la nuit','Rester immobile toute la journée'], correct:1, hint:'Règles d\'hygiène de vie à connaître dès la 6ème.' },
      { key:'hyg-2', q:'Un microbe peut être :', options:['Toujours dangereux','Parfois utile (digestion, fermentation) ou pathogène selon l\'espèce','Toujours bénéfique','Toujours sans effet sur le corps'], correct:1, hint:'Microbes : bactéries, virus, champignons. Certains sont indispensables (flore intestinale), d\'autres rendent malade.' },
      { key:'hyg-3', q:'Se laver les mains permet :', options:['D\'enlever la couleur de la peau','De limiter la transmission des microbes','D\'augmenter sa force','Rien de particulier'], correct:1, hint:'Hygiène de base pour bloquer la propagation des infections.' },
      { key:'hyg-4', q:'Les antibiotiques sont efficaces contre :', options:['Les virus (grippe, rhume)','Les bactéries uniquement','La fatigue généralisée','Les allergies saisonnières'], correct:1, hint:'Antibiotiques = anti-BACTÉRIENS. INUTILES contre les virus (grippe, covid, rhume).' },
      { key:'hyg-5', q:'Un vaccin permet de :', options:['Guérir une maladie déjà installée','Préparer le système immunitaire à combattre un microbe spécifique','Remplacer les antibiotiques','Nourrir les cellules directement'], correct:1, hint:'Le vaccin entraîne les défenses immunitaires à reconnaître un pathogène sans tomber malade.' },
      { key:'hyg-6', q:'La carie dentaire est causée par :', options:['Trop de fluor dans l\'eau','Des bactéries qui attaquent l\'émail (favorisées par le sucre)','Un manque de calcium uniquement','Un virus'], correct:1, hint:'Bactéries + sucres → acides → destruction de l\'émail. Solution : brossage régulier.' },
      { key:'hyg-7', q:'L\'activité physique régulière :', options:['Est totalement inutile','Renforce les muscles, le cœur et le système immunitaire','Nuit à la santé sur le long terme','Est réservée aux sportifs de haut niveau'], correct:1, hint:'30 min d\'activité modérée par jour : bénéfices cardiovasculaires, osseux, mentaux.' },
      { key:'hyg-8', q:'Dormir 9-10 heures par nuit à l\'adolescence, c\'est :', options:['Trop et inutile','Pas assez pour le cerveau','À peu près le besoin recommandé','Dangereux pour la santé'], correct:2, hint:'Besoin ado : 8-10 h. Le sommeil aide mémoire, croissance, humeur.' },
      { key:'hyg-9', q:'La ceinture de sécurité en voiture est utile car :', options:['Elle est obligatoire mais inutile physiquement','Elle retient le corps lors d\'un choc et évite la projection (divise le risque de mort par 3 environ)','Elle remplace l\'airbag','Elle empêche uniquement les nausées'], correct:1, hint:'En cas de choc, sans ceinture, le corps continue à la vitesse initiale → projection. Avec ceinture, retenu par la sangle.' },
    ],
  },
  PICK: {
    vivant: 4, classification: 5, peuplements: 4, respiration: 4, alimentation: 4,
    reproduction: 3, sol: 3, hygiene: 3,
  },
  PLANS: {
    vivant: {
      'non-acquis': ['Caractéristiques communes : cellules, naissance, croissance, reproduction, mort', 'Distinguer vivant / minéral', 'Savoir donner des exemples variés'],
      'fragile':    ['Cellule animale vs végétale (paroi, chloroplastes)']
    },
    classification: {
      'non-acquis': ['Classer selon les caractères communs', 'Grands groupes : mammifères, oiseaux, poissons, reptiles, amphibiens, insectes', 'Groupes emboîtés : un groupe contient des sous-groupes'],
      'fragile':    ['Distinguer insectes et arachnides (6 vs 8 pattes)']
    },
    peuplements: {
      'non-acquis': ['Saisons → changements dans le peuplement', 'Stratégies : migration, hibernation, perte des feuilles', 'Notion de milieu de vie'],
      'fragile':    ['Effet des activités humaines sur le peuplement']
    },
    respiration: {
      'non-acquis': ['Tous les vivants respirent (y compris les plantes)', 'Respiration : O₂ entre, CO₂ sort', 'Modes : poumons, branchies, trachées (insectes)'],
      'fragile':    ['Différencier respiration et photosynthèse']
    },
    alimentation: {
      'non-acquis': ['Plantes = autotrophes (photosynthèse), animaux = hétérotrophes', 'Régimes : herbivore, carnivore, omnivore', 'Chaîne alimentaire : sens de la flèche'],
      'fragile':    ['Réseau trophique, producteurs/consommateurs']
    },
    reproduction: {
      'non-acquis': ['Sexuée : gamètes ♂ + ♀', 'Rôle de la fleur chez les plantes', 'Reproduction asexuée = clones'],
      'fragile':    ['Pollinisation et dispersion des graines']
    },
    sol: {
      'non-acquis': ['Composition du sol : minéral + organique + vivants', 'Rôle clé des vers de terre et décomposeurs', 'Biodiversité cachée'],
      'fragile':    ['Cycle de la matière dans le sol']
    },
    hygiene: {
      'non-acquis': ['Alimentation variée, sommeil, activité physique', 'Hygiène : se laver, brosser les dents', 'Microbes : pathogènes vs utiles'],
      'fragile':    ['Vaccination (prévention) ≠ antibiotique (traitement bactérien)']
    },
  },
};
