// Source éditable — quiz svt-4. Régénéré automatiquement dans index.html via build.sh.
window.ALL_QUIZZES['svt-4'] = {
  SEARCH_SITES: 'site:fr.khanacademy.org OR site:lumni.fr OR site:planet-vie.ens.fr',
  YT_SUFFIX: 'college svt',
  SUMMER_TOPIC: 'SVT',
  SUBJECT: {
    id: 'svt-4',
    name: 'Sciences de la Vie et de la Terre',
    short: 'SVT',
    level: 'Fin de 4ème',
    mark: '🌿',
    tagline: 'Évaluation diagnostique',
  },
  DOMAINS: {
  reproduction: { id:'reproduction', name:'Reproduction humaine & puberté',        short:'Reproduction', coef:3, color:'#be185d', icon:'♂♀', search:'reproduction humaine puberte 4eme' },
  cycle:        { id:'cycle',        name:'Cycle menstruel & fécondation',         short:'Cycle',        coef:3, color:'#db2777', icon:'○',  search:'cycle menstruel fecondation 4eme' },
  contraception:{ id:'contraception',name:'Contraception & IST',                   short:'Contraception',coef:3, color:'#a21caf', icon:'⊘',  search:'contraception ist sida 4eme' },
  plaques:      { id:'plaques',      name:'Tectonique des plaques',                short:'Plaques',      coef:3, color:'#7c2d12', icon:'≡',  search:'tectonique plaques 4eme' },
  seismes:      { id:'seismes',      name:'Séismes & risques',                     short:'Séismes',      coef:3, color:'#a01b34', icon:'⚠',  search:'seismes ondes sismiques 4eme' },
  volcans:      { id:'volcans',      name:'Volcanisme',                            short:'Volcans',      coef:3, color:'#c2410c', icon:'▲',  search:'volcanisme eruption magma 4eme' },
  reproVeg:     { id:'reproVeg',     name:'Reproduction des végétaux',             short:'Plantes',      coef:2, color:'#15803d', icon:'✿',  search:'reproduction plantes pollinisation 4eme' },
  biodiversite: { id:'biodiversite', name:'Biodiversité & évolution',              short:'Biodiversité', coef:2, color:'#166a39', icon:'♾',  search:'biodiversite evolution 4eme' },
  nutrition:    { id:'nutrition',    name:'Nutrition, respiration, circulation',   short:'Corps humain', coef:3, color:'#b91c1c', icon:'♥',  search:'nutrition respiration circulation 4eme' },
  environnement:{ id:'environnement',name:'Environnement & santé',                 short:'Environnement',coef:2, color:'#059669', icon:'☘',  search:'environnement sante hygiene 4eme' },
  },
  RESOURCES: [
  { label:'Khan Academy — Biologie', author:'Cours + exos gratuits',          url:'https://fr.khanacademy.org/science/ms-biology' },
  { label:'Lumni — SVT 4ème',        author:'France TV éducation',            url:'https://www.lumni.fr/college/quatrieme/svt' },
  { label:'Planet-Vie',              author:'ENS — ressources SVT',           url:'https://planet-vie.ens.fr/' },
  { label:'SVT à l\'école',          author:'YouTube (cours de collège)',     url:'https://www.youtube.com/results?search_query=svt+4eme+cours' },
  ],
  POOL: {
  reproduction: [
    { key:'rep-1', q:'La puberté correspond au moment où :',
      options:['Le corps cesse de grandir','Le corps devient capable de se reproduire','On entre en primaire','On arrête la croissance osseuse'], correct:1,
      hint:'Puberté = passage à la maturité sexuelle. Les appareils reproducteurs deviennent fonctionnels.' },
    { key:'rep-2', q:'Les cellules reproductrices masculines sont :',
      options:['Les ovules','Les spermatozoïdes','Les neurones','Les globules rouges'], correct:1,
      hint:'Spermatozoïdes (produits par les testicules). Les femmes produisent des ovules (ovaires).' },
    { key:'rep-3', q:'Les testicules produisent :',
      options:['Des ovules','Du sang','Des spermatozoïdes et la testostérone','Des hormones uniquement'], correct:2,
      hint:'Les testicules sont à la fois producteurs de spermatozoïdes et de l\'hormone testostérone.' },
    { key:'rep-4', q:'Les ovaires libèrent :',
      options:['Un ovule par cycle','Des spermatozoïdes','Du sang','De la salive'], correct:0,
      hint:'Environ 1 ovule libéré par cycle (ovulation), vers le 14ᵉ jour.' },
    { key:'rep-5', q:'Les caractères sexuels secondaires apparaissent :',
      options:['À la naissance','À la puberté','À 20 ans','Jamais'], correct:1,
      hint:'Caractères secondaires (pilosité, voix, poitrine, musculature) = à la puberté sous l\'effet des hormones.' },
    { key:'rep-6', q:'Les hormones responsables de la puberté sont produites par :',
      options:['Le cerveau et les gonades (ovaires/testicules)','Le foie','Les poumons','La peau uniquement'], correct:0,
      hint:'L\'hypophyse (cerveau) commande les ovaires/testicules qui produisent œstrogènes/testostérone.' },
  ],

  cycle: [
    { key:'cyc-1', q:'La durée moyenne d\'un cycle menstruel est d\'environ :',
      options:['7 jours','14 jours','28 jours','365 jours'], correct:2,
      hint:'Cycle menstruel moyen = 28 jours, mais il peut varier de 21 à 35 jours selon les femmes.' },
    { key:'cyc-2', q:'L\'ovulation a lieu en général :',
      options:['Au 1er jour du cycle','Vers le 14ᵉ jour du cycle','Au 28ᵉ jour','Jamais'], correct:1,
      hint:'Ovulation vers le milieu du cycle (jour 14 pour un cycle de 28 jours).' },
    { key:'cyc-3', q:'La fécondation correspond à :',
      options:['La rencontre d\'un ovule et d\'un spermatozoïde','La naissance','L\'ovulation','Les règles'], correct:0,
      hint:'Fécondation = fusion du noyau de l\'ovule et d\'un spermatozoïde → cellule-œuf.' },
    { key:'cyc-4', q:'Les règles correspondent à :',
      options:['La fécondation','L\'élimination de la paroi de l\'utérus','La naissance','La puberté'], correct:1,
      hint:'Si pas de fécondation, la paroi utérine (endomètre) se détache → saignements = règles.' },
    { key:'cyc-5', q:'La fécondation a lieu habituellement :',
      options:['Dans l\'utérus','Dans une trompe','Dans l\'ovaire','Dans le vagin'], correct:1,
      hint:'Rencontre ovule-spermatozoïde dans une trompe de Fallope, puis l\'œuf migre vers l\'utérus.' },
    { key:'cyc-6', q:'La durée normale d\'une grossesse humaine est d\'environ :',
      options:['3 mois','6 mois','9 mois','12 mois'], correct:2,
      hint:'Environ 9 mois (40 semaines d\'aménorrhée).' },
  ],

  contraception: [
    { key:'con-1', q:'Le SIDA est causé par :',
      options:['Une bactérie','Un virus (le VIH)','Un champignon','Un parasite'], correct:1,
      hint:'VIH = Virus de l\'Immunodéficience Humaine. Il détruit les défenses immunitaires.' },
    { key:'con-2', q:'Quelle méthode de contraception protège aussi des IST ?',
      options:['La pilule','Le préservatif','Le stérilet','Rien'], correct:1,
      hint:'Seul le préservatif protège à la fois d\'une grossesse non désirée ET des IST.' },
    { key:'con-3', q:'Les IST se transmettent principalement par :',
      options:['Les poignées de main','Les relations sexuelles non protégées','L\'air','Les repas'], correct:1,
      hint:'IST = Infections Sexuellement Transmissibles. Transmission essentiellement lors des rapports sexuels.' },
    { key:'con-4', q:'La pilule contraceptive agit en :',
      options:['Bloquant l\'ovulation','Tuant les spermatozoïdes','Protégeant des IST','Stoppant les règles définitivement'], correct:0,
      hint:'La pilule apporte des hormones qui empêchent l\'ovulation.' },
    { key:'con-5', q:'Exemples d\'IST à connaître :',
      options:['Grippe, rhume','VIH/SIDA, chlamydia, hépatite B','Eczéma','Diabète'], correct:1,
      hint:'IST courantes : VIH, chlamydiose, hépatite B, gonorrhée, papillomavirus (HPV), syphilis.' },
    { key:'con-6', q:'En cas de rapport à risque, on peut utiliser :',
      options:['Une pilule du lendemain (contraception d\'urgence)','Un simple antidouleur','Du jus de citron','Rien'], correct:0,
      hint:'Contraception d\'urgence = pilule à prendre au plus tôt après le rapport. Et consulter pour un test IST.' },
  ],

  plaques: [
    { key:'pla-1', q:'La surface de la Terre est découpée en :',
      options:['2 morceaux','Des plaques lithosphériques','Des continents fixes','Un seul bloc'], correct:1,
      hint:'La lithosphère est découpée en une dizaine de plaques qui bougent lentement.' },
    { key:'pla-2', q:'Les plaques lithosphériques se déplacent de :',
      options:['Quelques km par seconde','Quelques cm par an','Quelques mètres par heure','Elles ne bougent pas'], correct:1,
      hint:'Vitesse de l\'ordre de quelques cm/an (aussi vite que pousse un ongle).' },
    { key:'pla-3', q:'Aux dorsales océaniques :',
      options:['Les plaques se rapprochent','Les plaques s\'écartent (création de croûte)','Rien ne bouge','Des volcans explosifs apparaissent'], correct:1,
      hint:'Dorsale = zone de divergence. Création de nouvelle croûte océanique par remontée de magma.' },
    { key:'pla-4', q:'Aux zones de subduction :',
      options:['Une plaque plonge sous une autre','Les plaques se séparent','Rien ne se passe','Un désert se forme'], correct:0,
      hint:'Subduction = convergence où la plaque océanique plonge sous l\'autre → séismes et volcanisme.' },
    { key:'pla-5', q:'Les mouvements des plaques sont responsables :',
      options:['Des séismes et du volcanisme','De la rotation de la Terre','Des saisons','Des marées'], correct:0,
      hint:'Les limites de plaques concentrent séismes et volcans ; ces mouvements forment aussi les chaînes de montagnes.' },
  ],

  seismes: [
    { key:'sei-1', q:'L\'endroit où se produit la rupture à l\'origine d\'un séisme s\'appelle :',
      options:['L\'épicentre','Le foyer (ou hypocentre)','La faille','Le magma'], correct:1,
      hint:'Foyer = point de la rupture en profondeur. Épicentre = point en surface juste au-dessus.' },
    { key:'sei-2', q:'Les séismes se propagent sous forme :',
      options:['De courants d\'air','D\'ondes sismiques','De chaleur','De lumière'], correct:1,
      hint:'Ondes sismiques (P rapides, puis S, puis L de surface). Détectées par les sismographes.' },
    { key:'sei-3', q:'Les séismes résultent :',
      options:['De marées','D\'une rupture brutale des roches en profondeur','D\'orages','Du vent'], correct:1,
      hint:'Les roches accumulent des contraintes, puis cassent brutalement → ondes qui se propagent.' },
    { key:'sei-4', q:'Le risque sismique dépend :',
      options:['Uniquement de l\'aléa','De l\'aléa et de la vulnérabilité','De la météo','De la population seule'], correct:1,
      hint:'Risque = aléa (probabilité d\'un séisme) × enjeu/vulnérabilité (constructions, population).' },
    { key:'sei-5', q:'La magnitude d\'un séisme se mesure sur :',
      options:['L\'échelle de Mercalli','L\'échelle de Richter','La règle graduée','Le thermomètre'], correct:1,
      hint:'Magnitude (Richter) = énergie libérée. Intensité (Mercalli) = effets ressentis en surface.' },
  ],

  volcans: [
    { key:'vol-1', q:'Le magma sort du volcan sous forme de :',
      options:['Gaz uniquement','Lave, bombes, cendres et gaz','Eau bouillante','Neige chaude'], correct:1,
      hint:'Lave (liquide), projections solides (bombes, cendres), gaz (vapeur d\'eau, CO₂, SO₂).' },
    { key:'vol-2', q:'Une éruption effusive se caractérise par :',
      options:['De grosses explosions','Des coulées de lave fluide','Des nuées ardentes uniquement','Aucune lave'], correct:1,
      hint:'Effusive = lave fluide qui coule (volcans hawaïens). Explosive = lave visqueuse + forte explosion (Vésuve).' },
    { key:'vol-3', q:'Une éruption explosive produit souvent :',
      options:['Des nuées ardentes','Uniquement de la neige','Rien de dangereux','Juste de la fumée'], correct:0,
      hint:'Nuées ardentes = mélange gaz+cendres+blocs à plus de 500 °C, dévalent à 100 km/h. Très mortel.' },
    { key:'vol-4', q:'Le magma est :',
      options:['De la roche fondue en profondeur','De l\'eau chaude','Du sable','Du sel'], correct:0,
      hint:'Magma = roche fondue dans la chambre magmatique. Une fois sorti = lave.' },
    { key:'vol-5', q:'Les volcans se forment principalement :',
      options:['N\'importe où','Aux limites des plaques tectoniques','Au centre des continents uniquement','Dans les déserts'], correct:1,
      hint:'Zones volcaniques = dorsales, zones de subduction, points chauds (ex. Hawaï).' },
  ],

  reproVeg: [
    { key:'veg-1', q:'Chez les plantes à fleurs, l\'organe reproducteur est :',
      options:['La feuille','La fleur','La racine','La tige'], correct:1,
      hint:'La fleur contient étamines (mâle, pollen) et pistil (femelle, ovules).' },
    { key:'veg-2', q:'La pollinisation est :',
      options:['Le transport du pollen vers le pistil','La germination','La pousse d\'une racine','La chute des feuilles'], correct:0,
      hint:'Pollinisation par vent, insectes (abeilles), oiseaux… Le pollen féconde l\'ovule du pistil.' },
    { key:'veg-3', q:'Après fécondation, l\'ovule devient :',
      options:['Une racine','Une graine','Une feuille','Un fruit'], correct:1,
      hint:'Ovule fécondé → graine. Le pistil (ovaire floral) se transforme en fruit.' },
    { key:'veg-4', q:'La reproduction asexuée chez les plantes :',
      options:['N\'existe pas','Produit des clones (bouturage, marcottage)','Nécessite deux parents','Est rare'], correct:1,
      hint:'Reproduction asexuée = bouturage, marcottage, stolons. Descendants identiques au parent.' },
    { key:'veg-5', q:'Le rôle du fruit est principalement :',
      options:['Décorer la plante','Protéger la graine et favoriser sa dispersion','Produire de l\'énergie','Empêcher la pollinisation'], correct:1,
      hint:'Le fruit protège la graine et aide à sa dispersion (animaux, vent, eau).' },
  ],

  biodiversite: [
    { key:'bio-1', q:'La biodiversité désigne :',
      options:['Seulement les animaux','La diversité du vivant (espèces, gènes, écosystèmes)','Seulement les plantes','Les minéraux'], correct:1,
      hint:'Biodiversité = diversité des espèces + diversité génétique + diversité des écosystèmes.' },
    { key:'bio-2', q:'Les fossiles permettent :',
      options:['De dater les roches et d\'étudier l\'évolution','De chauffer les maisons','De produire de l\'électricité','De manger'], correct:0,
      hint:'Fossiles = témoins de la vie passée. Ils montrent que les espèces ont changé au cours des temps géologiques.' },
    { key:'bio-3', q:'Les espèces actuelles :',
      options:['Existent depuis toujours','Résultent d\'une évolution à partir d\'ancêtres communs','Ont été créées récemment','N\'ont pas de lien entre elles'], correct:1,
      hint:'Les espèces évoluent au cours du temps par sélection naturelle (Darwin).' },
    { key:'bio-4', q:'L\'activité humaine peut :',
      options:['Toujours augmenter la biodiversité','Menacer la biodiversité (destruction d\'habitats, pollution)','N\'avoir aucun impact','Créer des espèces'], correct:1,
      hint:'Pollution, déforestation, surexploitation, changement climatique → 6ᵉ extinction de masse en cours.' },
    { key:'bio-5', q:'Deux espèces appartenant à un même groupe ont :',
      options:['Rien en commun','Un ancêtre commun','Obligatoirement la même taille','Obligatoirement le même habitat'], correct:1,
      hint:'La parenté phylogénétique se lit via les caractères communs hérités d\'un ancêtre commun.' },
  ],

  nutrition: [
    { key:'nut-1', q:'Lors de la respiration, le corps :',
      options:['Rejette du O₂ et absorbe du CO₂','Absorbe du O₂ et rejette du CO₂','N\'échange rien','Rejette de l\'azote'], correct:1,
      hint:'On inspire du dioxygène (O₂) et on rejette du dioxyde de carbone (CO₂) issu des cellules.' },
    { key:'nut-2', q:'Les échanges gazeux respiratoires ont lieu dans :',
      options:['L\'estomac','Les alvéoles pulmonaires','Le cœur','Le foie'], correct:1,
      hint:'Alvéoles = petits sacs au bout des bronchioles, très vascularisés → échanges O₂/CO₂ avec le sang.' },
    { key:'nut-3', q:'Le sang est mis en mouvement par :',
      options:['Les muscles','Le cœur','Les poumons','L\'estomac'], correct:1,
      hint:'Le cœur fait circuler le sang dans les artères, capillaires et veines (appareil circulatoire).' },
    { key:'nut-4', q:'La digestion transforme les aliments en :',
      options:['Déchets uniquement','Nutriments absorbables par l\'intestin','Gaz','Eau pure'], correct:1,
      hint:'Digestion mécanique + chimique → nutriments → absorbés dans l\'intestin grêle puis transportés par le sang.' },
    { key:'nut-5', q:'Les nutriments sont transportés dans le corps par :',
      options:['L\'air','Le sang','La peau','La salive'], correct:1,
      hint:'Le sang apporte aux organes dioxygène et nutriments, et emporte les déchets (CO₂, urée).' },
    { key:'nut-6', q:'Les cellules produisent de l\'énergie à partir :',
      options:['Uniquement d\'eau','De nutriments + dioxygène','De lumière directement (sauf plantes)','De rien, elles en ont par elles-mêmes'], correct:1,
      hint:'Respiration cellulaire : nutriments + O₂ → énergie + CO₂ + eau.' },
  ],

  environnement: [
    { key:'env-1', q:'Pour rester en bonne santé, il est important :',
      options:['De manger varié, bouger, dormir suffisamment','De rester couché toute la journée','De manger uniquement du sucre','De sauter les repas'], correct:0,
      hint:'Hygiène de vie = alimentation équilibrée + activité physique + sommeil + hygiène corporelle.' },
    { key:'env-2', q:'Le tabac et l\'alcool :',
      options:['Sont sans effet','Sont des facteurs de risque pour la santé','Aident à grandir','Sont recommandés aux ados'], correct:1,
      hint:'Tabac : cancers, maladies cardiovasculaires. Alcool : foie, cerveau, dépendance.' },
    { key:'env-3', q:'Un écosystème comprend :',
      options:['Uniquement les animaux','Les êtres vivants + leur milieu','Les roches seules','Les humains seuls'], correct:1,
      hint:'Écosystème = biocénose (communauté vivante) + biotope (milieu physique).' },
    { key:'env-4', q:'Les activités humaines peuvent modifier un écosystème par :',
      options:['Pollution, urbanisation, déforestation','Rien','Seulement la pluie','La rotation de la Terre'], correct:0,
      hint:'Actions humaines majeures : pollution, urbanisation, agriculture intensive, changement climatique.' },
  ],
  },
  PICK: {
  reproduction: 3, cycle: 3, contraception: 3, plaques: 3, seismes: 3,
  volcans: 3, reproVeg: 3, biodiversite: 3, nutrition: 4, environnement: 2,
  },
  PLANS: {
    reproduction: {
      'non-acquis': ['Revoir le schéma légendé des appareils reproducteurs (masculin et féminin)', 'Mémoriser les organes : testicules, ovaires, utérus, trompes, pénis, vagin', 'Rôle des hormones : testostérone, œstrogènes, progestérone'],
      'fragile':    ['Distinguer caractères sexuels primaires vs secondaires', 'Chronologie de la puberté']
    },
    cycle: {
      'non-acquis': ['Frise du cycle menstruel sur 28 jours avec ovulation au J14', 'Définir : menstruations, ovulation, fécondation, nidation', 'Localiser la fécondation (dans une trompe) et la nidation (utérus)'],
      'fragile':    ['Comprendre la coordination hormones / ovaires / utérus', 'Durée de vie des spermatozoïdes (5j) et ovule (24h) → période féconde']
    },
    contraception: {
      'non-acquis': ['PRIORITÉ : apprendre que seul le préservatif protège des IST', 'Citer 3-4 IST : VIH, chlamydia, hépatite B, HPV', 'Retenir les méthodes principales : préservatif, pilule, stérilet (DIU)'],
      'fragile':    ['Comprendre mode d\'action de la pilule (blocage ovulation)', 'Savoir où se faire dépister (CeGIDD, planning familial)']
    },
    plaques: {
      'non-acquis': ['Mémoriser : la lithosphère est découpée en plaques qui bougent', 'Vitesse ~ quelques cm/an', 'Limites de plaques : dorsales (divergence) et subduction (convergence)'],
      'fragile':    ['Savoir situer sur un planisphère les grandes plaques et les zones sismiques/volcaniques']
    },
    seismes: {
      'non-acquis': ['Distinguer : foyer (profondeur) et épicentre (surface)', 'Cause : rupture brutale des roches → ondes sismiques', 'Différence magnitude (Richter) / intensité (Mercalli)'],
      'fragile':    ['Mesures de prévention : normes parasismiques, plans d\'évacuation', 'Notion de risque = aléa × vulnérabilité']
    },
    volcans: {
      'non-acquis': ['Effusif (lave fluide, coulées) vs explosif (nuées ardentes, forte explosion)', 'Magma → lave + gaz + projections solides', 'Volcans liés aux limites de plaques (zones de subduction surtout)'],
      'fragile':    ['Exemples : Piton de la Fournaise (effusif), Vésuve / Montagne Pelée (explosif)']
    },
    reproVeg: {
      'non-acquis': ['Schéma d\'une fleur : pétales, sépales, étamines (♂), pistil (♀)', 'Pollinisation : vent, insectes → fécondation', 'Ovule → graine ; ovaire → fruit'],
      'fragile':    ['Reproduction asexuée : bouturage, marcottage, stolon (clones)']
    },
    biodiversite: {
      'non-acquis': ['Biodiversité = diversité des espèces + gènes + écosystèmes', 'Fossiles = preuves de l\'évolution', 'Notion d\'ancêtre commun'],
      'fragile':    ['Impact des activités humaines sur la biodiversité', 'Introduction à la sélection naturelle (Darwin)']
    },
    nutrition: {
      'non-acquis': ['Respiration : O₂ entre, CO₂ sort (échanges dans les alvéoles)', 'Digestion → nutriments → sang → cellules', 'Cœur = pompe ; sang = transport des nutriments et gaz'],
      'fragile':    ['Respiration cellulaire : nutriments + O₂ → énergie + CO₂', 'Trajet du sang : cœur → artères → capillaires → veines → cœur']
    },
    environnement: {
      'non-acquis': ['Hygiène de vie : alimentation variée, sommeil, activité physique', 'Dangers du tabac et de l\'alcool', 'Écosystème = êtres vivants + milieu'],
      'fragile':    ['Actions humaines qui perturbent les écosystèmes (pollution, déforestation, climat)']
    },
  },
};
